<?php
/**
 * BenefitsApi
 * PHP version 8.1
 *
 * @category Class
 * @package  BhrSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BambooHR API
 *
 * BambooHR API documentation. https://www.bamboohr.com/api/documentation/
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace BhrSdk\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use BhrSdk\ApiException;
use BhrSdk\Configuration;
use BhrSdk\FormDataProcessor;
use BhrSdk\HeaderSelector;
use BhrSdk\ObjectSerializer;
use BhrSdk\Client\Logger\LoggerInterface;
use BhrSdk\ApiHelper;

/**
 * BenefitsApi Class Doc Comment
 *
 * @category Class
 * @package  BhrSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BenefitsApi {
	/**
	 * @var ClientInterface
	 */
	protected $client;

	/**
	 * @var Configuration
	 */
	protected $config;

	/**
	 * @var HeaderSelector
	 */
	protected $headerSelector;

	/**
	 * @var int Host index
	 */
	protected $hostIndex;

	/**
	 * @var LoggerInterface|null Logger instance
	 */
	protected $logger;

	/** @var string[] $CONTENT_TYPES **/
	public const CONTENT_TYPES = [
		'addEmployeeDependent' => [
			'application/json',
        ],
		'getBenefitCoverages' => [
			'application/json',
        ],
		'getBenefitDeductionTypes' => [
			'application/json',
        ],
		'getEmployeeDependent' => [
			'application/json',
        ],
		'getEmployeeDependents' => [
			'application/json',
        ],
		'getMemberBenefit' => [
			'application/json',
        ],
		'updateEmployeeDependent' => [
			'application/json',
        ],
	];

	/**
	 * @param ClientInterface $client
	 * @param Configuration   $config
	 * @param HeaderSelector  $selector
	 * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
	 * @param LoggerInterface|null $logger (Optional) logger instance for secure logging
	 */
	public function __construct(
		?ClientInterface $client = null,
		?Configuration $config = null,
		?HeaderSelector $selector = null,
		int $hostIndex = 0,
		?LoggerInterface $logger = null
	) {
		$this->client = $client ?: new Client();
		$this->config = $config ?: Configuration::getDefaultConfiguration();
		$this->headerSelector = $selector ?: new HeaderSelector();
		$this->hostIndex = $hostIndex;
		$this->logger = $logger;
	}

	/**
	 * Set the host index
	 *
	 * @param int $hostIndex Host index (required)
	 */
	public function setHostIndex($hostIndex): void {
		$this->hostIndex = $hostIndex;
	}

	/**
	 * Get the host index
	 *
	 * @return int Host index
	 */
	public function getHostIndex() {
		return $this->hostIndex;
	}

	/**
	 * @return Configuration
	 */
	public function getConfig() {
		return $this->config;
	}

	/**
	 * Operation addEmployeeDependent
	 *
	 * Add an employee dependent
	 *
	 * @param  \BhrSdk\Model\EmployeeDependent $employee_dependent employee_dependent (required)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['addEmployeeDependent'] to see the possible values for this operation
	 *
	 * @throws \BhrSdk\ApiException on non-2xx response or if the response body is not in the expected format
	 * @throws \InvalidArgumentException
	 * @return void
	 */
	public function addEmployeeDependent($employee_dependent, string $contentType = self::CONTENT_TYPES['addEmployeeDependent'][0]) {
		$this->addEmployeeDependentWithHttpInfo($employee_dependent, $contentType);
	}

	/**
	 * Operation addEmployeeDependentWithHttpInfo
	 *
	 * Add an employee dependent
	 *
	 * @param  \BhrSdk\Model\EmployeeDependent $employee_dependent (required)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['addEmployeeDependent'] to see the possible values for this operation
	 *
	 * @throws \BhrSdk\ApiException on non-2xx response or if the response body is not in the expected format
	 * @throws \InvalidArgumentException
	 * @return array of null, HTTP status code, HTTP response headers (array of strings)
	 */
	public function addEmployeeDependentWithHttpInfo($employee_dependent, string $contentType = self::CONTENT_TYPES['addEmployeeDependent'][0]) {
		$request = $this->addEmployeeDependentRequest($employee_dependent, $contentType);
		$options = ApiHelper::createHttpClientOption($this->config);
		
		// Send request with retry support for timeout errors
		$response = ApiHelper::sendRequestWithRetries($this->client, $this->config, $request, $options);

		$statusCode = $response->getStatusCode();

		return ApiHelper::handleResponseWithDataType(
			'object', // or 'mixed' or any other generic type
			$request,
			$response,
		);
	}

	/**
	 * Operation addEmployeeDependentAsync
	 *
	 * Add an employee dependent
	 *
	 * @param  \BhrSdk\Model\EmployeeDependent $employee_dependent (required)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['addEmployeeDependent'] to see the possible values for this operation
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Promise\PromiseInterface
	 */
	public function addEmployeeDependentAsync($employee_dependent, string $contentType = self::CONTENT_TYPES['addEmployeeDependent'][0]) {
		return $this->addEmployeeDependentAsyncWithHttpInfo($employee_dependent, $contentType)
			->then(
				function ($response) {
					return $response[0];
				}
			);
	}

	/**
	 * Operation addEmployeeDependentAsyncWithHttpInfo
	 *
	 * Add an employee dependent
	 *
	 * @param  \BhrSdk\Model\EmployeeDependent $employee_dependent (required)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['addEmployeeDependent'] to see the possible values for this operation
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Promise\PromiseInterface
	 */
	public function addEmployeeDependentAsyncWithHttpInfo($employee_dependent, string $contentType = self::CONTENT_TYPES['addEmployeeDependent'][0]) {
		
		$request = $this->addEmployeeDependentRequest($employee_dependent, $contentType);

		return ApiHelper::sendRequestWithRetriesAsync($this->client, $this->config, $request, ApiHelper::createHttpClientOption($this->config))
			->then(
				function ($response) {
					$content = (string) $response->getBody();
					$content = json_decode($content);

					return [
						ObjectSerializer::deserialize($content, 'object', []),
						$response->getStatusCode(),
						$response->getHeaders()
					];
				},
				function ($exception) {
					$response = $exception->getResponse();
					$statusCode = $response->getStatusCode();
					throw new ApiException(
						sprintf(
							'[%d] Error connecting to the API (%s)',
							$statusCode,
							$exception->getRequest()->getUri()
						),
						$statusCode,
						$response->getHeaders(),
						(string) $response->getBody()
					);
				}
			);
	}

	/**
	 * Create request for operation 'addEmployeeDependent'
	 *
	 * @param  \BhrSdk\Model\EmployeeDependent $employee_dependent (required)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['addEmployeeDependent'] to see the possible values for this operation
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Psr7\Request
	 */
	public function addEmployeeDependentRequest($employee_dependent, string $contentType = self::CONTENT_TYPES['addEmployeeDependent'][0]) {
		// PHP 8.0+ only
		ApiHelper::validateRequiredParameters(
			params: [
				'employee_dependent' => $employee_dependent,
			],
			methodName: 'addEmployeeDependent'
		);

		$resourcePath = '/api/v1/employeedependents';
		
		$queryParams = [];
		$headerParams = [];
		$httpBody = '';
		$multipart = false;

		$headers = $this->headerSelector->selectHeaders(
			['application/json', ],
			$contentType,
			$multipart
		);

		// for model (json/xml)
		if (isset($employee_dependent)) {
			if (stripos($headers['Content-Type'], 'application/json') !== false) {
				# if Content-Type contains "application/json", json_encode the body
				$httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($employee_dependent));
			} else {
				$httpBody = $employee_dependent;
			}
		} 

		// Authentication methods
		
		// Basic authentication
		if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
			$headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
		}
		
		// OAuth/Bearer authentication
		if (!empty($this->config->getAccessToken())) {
			$headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
		}

		$defaultHeaders = [];
		if ($this->config->getUserAgent()) {
			$defaultHeaders['User-Agent'] = $this->config->getUserAgent();
		}

		$headers = array_merge(
			$defaultHeaders,
			$headerParams,
			$headers
		);
		
		// Special handling for accept_header_parameter to set the Accept header directly
		if (isset($accept_header_parameter) && $accept_header_parameter !== null) {
			$headers['Accept'] = ObjectSerializer::toHeaderValue($accept_header_parameter);
		}

		$operationHost = $this->config->getHost();
		$query = ObjectSerializer::buildQuery($queryParams);
		return new Request(
			'POST',
			$operationHost . $resourcePath . ($query ? "?{$query}" : ''),
			$headers,
			$httpBody
		);
	}

	/**
	 * Operation getBenefitCoverages
	 *
	 * Get benefit coverages
	 *
	 * @param  string|null $accept_header_parameter This endpoint can produce either JSON or XML. (optional)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['getBenefitCoverages'] to see the possible values for this operation
	 *
	 * @throws \BhrSdk\ApiException on non-2xx response or if the response body is not in the expected format
	 * @throws \InvalidArgumentException
	 * @return void
	 */
	public function getBenefitCoverages($accept_header_parameter = null, string $contentType = self::CONTENT_TYPES['getBenefitCoverages'][0]) {
		$this->getBenefitCoveragesWithHttpInfo($accept_header_parameter, $contentType);
	}

	/**
	 * Operation getBenefitCoveragesWithHttpInfo
	 *
	 * Get benefit coverages
	 *
	 * @param  string|null $accept_header_parameter This endpoint can produce either JSON or XML. (optional)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['getBenefitCoverages'] to see the possible values for this operation
	 *
	 * @throws \BhrSdk\ApiException on non-2xx response or if the response body is not in the expected format
	 * @throws \InvalidArgumentException
	 * @return array of null, HTTP status code, HTTP response headers (array of strings)
	 */
	public function getBenefitCoveragesWithHttpInfo($accept_header_parameter = null, string $contentType = self::CONTENT_TYPES['getBenefitCoverages'][0]) {
		$request = $this->getBenefitCoveragesRequest($accept_header_parameter, $contentType);
		$options = ApiHelper::createHttpClientOption($this->config);
		
		// Send request with retry support for timeout errors
		$response = ApiHelper::sendRequestWithRetries($this->client, $this->config, $request, $options);

		$statusCode = $response->getStatusCode();

		return ApiHelper::handleResponseWithDataType(
			'object', // or 'mixed' or any other generic type
			$request,
			$response,
		);
	}

	/**
	 * Operation getBenefitCoveragesAsync
	 *
	 * Get benefit coverages
	 *
	 * @param  string|null $accept_header_parameter This endpoint can produce either JSON or XML. (optional)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['getBenefitCoverages'] to see the possible values for this operation
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Promise\PromiseInterface
	 */
	public function getBenefitCoveragesAsync($accept_header_parameter = null, string $contentType = self::CONTENT_TYPES['getBenefitCoverages'][0]) {
		return $this->getBenefitCoveragesAsyncWithHttpInfo($accept_header_parameter, $contentType)
			->then(
				function ($response) {
					return $response[0];
				}
			);
	}

	/**
	 * Operation getBenefitCoveragesAsyncWithHttpInfo
	 *
	 * Get benefit coverages
	 *
	 * @param  string|null $accept_header_parameter This endpoint can produce either JSON or XML. (optional)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['getBenefitCoverages'] to see the possible values for this operation
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Promise\PromiseInterface
	 */
	public function getBenefitCoveragesAsyncWithHttpInfo($accept_header_parameter = null, string $contentType = self::CONTENT_TYPES['getBenefitCoverages'][0]) {
		
		$request = $this->getBenefitCoveragesRequest($accept_header_parameter, $contentType);

		return ApiHelper::sendRequestWithRetriesAsync($this->client, $this->config, $request, ApiHelper::createHttpClientOption($this->config))
			->then(
				function ($response) {
					$content = (string) $response->getBody();
					$content = json_decode($content);

					return [
						ObjectSerializer::deserialize($content, 'object', []),
						$response->getStatusCode(),
						$response->getHeaders()
					];
				},
				function ($exception) {
					$response = $exception->getResponse();
					$statusCode = $response->getStatusCode();
					throw new ApiException(
						sprintf(
							'[%d] Error connecting to the API (%s)',
							$statusCode,
							$exception->getRequest()->getUri()
						),
						$statusCode,
						$response->getHeaders(),
						(string) $response->getBody()
					);
				}
			);
	}

	/**
	 * Create request for operation 'getBenefitCoverages'
	 *
	 * @param  string|null $accept_header_parameter This endpoint can produce either JSON or XML. (optional)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['getBenefitCoverages'] to see the possible values for this operation
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Psr7\Request
	 */
	public function getBenefitCoveragesRequest($accept_header_parameter = null, string $contentType = self::CONTENT_TYPES['getBenefitCoverages'][0]) {

		$resourcePath = '/api/v1/benefitcoverages';
		
		$queryParams = [];
		$headerParams = [];
		$httpBody = '';
		$multipart = false;

		// header params
		if ($accept_header_parameter !== null) {
			$headerParams['AcceptHeaderParameter'] = ObjectSerializer::toHeaderValue($accept_header_parameter);
		}

		$headers = $this->headerSelector->selectHeaders(
			['application/json', 'application/xml', ],
			$contentType,
			$multipart
		);

		// Authentication methods
		
		// Basic authentication
		if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
			$headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
		}
		
		// OAuth/Bearer authentication
		if (!empty($this->config->getAccessToken())) {
			$headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
		}

		$defaultHeaders = [];
		if ($this->config->getUserAgent()) {
			$defaultHeaders['User-Agent'] = $this->config->getUserAgent();
		}

		$headers = array_merge(
			$defaultHeaders,
			$headerParams,
			$headers
		);
		
		// Special handling for accept_header_parameter to set the Accept header directly
		if (isset($accept_header_parameter) && $accept_header_parameter !== null) {
			$headers['Accept'] = ObjectSerializer::toHeaderValue($accept_header_parameter);
		}

		$operationHost = $this->config->getHost();
		$query = ObjectSerializer::buildQuery($queryParams);
		return new Request(
			'GET',
			$operationHost . $resourcePath . ($query ? "?{$query}" : ''),
			$headers,
			$httpBody
		);
	}

	/**
	 * Operation getBenefitDeductionTypes
	 *
	 * Get benefit deduction types
	 *
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['getBenefitDeductionTypes'] to see the possible values for this operation
	 *
	 * @throws \BhrSdk\ApiException on non-2xx response or if the response body is not in the expected format
	 * @throws \InvalidArgumentException
	 * @return void
	 */
	public function getBenefitDeductionTypes(string $contentType = self::CONTENT_TYPES['getBenefitDeductionTypes'][0]) {
		$this->getBenefitDeductionTypesWithHttpInfo($contentType);
	}

	/**
	 * Operation getBenefitDeductionTypesWithHttpInfo
	 *
	 * Get benefit deduction types
	 *
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['getBenefitDeductionTypes'] to see the possible values for this operation
	 *
	 * @throws \BhrSdk\ApiException on non-2xx response or if the response body is not in the expected format
	 * @throws \InvalidArgumentException
	 * @return array of null, HTTP status code, HTTP response headers (array of strings)
	 */
	public function getBenefitDeductionTypesWithHttpInfo(string $contentType = self::CONTENT_TYPES['getBenefitDeductionTypes'][0]) {
		$request = $this->getBenefitDeductionTypesRequest($contentType);
		$options = ApiHelper::createHttpClientOption($this->config);
		
		// Send request with retry support for timeout errors
		$response = ApiHelper::sendRequestWithRetries($this->client, $this->config, $request, $options);

		$statusCode = $response->getStatusCode();

		return ApiHelper::handleResponseWithDataType(
			'object', // or 'mixed' or any other generic type
			$request,
			$response,
		);
	}

	/**
	 * Operation getBenefitDeductionTypesAsync
	 *
	 * Get benefit deduction types
	 *
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['getBenefitDeductionTypes'] to see the possible values for this operation
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Promise\PromiseInterface
	 */
	public function getBenefitDeductionTypesAsync(string $contentType = self::CONTENT_TYPES['getBenefitDeductionTypes'][0]) {
		return $this->getBenefitDeductionTypesAsyncWithHttpInfo($contentType)
			->then(
				function ($response) {
					return $response[0];
				}
			);
	}

	/**
	 * Operation getBenefitDeductionTypesAsyncWithHttpInfo
	 *
	 * Get benefit deduction types
	 *
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['getBenefitDeductionTypes'] to see the possible values for this operation
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Promise\PromiseInterface
	 */
	public function getBenefitDeductionTypesAsyncWithHttpInfo(string $contentType = self::CONTENT_TYPES['getBenefitDeductionTypes'][0]) {
		
		$request = $this->getBenefitDeductionTypesRequest($contentType);

		return ApiHelper::sendRequestWithRetriesAsync($this->client, $this->config, $request, ApiHelper::createHttpClientOption($this->config))
			->then(
				function ($response) {
					$content = (string) $response->getBody();
					$content = json_decode($content);

					return [
						ObjectSerializer::deserialize($content, 'object', []),
						$response->getStatusCode(),
						$response->getHeaders()
					];
				},
				function ($exception) {
					$response = $exception->getResponse();
					$statusCode = $response->getStatusCode();
					throw new ApiException(
						sprintf(
							'[%d] Error connecting to the API (%s)',
							$statusCode,
							$exception->getRequest()->getUri()
						),
						$statusCode,
						$response->getHeaders(),
						(string) $response->getBody()
					);
				}
			);
	}

	/**
	 * Create request for operation 'getBenefitDeductionTypes'
	 *
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['getBenefitDeductionTypes'] to see the possible values for this operation
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Psr7\Request
	 */
	public function getBenefitDeductionTypesRequest(string $contentType = self::CONTENT_TYPES['getBenefitDeductionTypes'][0]) {

		$resourcePath = '/api/v1/benefits/settings/deduction_types/all';
		
		$queryParams = [];
		$headerParams = [];
		$httpBody = '';
		$multipart = false;

		$headers = $this->headerSelector->selectHeaders(
			['application/json', ],
			$contentType,
			$multipart
		);

		// Authentication methods
		
		// Basic authentication
		if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
			$headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
		}
		
		// OAuth/Bearer authentication
		if (!empty($this->config->getAccessToken())) {
			$headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
		}

		$defaultHeaders = [];
		if ($this->config->getUserAgent()) {
			$defaultHeaders['User-Agent'] = $this->config->getUserAgent();
		}

		$headers = array_merge(
			$defaultHeaders,
			$headerParams,
			$headers
		);
		
		// Special handling for accept_header_parameter to set the Accept header directly
		if (isset($accept_header_parameter) && $accept_header_parameter !== null) {
			$headers['Accept'] = ObjectSerializer::toHeaderValue($accept_header_parameter);
		}

		$operationHost = $this->config->getHost();
		$query = ObjectSerializer::buildQuery($queryParams);
		return new Request(
			'GET',
			$operationHost . $resourcePath . ($query ? "?{$query}" : ''),
			$headers,
			$httpBody
		);
	}

	/**
	 * Operation getEmployeeDependent
	 *
	 * Get employee dependent
	 *
	 * @param  string $id {id} is the employee dependent ID. (required)
	 * @param  string|null $accept_header_parameter This endpoint can produce either JSON or XML. (optional)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['getEmployeeDependent'] to see the possible values for this operation
	 *
	 * @throws \BhrSdk\ApiException on non-2xx response or if the response body is not in the expected format
	 * @throws \InvalidArgumentException
	 * @return void
	 */
	public function getEmployeeDependent($id, $accept_header_parameter = null, string $contentType = self::CONTENT_TYPES['getEmployeeDependent'][0]) {
		$this->getEmployeeDependentWithHttpInfo($id, $accept_header_parameter, $contentType);
	}

	/**
	 * Operation getEmployeeDependentWithHttpInfo
	 *
	 * Get employee dependent
	 *
	 * @param  string $id {id} is the employee dependent ID. (required)
	 * @param  string|null $accept_header_parameter This endpoint can produce either JSON or XML. (optional)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['getEmployeeDependent'] to see the possible values for this operation
	 *
	 * @throws \BhrSdk\ApiException on non-2xx response or if the response body is not in the expected format
	 * @throws \InvalidArgumentException
	 * @return array of null, HTTP status code, HTTP response headers (array of strings)
	 */
	public function getEmployeeDependentWithHttpInfo($id, $accept_header_parameter = null, string $contentType = self::CONTENT_TYPES['getEmployeeDependent'][0]) {
		$request = $this->getEmployeeDependentRequest($id, $accept_header_parameter, $contentType);
		$options = ApiHelper::createHttpClientOption($this->config);
		
		// Send request with retry support for timeout errors
		$response = ApiHelper::sendRequestWithRetries($this->client, $this->config, $request, $options);

		$statusCode = $response->getStatusCode();

		return ApiHelper::handleResponseWithDataType(
			'object', // or 'mixed' or any other generic type
			$request,
			$response,
		);
	}

	/**
	 * Operation getEmployeeDependentAsync
	 *
	 * Get employee dependent
	 *
	 * @param  string $id {id} is the employee dependent ID. (required)
	 * @param  string|null $accept_header_parameter This endpoint can produce either JSON or XML. (optional)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['getEmployeeDependent'] to see the possible values for this operation
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Promise\PromiseInterface
	 */
	public function getEmployeeDependentAsync($id, $accept_header_parameter = null, string $contentType = self::CONTENT_TYPES['getEmployeeDependent'][0]) {
		return $this->getEmployeeDependentAsyncWithHttpInfo($id, $accept_header_parameter, $contentType)
			->then(
				function ($response) {
					return $response[0];
				}
			);
	}

	/**
	 * Operation getEmployeeDependentAsyncWithHttpInfo
	 *
	 * Get employee dependent
	 *
	 * @param  string $id {id} is the employee dependent ID. (required)
	 * @param  string|null $accept_header_parameter This endpoint can produce either JSON or XML. (optional)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['getEmployeeDependent'] to see the possible values for this operation
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Promise\PromiseInterface
	 */
	public function getEmployeeDependentAsyncWithHttpInfo($id, $accept_header_parameter = null, string $contentType = self::CONTENT_TYPES['getEmployeeDependent'][0]) {
		
		$request = $this->getEmployeeDependentRequest($id, $accept_header_parameter, $contentType);

		return ApiHelper::sendRequestWithRetriesAsync($this->client, $this->config, $request, ApiHelper::createHttpClientOption($this->config))
			->then(
				function ($response) {
					$content = (string) $response->getBody();
					$content = json_decode($content);

					return [
						ObjectSerializer::deserialize($content, 'object', []),
						$response->getStatusCode(),
						$response->getHeaders()
					];
				},
				function ($exception) {
					$response = $exception->getResponse();
					$statusCode = $response->getStatusCode();
					throw new ApiException(
						sprintf(
							'[%d] Error connecting to the API (%s)',
							$statusCode,
							$exception->getRequest()->getUri()
						),
						$statusCode,
						$response->getHeaders(),
						(string) $response->getBody()
					);
				}
			);
	}

	/**
	 * Create request for operation 'getEmployeeDependent'
	 *
	 * @param  string $id {id} is the employee dependent ID. (required)
	 * @param  string|null $accept_header_parameter This endpoint can produce either JSON or XML. (optional)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['getEmployeeDependent'] to see the possible values for this operation
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Psr7\Request
	 */
	public function getEmployeeDependentRequest($id, $accept_header_parameter = null, string $contentType = self::CONTENT_TYPES['getEmployeeDependent'][0]) {
		// PHP 8.0+ only
		ApiHelper::validateRequiredParameters(
			params: [
				'id' => $id,
			],
			methodName: 'getEmployeeDependent'
		);

		$resourcePath = '/api/v1/employeedependents/{id}';
		
		$queryParams = [];
		$headerParams = [];
		$httpBody = '';
		$multipart = false;

		// header params
		if ($accept_header_parameter !== null) {
			$headerParams['AcceptHeaderParameter'] = ObjectSerializer::toHeaderValue($accept_header_parameter);
		}

		// path params
		if ($id !== null) {
			$resourcePath = str_replace(
				'{' . 'id' . '}',
				ObjectSerializer::toPathValue($id),
				$resourcePath
			);
		}

		$headers = $this->headerSelector->selectHeaders(
			['application/json', 'application/xml', ],
			$contentType,
			$multipart
		);

		// Authentication methods
		
		// Basic authentication
		if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
			$headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
		}
		
		// OAuth/Bearer authentication
		if (!empty($this->config->getAccessToken())) {
			$headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
		}

		$defaultHeaders = [];
		if ($this->config->getUserAgent()) {
			$defaultHeaders['User-Agent'] = $this->config->getUserAgent();
		}

		$headers = array_merge(
			$defaultHeaders,
			$headerParams,
			$headers
		);
		
		// Special handling for accept_header_parameter to set the Accept header directly
		if (isset($accept_header_parameter) && $accept_header_parameter !== null) {
			$headers['Accept'] = ObjectSerializer::toHeaderValue($accept_header_parameter);
		}

		$operationHost = $this->config->getHost();
		$query = ObjectSerializer::buildQuery($queryParams);
		return new Request(
			'GET',
			$operationHost . $resourcePath . ($query ? "?{$query}" : ''),
			$headers,
			$httpBody
		);
	}

	/**
	 * Operation getEmployeeDependents
	 *
	 * Get all employee dependents
	 *
	 * @param  string $employeeid {employeeid} is the employee ID. Supplying this ID limits the response to the specific employee. (required)
	 * @param  string|null $accept_header_parameter This endpoint can produce either JSON or XML. (optional)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['getEmployeeDependents'] to see the possible values for this operation
	 *
	 * @throws \BhrSdk\ApiException on non-2xx response or if the response body is not in the expected format
	 * @throws \InvalidArgumentException
	 * @return void
	 */
	public function getEmployeeDependents($employeeid, $accept_header_parameter = null, string $contentType = self::CONTENT_TYPES['getEmployeeDependents'][0]) {
		$this->getEmployeeDependentsWithHttpInfo($employeeid, $accept_header_parameter, $contentType);
	}

	/**
	 * Operation getEmployeeDependentsWithHttpInfo
	 *
	 * Get all employee dependents
	 *
	 * @param  string $employeeid {employeeid} is the employee ID. Supplying this ID limits the response to the specific employee. (required)
	 * @param  string|null $accept_header_parameter This endpoint can produce either JSON or XML. (optional)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['getEmployeeDependents'] to see the possible values for this operation
	 *
	 * @throws \BhrSdk\ApiException on non-2xx response or if the response body is not in the expected format
	 * @throws \InvalidArgumentException
	 * @return array of null, HTTP status code, HTTP response headers (array of strings)
	 */
	public function getEmployeeDependentsWithHttpInfo($employeeid, $accept_header_parameter = null, string $contentType = self::CONTENT_TYPES['getEmployeeDependents'][0]) {
		$request = $this->getEmployeeDependentsRequest($employeeid, $accept_header_parameter, $contentType);
		$options = ApiHelper::createHttpClientOption($this->config);
		
		// Send request with retry support for timeout errors
		$response = ApiHelper::sendRequestWithRetries($this->client, $this->config, $request, $options);

		$statusCode = $response->getStatusCode();

		return ApiHelper::handleResponseWithDataType(
			'object', // or 'mixed' or any other generic type
			$request,
			$response,
		);
	}

	/**
	 * Operation getEmployeeDependentsAsync
	 *
	 * Get all employee dependents
	 *
	 * @param  string $employeeid {employeeid} is the employee ID. Supplying this ID limits the response to the specific employee. (required)
	 * @param  string|null $accept_header_parameter This endpoint can produce either JSON or XML. (optional)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['getEmployeeDependents'] to see the possible values for this operation
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Promise\PromiseInterface
	 */
	public function getEmployeeDependentsAsync($employeeid, $accept_header_parameter = null, string $contentType = self::CONTENT_TYPES['getEmployeeDependents'][0]) {
		return $this->getEmployeeDependentsAsyncWithHttpInfo($employeeid, $accept_header_parameter, $contentType)
			->then(
				function ($response) {
					return $response[0];
				}
			);
	}

	/**
	 * Operation getEmployeeDependentsAsyncWithHttpInfo
	 *
	 * Get all employee dependents
	 *
	 * @param  string $employeeid {employeeid} is the employee ID. Supplying this ID limits the response to the specific employee. (required)
	 * @param  string|null $accept_header_parameter This endpoint can produce either JSON or XML. (optional)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['getEmployeeDependents'] to see the possible values for this operation
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Promise\PromiseInterface
	 */
	public function getEmployeeDependentsAsyncWithHttpInfo($employeeid, $accept_header_parameter = null, string $contentType = self::CONTENT_TYPES['getEmployeeDependents'][0]) {
		
		$request = $this->getEmployeeDependentsRequest($employeeid, $accept_header_parameter, $contentType);

		return ApiHelper::sendRequestWithRetriesAsync($this->client, $this->config, $request, ApiHelper::createHttpClientOption($this->config))
			->then(
				function ($response) {
					$content = (string) $response->getBody();
					$content = json_decode($content);

					return [
						ObjectSerializer::deserialize($content, 'object', []),
						$response->getStatusCode(),
						$response->getHeaders()
					];
				},
				function ($exception) {
					$response = $exception->getResponse();
					$statusCode = $response->getStatusCode();
					throw new ApiException(
						sprintf(
							'[%d] Error connecting to the API (%s)',
							$statusCode,
							$exception->getRequest()->getUri()
						),
						$statusCode,
						$response->getHeaders(),
						(string) $response->getBody()
					);
				}
			);
	}

	/**
	 * Create request for operation 'getEmployeeDependents'
	 *
	 * @param  string $employeeid {employeeid} is the employee ID. Supplying this ID limits the response to the specific employee. (required)
	 * @param  string|null $accept_header_parameter This endpoint can produce either JSON or XML. (optional)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['getEmployeeDependents'] to see the possible values for this operation
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Psr7\Request
	 */
	public function getEmployeeDependentsRequest($employeeid, $accept_header_parameter = null, string $contentType = self::CONTENT_TYPES['getEmployeeDependents'][0]) {
		// PHP 8.0+ only
		ApiHelper::validateRequiredParameters(
			params: [
				'employeeid' => $employeeid,
			],
			methodName: 'getEmployeeDependents'
		);

		$resourcePath = '/api/v1/employeedependents';
		
		$queryParams = [];
		$headerParams = [];
		$httpBody = '';
		$multipart = false;

		$parameters = [
			'employeeid' => ['value' => $employeeid, 'type' => 'string', 'required' => true, 'style' => 'form', 'explode' => true],
		];

		// Process parameters and build query values directly
		$queryParams = [];

		foreach ($parameters as $paramName => $config) {
			$value = ObjectSerializer::toQueryValue($config['value'], $paramName, $config['type'], $config['style'], $config['explode'], $config['required']);
			
			if ($value !== null) {
				// Merge each parameter value directly into queryParams
				$queryParams = array_merge($queryParams, $value);
			}
		}

		// header params
		if ($accept_header_parameter !== null) {
			$headerParams['AcceptHeaderParameter'] = ObjectSerializer::toHeaderValue($accept_header_parameter);
		}

		$headers = $this->headerSelector->selectHeaders(
			['application/json', 'application/xml', ],
			$contentType,
			$multipart
		);

		// Authentication methods
		
		// Basic authentication
		if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
			$headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
		}
		
		// OAuth/Bearer authentication
		if (!empty($this->config->getAccessToken())) {
			$headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
		}

		$defaultHeaders = [];
		if ($this->config->getUserAgent()) {
			$defaultHeaders['User-Agent'] = $this->config->getUserAgent();
		}

		$headers = array_merge(
			$defaultHeaders,
			$headerParams,
			$headers
		);
		
		// Special handling for accept_header_parameter to set the Accept header directly
		if (isset($accept_header_parameter) && $accept_header_parameter !== null) {
			$headers['Accept'] = ObjectSerializer::toHeaderValue($accept_header_parameter);
		}

		$operationHost = $this->config->getHost();
		$query = ObjectSerializer::buildQuery($queryParams);
		return new Request(
			'GET',
			$operationHost . $resourcePath . ($query ? "?{$query}" : ''),
			$headers,
			$httpBody
		);
	}

	/**
	 * Operation getMemberBenefit
	 *
	 * Get a list of member benefit events
	 *
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['getMemberBenefit'] to see the possible values for this operation
	 *
	 * @throws \BhrSdk\ApiException on non-2xx response or if the response body is not in the expected format
	 * @throws \InvalidArgumentException
	 * @return \BhrSdk\Model\MemberBenefitEvent[]
	 */
	public function getMemberBenefit(string $contentType = self::CONTENT_TYPES['getMemberBenefit'][0]) {
		list($response) = $this->getMemberBenefitWithHttpInfo($contentType);
		return $response;
	}

	/**
	 * Operation getMemberBenefitWithHttpInfo
	 *
	 * Get a list of member benefit events
	 *
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['getMemberBenefit'] to see the possible values for this operation
	 *
	 * @throws \BhrSdk\ApiException on non-2xx response or if the response body is not in the expected format
	 * @throws \InvalidArgumentException
	 * @return array of \BhrSdk\Model\MemberBenefitEvent[], HTTP status code, HTTP response headers (array of strings)
	 */
	public function getMemberBenefitWithHttpInfo(string $contentType = self::CONTENT_TYPES['getMemberBenefit'][0]) {
		$request = $this->getMemberBenefitRequest($contentType);
		$options = ApiHelper::createHttpClientOption($this->config);
		
		// Send request with retry support for timeout errors
		$response = ApiHelper::sendRequestWithRetries($this->client, $this->config, $request, $options);

		$statusCode = $response->getStatusCode();

		switch($statusCode) {
			case 200:
				return ApiHelper::handleResponseWithDataType(
					'\BhrSdk\Model\MemberBenefitEvent[]',
					$request,
					$response,
				);
		}

		if ($statusCode < 200 || $statusCode > 299) {
			throw new ApiException(
				sprintf(
					'[%d] Error connecting to the API (%s)',
					$statusCode,
					(string) $request->getUri()
				),
				$statusCode,
				$response->getHeaders(),
				(string) $response->getBody()
			);
		}

		return ApiHelper::handleResponseWithDataType(
			'\BhrSdk\Model\MemberBenefitEvent[]',
			$request,
			$response,
		);
	}

	/**
	 * Operation getMemberBenefitAsync
	 *
	 * Get a list of member benefit events
	 *
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['getMemberBenefit'] to see the possible values for this operation
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Promise\PromiseInterface
	 */
	public function getMemberBenefitAsync(string $contentType = self::CONTENT_TYPES['getMemberBenefit'][0]) {
		return $this->getMemberBenefitAsyncWithHttpInfo($contentType)
			->then(
				function ($response) {
					return $response[0];
				}
			);
	}

	/**
	 * Operation getMemberBenefitAsyncWithHttpInfo
	 *
	 * Get a list of member benefit events
	 *
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['getMemberBenefit'] to see the possible values for this operation
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Promise\PromiseInterface
	 */
	public function getMemberBenefitAsyncWithHttpInfo(string $contentType = self::CONTENT_TYPES['getMemberBenefit'][0]) {
		$returnType = '\BhrSdk\Model\MemberBenefitEvent[]';
		$request = $this->getMemberBenefitRequest($contentType);

		return ApiHelper::sendRequestWithRetriesAsync($this->client, $this->config, $request, ApiHelper::createHttpClientOption($this->config))
			->then(
				function ($response) use ($returnType) {
					$content = (string) $response->getBody();
					if ($returnType !== 'string') {
						$content = json_decode($content);
					}

					return [
						ObjectSerializer::deserialize($content, $returnType, []),
						$response->getStatusCode(),
						$response->getHeaders()
					];
				},
				function ($exception) {
					$response = $exception->getResponse();
					$statusCode = $response->getStatusCode();
					throw new ApiException(
						sprintf(
							'[%d] Error connecting to the API (%s)',
							$statusCode,
							$exception->getRequest()->getUri()
						),
						$statusCode,
						$response->getHeaders(),
						(string) $response->getBody()
					);
				}
			);
	}

	/**
	 * Create request for operation 'getMemberBenefit'
	 *
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['getMemberBenefit'] to see the possible values for this operation
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Psr7\Request
	 */
	public function getMemberBenefitRequest(string $contentType = self::CONTENT_TYPES['getMemberBenefit'][0]) {

		$resourcePath = '/api/v1/benefit/member_benefit';
		
		$queryParams = [];
		$headerParams = [];
		$httpBody = '';
		$multipart = false;

		$headers = $this->headerSelector->selectHeaders(
			['application/json', ],
			$contentType,
			$multipart
		);

		// Authentication methods
		
		// Basic authentication
		if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
			$headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
		}
		
		// OAuth/Bearer authentication
		if (!empty($this->config->getAccessToken())) {
			$headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
		}

		$defaultHeaders = [];
		if ($this->config->getUserAgent()) {
			$defaultHeaders['User-Agent'] = $this->config->getUserAgent();
		}

		$headers = array_merge(
			$defaultHeaders,
			$headerParams,
			$headers
		);
		
		// Special handling for accept_header_parameter to set the Accept header directly
		if (isset($accept_header_parameter) && $accept_header_parameter !== null) {
			$headers['Accept'] = ObjectSerializer::toHeaderValue($accept_header_parameter);
		}

		$operationHost = $this->config->getHost();
		$query = ObjectSerializer::buildQuery($queryParams);
		return new Request(
			'GET',
			$operationHost . $resourcePath . ($query ? "?{$query}" : ''),
			$headers,
			$httpBody
		);
	}

	/**
	 * Operation updateEmployeeDependent
	 *
	 * Update an employee dependent
	 *
	 * @param  string $id {id} is the employee dependent ID. (required)
	 * @param  \BhrSdk\Model\EmployeeDependent $employee_dependent employee_dependent (required)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['updateEmployeeDependent'] to see the possible values for this operation
	 *
	 * @throws \BhrSdk\ApiException on non-2xx response or if the response body is not in the expected format
	 * @throws \InvalidArgumentException
	 * @return void
	 */
	public function updateEmployeeDependent($id, $employee_dependent, string $contentType = self::CONTENT_TYPES['updateEmployeeDependent'][0]) {
		$this->updateEmployeeDependentWithHttpInfo($id, $employee_dependent, $contentType);
	}

	/**
	 * Operation updateEmployeeDependentWithHttpInfo
	 *
	 * Update an employee dependent
	 *
	 * @param  string $id {id} is the employee dependent ID. (required)
	 * @param  \BhrSdk\Model\EmployeeDependent $employee_dependent (required)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['updateEmployeeDependent'] to see the possible values for this operation
	 *
	 * @throws \BhrSdk\ApiException on non-2xx response or if the response body is not in the expected format
	 * @throws \InvalidArgumentException
	 * @return array of null, HTTP status code, HTTP response headers (array of strings)
	 */
	public function updateEmployeeDependentWithHttpInfo($id, $employee_dependent, string $contentType = self::CONTENT_TYPES['updateEmployeeDependent'][0]) {
		$request = $this->updateEmployeeDependentRequest($id, $employee_dependent, $contentType);
		$options = ApiHelper::createHttpClientOption($this->config);
		
		// Send request with retry support for timeout errors
		$response = ApiHelper::sendRequestWithRetries($this->client, $this->config, $request, $options);

		$statusCode = $response->getStatusCode();

		return ApiHelper::handleResponseWithDataType(
			'object', // or 'mixed' or any other generic type
			$request,
			$response,
		);
	}

	/**
	 * Operation updateEmployeeDependentAsync
	 *
	 * Update an employee dependent
	 *
	 * @param  string $id {id} is the employee dependent ID. (required)
	 * @param  \BhrSdk\Model\EmployeeDependent $employee_dependent (required)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['updateEmployeeDependent'] to see the possible values for this operation
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Promise\PromiseInterface
	 */
	public function updateEmployeeDependentAsync($id, $employee_dependent, string $contentType = self::CONTENT_TYPES['updateEmployeeDependent'][0]) {
		return $this->updateEmployeeDependentAsyncWithHttpInfo($id, $employee_dependent, $contentType)
			->then(
				function ($response) {
					return $response[0];
				}
			);
	}

	/**
	 * Operation updateEmployeeDependentAsyncWithHttpInfo
	 *
	 * Update an employee dependent
	 *
	 * @param  string $id {id} is the employee dependent ID. (required)
	 * @param  \BhrSdk\Model\EmployeeDependent $employee_dependent (required)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['updateEmployeeDependent'] to see the possible values for this operation
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Promise\PromiseInterface
	 */
	public function updateEmployeeDependentAsyncWithHttpInfo($id, $employee_dependent, string $contentType = self::CONTENT_TYPES['updateEmployeeDependent'][0]) {
		
		$request = $this->updateEmployeeDependentRequest($id, $employee_dependent, $contentType);

		return ApiHelper::sendRequestWithRetriesAsync($this->client, $this->config, $request, ApiHelper::createHttpClientOption($this->config))
			->then(
				function ($response) {
					$content = (string) $response->getBody();
					$content = json_decode($content);

					return [
						ObjectSerializer::deserialize($content, 'object', []),
						$response->getStatusCode(),
						$response->getHeaders()
					];
				},
				function ($exception) {
					$response = $exception->getResponse();
					$statusCode = $response->getStatusCode();
					throw new ApiException(
						sprintf(
							'[%d] Error connecting to the API (%s)',
							$statusCode,
							$exception->getRequest()->getUri()
						),
						$statusCode,
						$response->getHeaders(),
						(string) $response->getBody()
					);
				}
			);
	}

	/**
	 * Create request for operation 'updateEmployeeDependent'
	 *
	 * @param  string $id {id} is the employee dependent ID. (required)
	 * @param  \BhrSdk\Model\EmployeeDependent $employee_dependent (required)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['updateEmployeeDependent'] to see the possible values for this operation
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Psr7\Request
	 */
	public function updateEmployeeDependentRequest($id, $employee_dependent, string $contentType = self::CONTENT_TYPES['updateEmployeeDependent'][0]) {
		// PHP 8.0+ only
		ApiHelper::validateRequiredParameters(
			params: [
				'id' => $id,
				'employee_dependent' => $employee_dependent,
			],
			methodName: 'updateEmployeeDependent'
		);

		$resourcePath = '/api/v1/employeedependents/{id}';
		
		$queryParams = [];
		$headerParams = [];
		$httpBody = '';
		$multipart = false;

		// path params
		if ($id !== null) {
			$resourcePath = str_replace(
				'{' . 'id' . '}',
				ObjectSerializer::toPathValue($id),
				$resourcePath
			);
		}

		$headers = $this->headerSelector->selectHeaders(
			['application/json', ],
			$contentType,
			$multipart
		);

		// for model (json/xml)
		if (isset($employee_dependent)) {
			if (stripos($headers['Content-Type'], 'application/json') !== false) {
				# if Content-Type contains "application/json", json_encode the body
				$httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($employee_dependent));
			} else {
				$httpBody = $employee_dependent;
			}
		} 

		// Authentication methods
		
		// Basic authentication
		if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
			$headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
		}
		
		// OAuth/Bearer authentication
		if (!empty($this->config->getAccessToken())) {
			$headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
		}

		$defaultHeaders = [];
		if ($this->config->getUserAgent()) {
			$defaultHeaders['User-Agent'] = $this->config->getUserAgent();
		}

		$headers = array_merge(
			$defaultHeaders,
			$headerParams,
			$headers
		);
		
		// Special handling for accept_header_parameter to set the Accept header directly
		if (isset($accept_header_parameter) && $accept_header_parameter !== null) {
			$headers['Accept'] = ObjectSerializer::toHeaderValue($accept_header_parameter);
		}

		$operationHost = $this->config->getHost();
		$query = ObjectSerializer::buildQuery($queryParams);
		return new Request(
			'PUT',
			$operationHost . $resourcePath . ($query ? "?{$query}" : ''),
			$headers,
			$httpBody
		);
	}

}
