<?php
declare(strict_types=1);
/**
 * HolidaysApi
 * PHP version 8.1
 *
 * @category Class
 * @package  BhrSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BambooHR API
 *
 * BambooHR API documentation. https://documentation.bamboohr.com/
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace BhrSdk\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use BhrSdk\ApiException;
use BhrSdk\Configuration;
use BhrSdk\FormDataProcessor;
use BhrSdk\HeaderSelector;
use BhrSdk\ObjectSerializer;
use BhrSdk\Client\Logger\LoggerInterface;
use BhrSdk\ApiHelper;

/**
 * HolidaysApi Class Doc Comment
 *
 * @category Class
 * @package  BhrSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class HolidaysApi {
	/**
	 * @var ClientInterface
	 */
	protected $client;

	/**
	 * @var Configuration
	 */
	protected $config;

	/**
	 * @var HeaderSelector
	 */
	protected $headerSelector;

	/**
	 * @var int Host index
	 */
	protected $hostIndex;

	/**
	 * @var LoggerInterface|null Logger instance
	 */
	protected $logger;

	/** @var string[] $CONTENT_TYPES **/
	public const CONTENT_TYPES = [
		'bulkInsertCompanyHolidays' => [
			'application/json',
        ],
		'createCompanyHoliday' => [
			'application/json',
        ],
		'deleteCompanyHoliday' => [
			'application/json',
        ],
		'getCatalogHoliday' => [
			'application/json',
        ],
		'getCompanyHoliday' => [
			'application/json',
        ],
		'listCatalogHolidays' => [
			'application/json',
        ],
		'listCompanyHolidays' => [
			'application/json',
        ],
		'updateCompanyHoliday' => [
			'application/merge-patch+json',
        ],
	];

	/**
	 * @param ClientInterface $client
	 * @param Configuration   $config
	 * @param HeaderSelector  $selector
	 * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
	 * @param LoggerInterface|null $logger (Optional) logger instance for secure logging
	 */
	public function __construct(
		?ClientInterface $client = null,
		?Configuration $config = null,
		?HeaderSelector $selector = null,
		int $hostIndex = 0,
		?LoggerInterface $logger = null
	) {
		$this->client = $client ?: new Client();
		$this->config = $config ?: Configuration::getDefaultConfiguration();
		$this->headerSelector = $selector ?: new HeaderSelector();
		$this->hostIndex = $hostIndex;
		$this->logger = $logger;
	}

	/**
	 * Set the host index
	 *
	 * @param int $hostIndex Host index (required)
	 */
	public function setHostIndex($hostIndex): void {
		$this->hostIndex = $hostIndex;
	}

	/**
	 * Get the host index
	 *
	 * @return int Host index
	 */
	public function getHostIndex() {
		return $this->hostIndex;
	}

	/**
	 * @return Configuration
	 */
	public function getConfig() {
		return $this->config;
	}

	/**
	 * Operation bulkInsertCompanyHolidays
	 *
	 * Bulk Create Company Holidays
	 *
	 * @param  \BhrSdk\Model\HolidayCreateCompanyHolidayRequestV1[] $holiday_create_company_holiday_request_v1 holiday_create_company_holiday_request_v1 (required)
	 * @param  bool|null $atomic When true, the entire batch is committed in a single transaction and any per-record failure aborts the whole request with a 422 (no records are created). When false, each record commits independently and failures are reported per record in a 207 response. Accepted values: true/false, 1/0, yes/no, on/off. (optional, default to false)
	 * @param  bool|null $return_records When true, each entry in the response records array also includes the full created company holiday under the record key. Accepted values: true/false, 1/0, yes/no, on/off. (optional, default to false)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['bulkInsertCompanyHolidays'] to see the possible values for this operation
	 *
	 * @throws \BhrSdk\ApiException on non-2xx response or if the response body is not in the expected format
	 * @throws \InvalidArgumentException
	 * @return \BhrSdk\Model\HolidayBulkInsertCompanyHolidaysResponseV1|\BhrSdk\Model\HolidayBulkInsertCompanyHolidaysResponseV1|\BhrSdk\Model\ProblemDetailsResponse|\BhrSdk\Model\ProblemDetailsResponse|\BhrSdk\Model\ProblemDetailsResponse|\BhrSdk\Model\HolidayBulkInsertCompanyHolidaysFailureResponseV1
	 */
	public function bulkInsertCompanyHolidays($holiday_create_company_holiday_request_v1, $atomic = false, $return_records = false, string $contentType = self::CONTENT_TYPES['bulkInsertCompanyHolidays'][0]) {
		list($response) = $this->bulkInsertCompanyHolidaysWithHttpInfo($holiday_create_company_holiday_request_v1, $atomic, $return_records, $contentType);
		return $response;
	}

	/**
	 * Operation bulkInsertCompanyHolidaysWithHttpInfo
	 *
	 * Bulk Create Company Holidays
	 *
	 * @param  \BhrSdk\Model\HolidayCreateCompanyHolidayRequestV1[] $holiday_create_company_holiday_request_v1 (required)
	 * @param  bool|null $atomic When true, the entire batch is committed in a single transaction and any per-record failure aborts the whole request with a 422 (no records are created). When false, each record commits independently and failures are reported per record in a 207 response. Accepted values: true/false, 1/0, yes/no, on/off. (optional, default to false)
	 * @param  bool|null $return_records When true, each entry in the response records array also includes the full created company holiday under the record key. Accepted values: true/false, 1/0, yes/no, on/off. (optional, default to false)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['bulkInsertCompanyHolidays'] to see the possible values for this operation
	 *
	 * @throws \BhrSdk\ApiException on non-2xx response or if the response body is not in the expected format
	 * @throws \InvalidArgumentException
	 * @return array of \BhrSdk\Model\HolidayBulkInsertCompanyHolidaysResponseV1|\BhrSdk\Model\HolidayBulkInsertCompanyHolidaysResponseV1|\BhrSdk\Model\ProblemDetailsResponse|\BhrSdk\Model\ProblemDetailsResponse|\BhrSdk\Model\ProblemDetailsResponse|\BhrSdk\Model\HolidayBulkInsertCompanyHolidaysFailureResponseV1, HTTP status code, HTTP response headers (array of strings)
	 */
	public function bulkInsertCompanyHolidaysWithHttpInfo($holiday_create_company_holiday_request_v1, $atomic = false, $return_records = false, string $contentType = self::CONTENT_TYPES['bulkInsertCompanyHolidays'][0]) {
		$request = $this->bulkInsertCompanyHolidaysRequest($holiday_create_company_holiday_request_v1, $atomic, $return_records, $contentType);
		$options = ApiHelper::createHttpClientOption($this->config);
		
		// Send request with retry support for timeout errors
		$response = ApiHelper::sendRequestWithRetries($this->logger, $this->client, $this->config, $request, $options);

		$statusCode = $response->getStatusCode();

		switch($statusCode) {
			case 200:
				return ApiHelper::handleResponseWithDataType(
					'\BhrSdk\Model\HolidayBulkInsertCompanyHolidaysResponseV1',
					$request,
					$response,
				);
			case 207:
				return ApiHelper::handleResponseWithDataType(
					'\BhrSdk\Model\HolidayBulkInsertCompanyHolidaysResponseV1',
					$request,
					$response,
				);
			case 400:
				return ApiHelper::handleResponseWithDataType(
					'\BhrSdk\Model\ProblemDetailsResponse',
					$request,
					$response,
				);
			case 401:
				return ApiHelper::handleResponseWithDataType(
					'\BhrSdk\Model\ProblemDetailsResponse',
					$request,
					$response,
				);
			case 403:
				return ApiHelper::handleResponseWithDataType(
					'\BhrSdk\Model\ProblemDetailsResponse',
					$request,
					$response,
				);
			case 422:
				return ApiHelper::handleResponseWithDataType(
					'\BhrSdk\Model\HolidayBulkInsertCompanyHolidaysFailureResponseV1',
					$request,
					$response,
				);
		}

		if ($statusCode < 200 || $statusCode > 299) {
			throw new ApiException(
				sprintf(
					'[%d] Error connecting to the API (%s)',
					$statusCode,
					(string) $request->getUri()
				),
				$statusCode,
				$response->getHeaders(),
				(string) $response->getBody()
			);
		}

		return ApiHelper::handleResponseWithDataType(
			'\BhrSdk\Model\HolidayBulkInsertCompanyHolidaysResponseV1',
			$request,
			$response,
		);
	}

	/**
	 * Operation bulkInsertCompanyHolidaysAsync
	 *
	 * Bulk Create Company Holidays
	 *
	 * @param  \BhrSdk\Model\HolidayCreateCompanyHolidayRequestV1[] $holiday_create_company_holiday_request_v1 (required)
	 * @param  bool|null $atomic When true, the entire batch is committed in a single transaction and any per-record failure aborts the whole request with a 422 (no records are created). When false, each record commits independently and failures are reported per record in a 207 response. Accepted values: true/false, 1/0, yes/no, on/off. (optional, default to false)
	 * @param  bool|null $return_records When true, each entry in the response records array also includes the full created company holiday under the record key. Accepted values: true/false, 1/0, yes/no, on/off. (optional, default to false)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['bulkInsertCompanyHolidays'] to see the possible values for this operation
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Promise\PromiseInterface
	 */
	public function bulkInsertCompanyHolidaysAsync($holiday_create_company_holiday_request_v1, $atomic = false, $return_records = false, string $contentType = self::CONTENT_TYPES['bulkInsertCompanyHolidays'][0]) {
		return $this->bulkInsertCompanyHolidaysAsyncWithHttpInfo($holiday_create_company_holiday_request_v1, $atomic, $return_records, $contentType)
			->then(
				function ($response) {
					return $response[0];
				}
			);
	}

	/**
	 * Operation bulkInsertCompanyHolidaysAsyncWithHttpInfo
	 *
	 * Bulk Create Company Holidays
	 *
	 * @param  \BhrSdk\Model\HolidayCreateCompanyHolidayRequestV1[] $holiday_create_company_holiday_request_v1 (required)
	 * @param  bool|null $atomic When true, the entire batch is committed in a single transaction and any per-record failure aborts the whole request with a 422 (no records are created). When false, each record commits independently and failures are reported per record in a 207 response. Accepted values: true/false, 1/0, yes/no, on/off. (optional, default to false)
	 * @param  bool|null $return_records When true, each entry in the response records array also includes the full created company holiday under the record key. Accepted values: true/false, 1/0, yes/no, on/off. (optional, default to false)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['bulkInsertCompanyHolidays'] to see the possible values for this operation
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Promise\PromiseInterface
	 */
	public function bulkInsertCompanyHolidaysAsyncWithHttpInfo($holiday_create_company_holiday_request_v1, $atomic = false, $return_records = false, string $contentType = self::CONTENT_TYPES['bulkInsertCompanyHolidays'][0]) {
		$returnType = '\BhrSdk\Model\HolidayBulkInsertCompanyHolidaysResponseV1';
		$request = $this->bulkInsertCompanyHolidaysRequest($holiday_create_company_holiday_request_v1, $atomic, $return_records, $contentType);

		return ApiHelper::sendRequestWithRetriesAsync($this->logger, $this->client, $this->config, $request, ApiHelper::createHttpClientOption($this->config))
			->then(
				function ($response) use ($returnType) {
					$content = (string) $response->getBody();
					if ($returnType !== 'string') {
						$content = json_decode($content);
					}

					return [
						ObjectSerializer::deserialize($content, $returnType, []),
						$response->getStatusCode(),
						$response->getHeaders()
					];
				},
				function ($exception) {
					$response = $exception->getResponse();
					$statusCode = $response->getStatusCode();
					throw new ApiException(
						sprintf(
							'[%d] Error connecting to the API (%s)',
							$statusCode,
							$exception->getRequest()->getUri()
						),
						$statusCode,
						$response->getHeaders(),
						(string) $response->getBody()
					);
				}
			);
	}

	/**
	 * Create request for operation 'bulkInsertCompanyHolidays'
	 *
	 * @param  \BhrSdk\Model\HolidayCreateCompanyHolidayRequestV1[] $holiday_create_company_holiday_request_v1 (required)
	 * @param  bool|null $atomic When true, the entire batch is committed in a single transaction and any per-record failure aborts the whole request with a 422 (no records are created). When false, each record commits independently and failures are reported per record in a 207 response. Accepted values: true/false, 1/0, yes/no, on/off. (optional, default to false)
	 * @param  bool|null $return_records When true, each entry in the response records array also includes the full created company holiday under the record key. Accepted values: true/false, 1/0, yes/no, on/off. (optional, default to false)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['bulkInsertCompanyHolidays'] to see the possible values for this operation
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Psr7\Request
	 */
	public function bulkInsertCompanyHolidaysRequest($holiday_create_company_holiday_request_v1, $atomic = false, $return_records = false, string $contentType = self::CONTENT_TYPES['bulkInsertCompanyHolidays'][0]) {
		// PHP 8.0+ only
		ApiHelper::validateRequiredParameters(
			params: [
				'holiday_create_company_holiday_request_v1' => $holiday_create_company_holiday_request_v1,
			],
			methodName: 'bulkInsertCompanyHolidays'
		);

		if (count($holiday_create_company_holiday_request_v1) > 100) {
			throw new \InvalidArgumentException('invalid value for "$holiday_create_company_holiday_request_v1" when calling HolidaysApi.bulkInsertCompanyHolidays, number of items must be less than or equal to 100.');
		}
		if (count($holiday_create_company_holiday_request_v1) < 1) {
			throw new \InvalidArgumentException('invalid value for "$holiday_create_company_holiday_request_v1" when calling HolidaysApi.bulkInsertCompanyHolidays, number of items must be greater than or equal to 1.');
		}
		
		$resourcePath = '/api/v1/holidays/bulk-insert';
		$this->logger?->info('Request method: [POST], URL: ' . $resourcePath);
		
		$queryParams = [];
		$headerParams = [];
		$httpBody = '';
		$multipart = false;

		$parameters = [
			'atomic' => ['value' => $atomic, 'type' => 'boolean', 'required' => false, 'style' => 'form', 'explode' => true],
			'returnRecords' => ['value' => $return_records, 'type' => 'boolean', 'required' => false, 'style' => 'form', 'explode' => true],
		];

		// Process parameters and build query values directly
		$queryParams = [];

		foreach ($parameters as $paramName => $config) {
			$value = ObjectSerializer::toQueryValue($config['value'], $paramName, $config['type'], $config['style'], $config['explode'], $config['required']);
			
			if ($value !== null) {
				// Merge each parameter value directly into queryParams
				$queryParams = array_merge($queryParams, $value);
			}
		}

		$headers = $this->headerSelector->selectHeaders(
			['application/json', ],
			$contentType,
			$multipart
		);

		// for model (json/xml)
		if (isset($holiday_create_company_holiday_request_v1)) {
			if (stripos($headers['Content-Type'], 'application/json') !== false) {
				# if Content-Type contains "application/json", json_encode the body
				$httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($holiday_create_company_holiday_request_v1));
			} else {
				$httpBody = is_array($holiday_create_company_holiday_request_v1) ? json_encode($holiday_create_company_holiday_request_v1) : $holiday_create_company_holiday_request_v1;
			}
		} 

		// Authentication methods
		
		// Basic authentication
		if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
			$this->logger?->info('Using Basic authentication');	
			$headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
		}
		
		// OAuth/Bearer authentication
		if (!empty($this->config->getAccessToken())) {
			$this->logger?->info('Using Bearer authentication');
			$headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
		}

		$defaultHeaders = [];
		if ($this->config->getUserAgent()) {
			$this->logger?->debug('Using User-Agent: ' . $this->config->getUserAgent());	
			$defaultHeaders['User-Agent'] = $this->config->getUserAgent();
		}

		$headers = array_merge(
			$defaultHeaders,
			$headerParams,
			$headers
		);
		
		// Special handling for accept_header_parameter to set the Accept header directly
		/** @phpstan-ignore-next-line */
		if (isset($accept_header_parameter) && $accept_header_parameter !== null) {
			$this->logger?->debug('Overriding Accept header: ' . $accept_header_parameter);
			/** @phpstan-ignore-next-line */
			$headers['Accept'] = ObjectSerializer::toHeaderValue($accept_header_parameter);
		}

		$operationHost = $this->config->getHost();
		$query = ObjectSerializer::buildQuery($queryParams);
		return new Request(
			'POST',
			$operationHost . $resourcePath . ($query ? "?{$query}" : ''),
			$headers,
			is_string($httpBody) ? $httpBody : (string)$httpBody
		);
	}

	/**
	 * Operation createCompanyHoliday
	 *
	 * Create Company Holiday
	 *
	 * @param  \BhrSdk\Model\HolidayCreateCompanyHolidayRequestV1 $holiday_create_company_holiday_request_v1 holiday_create_company_holiday_request_v1 (required)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['createCompanyHoliday'] to see the possible values for this operation
	 *
	 * @throws \BhrSdk\ApiException on non-2xx response or if the response body is not in the expected format
	 * @throws \InvalidArgumentException
	 * @return \BhrSdk\Model\HolidayCompanyHolidayV1|\BhrSdk\Model\ProblemDetailsResponse|\BhrSdk\Model\ProblemDetailsResponse|\BhrSdk\Model\ProblemDetailsResponse|\BhrSdk\Model\ProblemDetailsResponse|\BhrSdk\Model\ProblemDetailsResponse|\BhrSdk\Model\ProblemDetailsResponse
	 */
	public function createCompanyHoliday($holiday_create_company_holiday_request_v1, string $contentType = self::CONTENT_TYPES['createCompanyHoliday'][0]) {
		list($response) = $this->createCompanyHolidayWithHttpInfo($holiday_create_company_holiday_request_v1, $contentType);
		return $response;
	}

	/**
	 * Operation createCompanyHolidayWithHttpInfo
	 *
	 * Create Company Holiday
	 *
	 * @param  \BhrSdk\Model\HolidayCreateCompanyHolidayRequestV1 $holiday_create_company_holiday_request_v1 (required)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['createCompanyHoliday'] to see the possible values for this operation
	 *
	 * @throws \BhrSdk\ApiException on non-2xx response or if the response body is not in the expected format
	 * @throws \InvalidArgumentException
	 * @return array of \BhrSdk\Model\HolidayCompanyHolidayV1|\BhrSdk\Model\ProblemDetailsResponse|\BhrSdk\Model\ProblemDetailsResponse|\BhrSdk\Model\ProblemDetailsResponse|\BhrSdk\Model\ProblemDetailsResponse|\BhrSdk\Model\ProblemDetailsResponse|\BhrSdk\Model\ProblemDetailsResponse, HTTP status code, HTTP response headers (array of strings)
	 */
	public function createCompanyHolidayWithHttpInfo($holiday_create_company_holiday_request_v1, string $contentType = self::CONTENT_TYPES['createCompanyHoliday'][0]) {
		$request = $this->createCompanyHolidayRequest($holiday_create_company_holiday_request_v1, $contentType);
		$options = ApiHelper::createHttpClientOption($this->config);
		
		// Send request with retry support for timeout errors
		$response = ApiHelper::sendRequestWithRetries($this->logger, $this->client, $this->config, $request, $options);

		$statusCode = $response->getStatusCode();

		switch($statusCode) {
			case 201:
				return ApiHelper::handleResponseWithDataType(
					'\BhrSdk\Model\HolidayCompanyHolidayV1',
					$request,
					$response,
				);
			case 400:
				return ApiHelper::handleResponseWithDataType(
					'\BhrSdk\Model\ProblemDetailsResponse',
					$request,
					$response,
				);
			case 401:
				return ApiHelper::handleResponseWithDataType(
					'\BhrSdk\Model\ProblemDetailsResponse',
					$request,
					$response,
				);
			case 403:
				return ApiHelper::handleResponseWithDataType(
					'\BhrSdk\Model\ProblemDetailsResponse',
					$request,
					$response,
				);
			case 404:
				return ApiHelper::handleResponseWithDataType(
					'\BhrSdk\Model\ProblemDetailsResponse',
					$request,
					$response,
				);
			case 409:
				return ApiHelper::handleResponseWithDataType(
					'\BhrSdk\Model\ProblemDetailsResponse',
					$request,
					$response,
				);
			case 422:
				return ApiHelper::handleResponseWithDataType(
					'\BhrSdk\Model\ProblemDetailsResponse',
					$request,
					$response,
				);
		}

		if ($statusCode < 200 || $statusCode > 299) {
			throw new ApiException(
				sprintf(
					'[%d] Error connecting to the API (%s)',
					$statusCode,
					(string) $request->getUri()
				),
				$statusCode,
				$response->getHeaders(),
				(string) $response->getBody()
			);
		}

		return ApiHelper::handleResponseWithDataType(
			'\BhrSdk\Model\HolidayCompanyHolidayV1',
			$request,
			$response,
		);
	}

	/**
	 * Operation createCompanyHolidayAsync
	 *
	 * Create Company Holiday
	 *
	 * @param  \BhrSdk\Model\HolidayCreateCompanyHolidayRequestV1 $holiday_create_company_holiday_request_v1 (required)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['createCompanyHoliday'] to see the possible values for this operation
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Promise\PromiseInterface
	 */
	public function createCompanyHolidayAsync($holiday_create_company_holiday_request_v1, string $contentType = self::CONTENT_TYPES['createCompanyHoliday'][0]) {
		return $this->createCompanyHolidayAsyncWithHttpInfo($holiday_create_company_holiday_request_v1, $contentType)
			->then(
				function ($response) {
					return $response[0];
				}
			);
	}

	/**
	 * Operation createCompanyHolidayAsyncWithHttpInfo
	 *
	 * Create Company Holiday
	 *
	 * @param  \BhrSdk\Model\HolidayCreateCompanyHolidayRequestV1 $holiday_create_company_holiday_request_v1 (required)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['createCompanyHoliday'] to see the possible values for this operation
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Promise\PromiseInterface
	 */
	public function createCompanyHolidayAsyncWithHttpInfo($holiday_create_company_holiday_request_v1, string $contentType = self::CONTENT_TYPES['createCompanyHoliday'][0]) {
		$returnType = '\BhrSdk\Model\HolidayCompanyHolidayV1';
		$request = $this->createCompanyHolidayRequest($holiday_create_company_holiday_request_v1, $contentType);

		return ApiHelper::sendRequestWithRetriesAsync($this->logger, $this->client, $this->config, $request, ApiHelper::createHttpClientOption($this->config))
			->then(
				function ($response) use ($returnType) {
					$content = (string) $response->getBody();
					if ($returnType !== 'string') {
						$content = json_decode($content);
					}

					return [
						ObjectSerializer::deserialize($content, $returnType, []),
						$response->getStatusCode(),
						$response->getHeaders()
					];
				},
				function ($exception) {
					$response = $exception->getResponse();
					$statusCode = $response->getStatusCode();
					throw new ApiException(
						sprintf(
							'[%d] Error connecting to the API (%s)',
							$statusCode,
							$exception->getRequest()->getUri()
						),
						$statusCode,
						$response->getHeaders(),
						(string) $response->getBody()
					);
				}
			);
	}

	/**
	 * Create request for operation 'createCompanyHoliday'
	 *
	 * @param  \BhrSdk\Model\HolidayCreateCompanyHolidayRequestV1 $holiday_create_company_holiday_request_v1 (required)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['createCompanyHoliday'] to see the possible values for this operation
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Psr7\Request
	 */
	public function createCompanyHolidayRequest($holiday_create_company_holiday_request_v1, string $contentType = self::CONTENT_TYPES['createCompanyHoliday'][0]) {
		// PHP 8.0+ only
		ApiHelper::validateRequiredParameters(
			params: [
				'holiday_create_company_holiday_request_v1' => $holiday_create_company_holiday_request_v1,
			],
			methodName: 'createCompanyHoliday'
		);

		$resourcePath = '/api/v1/holidays';
		$this->logger?->info('Request method: [POST], URL: ' . $resourcePath);
		
		$queryParams = [];
		$headerParams = [];
		$httpBody = '';
		$multipart = false;

		$headers = $this->headerSelector->selectHeaders(
			['application/json', ],
			$contentType,
			$multipart
		);

		// for model (json/xml)
		if (isset($holiday_create_company_holiday_request_v1)) {
			if (stripos($headers['Content-Type'], 'application/json') !== false) {
				# if Content-Type contains "application/json", json_encode the body
				$httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($holiday_create_company_holiday_request_v1));
			} else {
				$httpBody = is_array($holiday_create_company_holiday_request_v1) ? json_encode($holiday_create_company_holiday_request_v1) : $holiday_create_company_holiday_request_v1;
			}
		} 

		// Authentication methods
		
		// Basic authentication
		if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
			$this->logger?->info('Using Basic authentication');	
			$headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
		}
		
		// OAuth/Bearer authentication
		if (!empty($this->config->getAccessToken())) {
			$this->logger?->info('Using Bearer authentication');
			$headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
		}

		$defaultHeaders = [];
		if ($this->config->getUserAgent()) {
			$this->logger?->debug('Using User-Agent: ' . $this->config->getUserAgent());	
			$defaultHeaders['User-Agent'] = $this->config->getUserAgent();
		}

		$headers = array_merge(
			$defaultHeaders,
			$headerParams,
			$headers
		);
		
		// Special handling for accept_header_parameter to set the Accept header directly
		/** @phpstan-ignore-next-line */
		if (isset($accept_header_parameter) && $accept_header_parameter !== null) {
			$this->logger?->debug('Overriding Accept header: ' . $accept_header_parameter);
			/** @phpstan-ignore-next-line */
			$headers['Accept'] = ObjectSerializer::toHeaderValue($accept_header_parameter);
		}

		$operationHost = $this->config->getHost();
		$query = ObjectSerializer::buildQuery($queryParams);
		return new Request(
			'POST',
			$operationHost . $resourcePath . ($query ? "?{$query}" : ''),
			$headers,
			is_string($httpBody) ? $httpBody : (string)$httpBody
		);
	}

	/**
	 * Operation deleteCompanyHoliday
	 *
	 * Delete Company Holiday
	 *
	 * @param  int $id The company holiday ID. (required)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['deleteCompanyHoliday'] to see the possible values for this operation
	 *
	 * @throws \BhrSdk\ApiException on non-2xx response or if the response body is not in the expected format
	 * @throws \InvalidArgumentException
	 * @return mixed
	 */
	public function deleteCompanyHoliday($id, string $contentType = self::CONTENT_TYPES['deleteCompanyHoliday'][0]) {
		list($response) = $this->deleteCompanyHolidayWithHttpInfo($id, $contentType);
		return $response;
	}

	/**
	 * Operation deleteCompanyHolidayWithHttpInfo
	 *
	 * Delete Company Holiday
	 *
	 * @param  int $id The company holiday ID. (required)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['deleteCompanyHoliday'] to see the possible values for this operation
	 *
	 * @throws \BhrSdk\ApiException on non-2xx response or if the response body is not in the expected format
	 * @throws \InvalidArgumentException
	 * @return array of null, HTTP status code, HTTP response headers (array of strings)
	 */
	public function deleteCompanyHolidayWithHttpInfo($id, string $contentType = self::CONTENT_TYPES['deleteCompanyHoliday'][0]) {
		$request = $this->deleteCompanyHolidayRequest($id, $contentType);
		$options = ApiHelper::createHttpClientOption($this->config);
		
		// Send request with retry support for timeout errors
		$response = ApiHelper::sendRequestWithRetries($this->logger, $this->client, $this->config, $request, $options);

		$statusCode = $response->getStatusCode();

		return ApiHelper::handleResponseWithDataType(
			'object', // or 'mixed' or any other generic type
			$request,
			$response,
		);
	}

	/**
	 * Operation deleteCompanyHolidayAsync
	 *
	 * Delete Company Holiday
	 *
	 * @param  int $id The company holiday ID. (required)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['deleteCompanyHoliday'] to see the possible values for this operation
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Promise\PromiseInterface
	 */
	public function deleteCompanyHolidayAsync($id, string $contentType = self::CONTENT_TYPES['deleteCompanyHoliday'][0]) {
		return $this->deleteCompanyHolidayAsyncWithHttpInfo($id, $contentType)
			->then(
				function ($response) {
					return $response[0];
				}
			);
	}

	/**
	 * Operation deleteCompanyHolidayAsyncWithHttpInfo
	 *
	 * Delete Company Holiday
	 *
	 * @param  int $id The company holiday ID. (required)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['deleteCompanyHoliday'] to see the possible values for this operation
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Promise\PromiseInterface
	 */
	public function deleteCompanyHolidayAsyncWithHttpInfo($id, string $contentType = self::CONTENT_TYPES['deleteCompanyHoliday'][0]) {
		
		$request = $this->deleteCompanyHolidayRequest($id, $contentType);

		return ApiHelper::sendRequestWithRetriesAsync($this->logger, $this->client, $this->config, $request, ApiHelper::createHttpClientOption($this->config))
			->then(
				function ($response) {
					$content = (string) $response->getBody();
					$content = json_decode($content);

					return [
						ObjectSerializer::deserialize($content, 'object', []),
						$response->getStatusCode(),
						$response->getHeaders()
					];
				},
				function ($exception) {
					$response = $exception->getResponse();
					$statusCode = $response->getStatusCode();
					throw new ApiException(
						sprintf(
							'[%d] Error connecting to the API (%s)',
							$statusCode,
							$exception->getRequest()->getUri()
						),
						$statusCode,
						$response->getHeaders(),
						(string) $response->getBody()
					);
				}
			);
	}

	/**
	 * Create request for operation 'deleteCompanyHoliday'
	 *
	 * @param  int $id The company holiday ID. (required)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['deleteCompanyHoliday'] to see the possible values for this operation
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Psr7\Request
	 */
	public function deleteCompanyHolidayRequest($id, string $contentType = self::CONTENT_TYPES['deleteCompanyHoliday'][0]) {
		// PHP 8.0+ only
		ApiHelper::validateRequiredParameters(
			params: [
				'id' => $id,
			],
			methodName: 'deleteCompanyHoliday'
		);

		$resourcePath = '/api/v1/holidays/{id}';
		$this->logger?->info('Request method: [DELETE], URL: ' . $resourcePath);
		
		$queryParams = [];
		$headerParams = [];
		$httpBody = '';
		$multipart = false;

		// path params
		if ($id !== null) {
			$resourcePath = str_replace(
				'{' . 'id' . '}',
				ObjectSerializer::toPathValue((string) $id),
				$resourcePath
			);
		}

		$headers = $this->headerSelector->selectHeaders(
			['application/json', ],
			$contentType,
			$multipart
		);

		// Authentication methods
		
		// Basic authentication
		if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
			$this->logger?->info('Using Basic authentication');	
			$headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
		}
		
		// OAuth/Bearer authentication
		if (!empty($this->config->getAccessToken())) {
			$this->logger?->info('Using Bearer authentication');
			$headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
		}

		$defaultHeaders = [];
		if ($this->config->getUserAgent()) {
			$this->logger?->debug('Using User-Agent: ' . $this->config->getUserAgent());	
			$defaultHeaders['User-Agent'] = $this->config->getUserAgent();
		}

		$headers = array_merge(
			$defaultHeaders,
			$headerParams,
			$headers
		);
		
		// Special handling for accept_header_parameter to set the Accept header directly
		/** @phpstan-ignore-next-line */
		if (isset($accept_header_parameter) && $accept_header_parameter !== null) {
			$this->logger?->debug('Overriding Accept header: ' . $accept_header_parameter);
			/** @phpstan-ignore-next-line */
			$headers['Accept'] = ObjectSerializer::toHeaderValue($accept_header_parameter);
		}

		$operationHost = $this->config->getHost();
		$query = ObjectSerializer::buildQuery($queryParams);
		return new Request(
			'DELETE',
			$operationHost . $resourcePath . ($query ? "?{$query}" : ''),
			$headers,
			is_string($httpBody) ? $httpBody : (string)$httpBody
		);
	}

	/**
	 * Operation getCatalogHoliday
	 *
	 * Get Catalog Holiday
	 *
	 * @param  string $uuid The catalog entry UUID. (required)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['getCatalogHoliday'] to see the possible values for this operation
	 *
	 * @throws \BhrSdk\ApiException on non-2xx response or if the response body is not in the expected format
	 * @throws \InvalidArgumentException
	 * @return \BhrSdk\Model\GlobalHolidayGlobalHolidayV1|\BhrSdk\Model\ProblemDetailsResponse|\BhrSdk\Model\ProblemDetailsResponse|\BhrSdk\Model\ProblemDetailsResponse|\BhrSdk\Model\ProblemDetailsResponse
	 */
	public function getCatalogHoliday($uuid, string $contentType = self::CONTENT_TYPES['getCatalogHoliday'][0]) {
		list($response) = $this->getCatalogHolidayWithHttpInfo($uuid, $contentType);
		return $response;
	}

	/**
	 * Operation getCatalogHolidayWithHttpInfo
	 *
	 * Get Catalog Holiday
	 *
	 * @param  string $uuid The catalog entry UUID. (required)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['getCatalogHoliday'] to see the possible values for this operation
	 *
	 * @throws \BhrSdk\ApiException on non-2xx response or if the response body is not in the expected format
	 * @throws \InvalidArgumentException
	 * @return array of \BhrSdk\Model\GlobalHolidayGlobalHolidayV1|\BhrSdk\Model\ProblemDetailsResponse|\BhrSdk\Model\ProblemDetailsResponse|\BhrSdk\Model\ProblemDetailsResponse|\BhrSdk\Model\ProblemDetailsResponse, HTTP status code, HTTP response headers (array of strings)
	 */
	public function getCatalogHolidayWithHttpInfo($uuid, string $contentType = self::CONTENT_TYPES['getCatalogHoliday'][0]) {
		$request = $this->getCatalogHolidayRequest($uuid, $contentType);
		$options = ApiHelper::createHttpClientOption($this->config);
		
		// Send request with retry support for timeout errors
		$response = ApiHelper::sendRequestWithRetries($this->logger, $this->client, $this->config, $request, $options);

		$statusCode = $response->getStatusCode();

		switch($statusCode) {
			case 200:
				return ApiHelper::handleResponseWithDataType(
					'\BhrSdk\Model\GlobalHolidayGlobalHolidayV1',
					$request,
					$response,
				);
			case 401:
				return ApiHelper::handleResponseWithDataType(
					'\BhrSdk\Model\ProblemDetailsResponse',
					$request,
					$response,
				);
			case 403:
				return ApiHelper::handleResponseWithDataType(
					'\BhrSdk\Model\ProblemDetailsResponse',
					$request,
					$response,
				);
			case 404:
				return ApiHelper::handleResponseWithDataType(
					'\BhrSdk\Model\ProblemDetailsResponse',
					$request,
					$response,
				);
			case 422:
				return ApiHelper::handleResponseWithDataType(
					'\BhrSdk\Model\ProblemDetailsResponse',
					$request,
					$response,
				);
		}

		if ($statusCode < 200 || $statusCode > 299) {
			throw new ApiException(
				sprintf(
					'[%d] Error connecting to the API (%s)',
					$statusCode,
					(string) $request->getUri()
				),
				$statusCode,
				$response->getHeaders(),
				(string) $response->getBody()
			);
		}

		return ApiHelper::handleResponseWithDataType(
			'\BhrSdk\Model\GlobalHolidayGlobalHolidayV1',
			$request,
			$response,
		);
	}

	/**
	 * Operation getCatalogHolidayAsync
	 *
	 * Get Catalog Holiday
	 *
	 * @param  string $uuid The catalog entry UUID. (required)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['getCatalogHoliday'] to see the possible values for this operation
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Promise\PromiseInterface
	 */
	public function getCatalogHolidayAsync($uuid, string $contentType = self::CONTENT_TYPES['getCatalogHoliday'][0]) {
		return $this->getCatalogHolidayAsyncWithHttpInfo($uuid, $contentType)
			->then(
				function ($response) {
					return $response[0];
				}
			);
	}

	/**
	 * Operation getCatalogHolidayAsyncWithHttpInfo
	 *
	 * Get Catalog Holiday
	 *
	 * @param  string $uuid The catalog entry UUID. (required)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['getCatalogHoliday'] to see the possible values for this operation
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Promise\PromiseInterface
	 */
	public function getCatalogHolidayAsyncWithHttpInfo($uuid, string $contentType = self::CONTENT_TYPES['getCatalogHoliday'][0]) {
		$returnType = '\BhrSdk\Model\GlobalHolidayGlobalHolidayV1';
		$request = $this->getCatalogHolidayRequest($uuid, $contentType);

		return ApiHelper::sendRequestWithRetriesAsync($this->logger, $this->client, $this->config, $request, ApiHelper::createHttpClientOption($this->config))
			->then(
				function ($response) use ($returnType) {
					$content = (string) $response->getBody();
					if ($returnType !== 'string') {
						$content = json_decode($content);
					}

					return [
						ObjectSerializer::deserialize($content, $returnType, []),
						$response->getStatusCode(),
						$response->getHeaders()
					];
				},
				function ($exception) {
					$response = $exception->getResponse();
					$statusCode = $response->getStatusCode();
					throw new ApiException(
						sprintf(
							'[%d] Error connecting to the API (%s)',
							$statusCode,
							$exception->getRequest()->getUri()
						),
						$statusCode,
						$response->getHeaders(),
						(string) $response->getBody()
					);
				}
			);
	}

	/**
	 * Create request for operation 'getCatalogHoliday'
	 *
	 * @param  string $uuid The catalog entry UUID. (required)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['getCatalogHoliday'] to see the possible values for this operation
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Psr7\Request
	 */
	public function getCatalogHolidayRequest($uuid, string $contentType = self::CONTENT_TYPES['getCatalogHoliday'][0]) {
		// PHP 8.0+ only
		ApiHelper::validateRequiredParameters(
			params: [
				'uuid' => $uuid,
			],
			methodName: 'getCatalogHoliday'
		);

		$resourcePath = '/api/v1/holidays/catalog/{uuid}';
		$this->logger?->info('Request method: [GET], URL: ' . $resourcePath);
		
		$queryParams = [];
		$headerParams = [];
		$httpBody = '';
		$multipart = false;

		// path params
		if ($uuid !== null) {
			$resourcePath = str_replace(
				'{' . 'uuid' . '}',
				ObjectSerializer::toPathValue((string) $uuid),
				$resourcePath
			);
		}

		$headers = $this->headerSelector->selectHeaders(
			['application/json', ],
			$contentType,
			$multipart
		);

		// Authentication methods
		
		// Basic authentication
		if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
			$this->logger?->info('Using Basic authentication');	
			$headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
		}
		
		// OAuth/Bearer authentication
		if (!empty($this->config->getAccessToken())) {
			$this->logger?->info('Using Bearer authentication');
			$headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
		}

		$defaultHeaders = [];
		if ($this->config->getUserAgent()) {
			$this->logger?->debug('Using User-Agent: ' . $this->config->getUserAgent());	
			$defaultHeaders['User-Agent'] = $this->config->getUserAgent();
		}

		$headers = array_merge(
			$defaultHeaders,
			$headerParams,
			$headers
		);
		
		// Special handling for accept_header_parameter to set the Accept header directly
		/** @phpstan-ignore-next-line */
		if (isset($accept_header_parameter) && $accept_header_parameter !== null) {
			$this->logger?->debug('Overriding Accept header: ' . $accept_header_parameter);
			/** @phpstan-ignore-next-line */
			$headers['Accept'] = ObjectSerializer::toHeaderValue($accept_header_parameter);
		}

		$operationHost = $this->config->getHost();
		$query = ObjectSerializer::buildQuery($queryParams);
		return new Request(
			'GET',
			$operationHost . $resourcePath . ($query ? "?{$query}" : ''),
			$headers,
			is_string($httpBody) ? $httpBody : (string)$httpBody
		);
	}

	/**
	 * Operation getCompanyHoliday
	 *
	 * Get Company Holiday
	 *
	 * @param  int $id The company holiday ID. (required)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['getCompanyHoliday'] to see the possible values for this operation
	 *
	 * @throws \BhrSdk\ApiException on non-2xx response or if the response body is not in the expected format
	 * @throws \InvalidArgumentException
	 * @return \BhrSdk\Model\HolidayCompanyHolidayV1|\BhrSdk\Model\ProblemDetailsResponse|\BhrSdk\Model\ProblemDetailsResponse|\BhrSdk\Model\ProblemDetailsResponse
	 */
	public function getCompanyHoliday($id, string $contentType = self::CONTENT_TYPES['getCompanyHoliday'][0]) {
		list($response) = $this->getCompanyHolidayWithHttpInfo($id, $contentType);
		return $response;
	}

	/**
	 * Operation getCompanyHolidayWithHttpInfo
	 *
	 * Get Company Holiday
	 *
	 * @param  int $id The company holiday ID. (required)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['getCompanyHoliday'] to see the possible values for this operation
	 *
	 * @throws \BhrSdk\ApiException on non-2xx response or if the response body is not in the expected format
	 * @throws \InvalidArgumentException
	 * @return array of \BhrSdk\Model\HolidayCompanyHolidayV1|\BhrSdk\Model\ProblemDetailsResponse|\BhrSdk\Model\ProblemDetailsResponse|\BhrSdk\Model\ProblemDetailsResponse, HTTP status code, HTTP response headers (array of strings)
	 */
	public function getCompanyHolidayWithHttpInfo($id, string $contentType = self::CONTENT_TYPES['getCompanyHoliday'][0]) {
		$request = $this->getCompanyHolidayRequest($id, $contentType);
		$options = ApiHelper::createHttpClientOption($this->config);
		
		// Send request with retry support for timeout errors
		$response = ApiHelper::sendRequestWithRetries($this->logger, $this->client, $this->config, $request, $options);

		$statusCode = $response->getStatusCode();

		switch($statusCode) {
			case 200:
				return ApiHelper::handleResponseWithDataType(
					'\BhrSdk\Model\HolidayCompanyHolidayV1',
					$request,
					$response,
				);
			case 401:
				return ApiHelper::handleResponseWithDataType(
					'\BhrSdk\Model\ProblemDetailsResponse',
					$request,
					$response,
				);
			case 403:
				return ApiHelper::handleResponseWithDataType(
					'\BhrSdk\Model\ProblemDetailsResponse',
					$request,
					$response,
				);
			case 404:
				return ApiHelper::handleResponseWithDataType(
					'\BhrSdk\Model\ProblemDetailsResponse',
					$request,
					$response,
				);
		}

		if ($statusCode < 200 || $statusCode > 299) {
			throw new ApiException(
				sprintf(
					'[%d] Error connecting to the API (%s)',
					$statusCode,
					(string) $request->getUri()
				),
				$statusCode,
				$response->getHeaders(),
				(string) $response->getBody()
			);
		}

		return ApiHelper::handleResponseWithDataType(
			'\BhrSdk\Model\HolidayCompanyHolidayV1',
			$request,
			$response,
		);
	}

	/**
	 * Operation getCompanyHolidayAsync
	 *
	 * Get Company Holiday
	 *
	 * @param  int $id The company holiday ID. (required)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['getCompanyHoliday'] to see the possible values for this operation
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Promise\PromiseInterface
	 */
	public function getCompanyHolidayAsync($id, string $contentType = self::CONTENT_TYPES['getCompanyHoliday'][0]) {
		return $this->getCompanyHolidayAsyncWithHttpInfo($id, $contentType)
			->then(
				function ($response) {
					return $response[0];
				}
			);
	}

	/**
	 * Operation getCompanyHolidayAsyncWithHttpInfo
	 *
	 * Get Company Holiday
	 *
	 * @param  int $id The company holiday ID. (required)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['getCompanyHoliday'] to see the possible values for this operation
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Promise\PromiseInterface
	 */
	public function getCompanyHolidayAsyncWithHttpInfo($id, string $contentType = self::CONTENT_TYPES['getCompanyHoliday'][0]) {
		$returnType = '\BhrSdk\Model\HolidayCompanyHolidayV1';
		$request = $this->getCompanyHolidayRequest($id, $contentType);

		return ApiHelper::sendRequestWithRetriesAsync($this->logger, $this->client, $this->config, $request, ApiHelper::createHttpClientOption($this->config))
			->then(
				function ($response) use ($returnType) {
					$content = (string) $response->getBody();
					if ($returnType !== 'string') {
						$content = json_decode($content);
					}

					return [
						ObjectSerializer::deserialize($content, $returnType, []),
						$response->getStatusCode(),
						$response->getHeaders()
					];
				},
				function ($exception) {
					$response = $exception->getResponse();
					$statusCode = $response->getStatusCode();
					throw new ApiException(
						sprintf(
							'[%d] Error connecting to the API (%s)',
							$statusCode,
							$exception->getRequest()->getUri()
						),
						$statusCode,
						$response->getHeaders(),
						(string) $response->getBody()
					);
				}
			);
	}

	/**
	 * Create request for operation 'getCompanyHoliday'
	 *
	 * @param  int $id The company holiday ID. (required)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['getCompanyHoliday'] to see the possible values for this operation
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Psr7\Request
	 */
	public function getCompanyHolidayRequest($id, string $contentType = self::CONTENT_TYPES['getCompanyHoliday'][0]) {
		// PHP 8.0+ only
		ApiHelper::validateRequiredParameters(
			params: [
				'id' => $id,
			],
			methodName: 'getCompanyHoliday'
		);

		$resourcePath = '/api/v1/holidays/{id}';
		$this->logger?->info('Request method: [GET], URL: ' . $resourcePath);
		
		$queryParams = [];
		$headerParams = [];
		$httpBody = '';
		$multipart = false;

		// path params
		if ($id !== null) {
			$resourcePath = str_replace(
				'{' . 'id' . '}',
				ObjectSerializer::toPathValue((string) $id),
				$resourcePath
			);
		}

		$headers = $this->headerSelector->selectHeaders(
			['application/json', ],
			$contentType,
			$multipart
		);

		// Authentication methods
		
		// Basic authentication
		if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
			$this->logger?->info('Using Basic authentication');	
			$headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
		}
		
		// OAuth/Bearer authentication
		if (!empty($this->config->getAccessToken())) {
			$this->logger?->info('Using Bearer authentication');
			$headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
		}

		$defaultHeaders = [];
		if ($this->config->getUserAgent()) {
			$this->logger?->debug('Using User-Agent: ' . $this->config->getUserAgent());	
			$defaultHeaders['User-Agent'] = $this->config->getUserAgent();
		}

		$headers = array_merge(
			$defaultHeaders,
			$headerParams,
			$headers
		);
		
		// Special handling for accept_header_parameter to set the Accept header directly
		/** @phpstan-ignore-next-line */
		if (isset($accept_header_parameter) && $accept_header_parameter !== null) {
			$this->logger?->debug('Overriding Accept header: ' . $accept_header_parameter);
			/** @phpstan-ignore-next-line */
			$headers['Accept'] = ObjectSerializer::toHeaderValue($accept_header_parameter);
		}

		$operationHost = $this->config->getHost();
		$query = ObjectSerializer::buildQuery($queryParams);
		return new Request(
			'GET',
			$operationHost . $resourcePath . ($query ? "?{$query}" : ''),
			$headers,
			is_string($httpBody) ? $httpBody : (string)$httpBody
		);
	}

	/**
	 * Operation listCatalogHolidays
	 *
	 * List Catalog Holidays
	 *
	 * @param  string|null $country_code ISO 3166-1 alpha-2 country code. Filters the catalog to entries for the given country. (optional)
	 * @param  int|null $year Calendar year. Filters the catalog to entries whose startDate falls in the given year. (optional)
	 * @param  string|null $filter OData v4 filter expression. Supported fields: name, type, countryCode, startDate. Example: startDate ge &#39;2026-01-01&#39; and type eq &#39;PUBLIC&#39; (optional)
	 * @param  string|null $order_by Sort expression. Allowed fields: startDate, name, with optional asc/desc direction. (optional, default to 'startDate asc')
	 * @param  int|null $page Page number. (optional, default to 1)
	 * @param  int|null $page_size Page size. (optional, default to 20)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['listCatalogHolidays'] to see the possible values for this operation
	 *
	 * @throws \BhrSdk\ApiException on non-2xx response or if the response body is not in the expected format
	 * @throws \InvalidArgumentException
	 * @return \BhrSdk\Model\HolidayCatalogHolidayListResponseV1|\BhrSdk\Model\ProblemDetailsResponse|\BhrSdk\Model\ProblemDetailsResponse|\BhrSdk\Model\ProblemDetailsResponse
	 */
	public function listCatalogHolidays($country_code = null, $year = null, $filter = null, $order_by = 'startDate asc', $page = 1, $page_size = 20, string $contentType = self::CONTENT_TYPES['listCatalogHolidays'][0]) {
		list($response) = $this->listCatalogHolidaysWithHttpInfo($country_code, $year, $filter, $order_by, $page, $page_size, $contentType);
		return $response;
	}

	/**
	 * Operation listCatalogHolidaysWithHttpInfo
	 *
	 * List Catalog Holidays
	 *
	 * @param  string|null $country_code ISO 3166-1 alpha-2 country code. Filters the catalog to entries for the given country. (optional)
	 * @param  int|null $year Calendar year. Filters the catalog to entries whose startDate falls in the given year. (optional)
	 * @param  string|null $filter OData v4 filter expression. Supported fields: name, type, countryCode, startDate. Example: startDate ge &#39;2026-01-01&#39; and type eq &#39;PUBLIC&#39; (optional)
	 * @param  string|null $order_by Sort expression. Allowed fields: startDate, name, with optional asc/desc direction. (optional, default to 'startDate asc')
	 * @param  int|null $page Page number. (optional, default to 1)
	 * @param  int|null $page_size Page size. (optional, default to 20)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['listCatalogHolidays'] to see the possible values for this operation
	 *
	 * @throws \BhrSdk\ApiException on non-2xx response or if the response body is not in the expected format
	 * @throws \InvalidArgumentException
	 * @return array of \BhrSdk\Model\HolidayCatalogHolidayListResponseV1|\BhrSdk\Model\ProblemDetailsResponse|\BhrSdk\Model\ProblemDetailsResponse|\BhrSdk\Model\ProblemDetailsResponse, HTTP status code, HTTP response headers (array of strings)
	 */
	public function listCatalogHolidaysWithHttpInfo($country_code = null, $year = null, $filter = null, $order_by = 'startDate asc', $page = 1, $page_size = 20, string $contentType = self::CONTENT_TYPES['listCatalogHolidays'][0]) {
		$request = $this->listCatalogHolidaysRequest($country_code, $year, $filter, $order_by, $page, $page_size, $contentType);
		$options = ApiHelper::createHttpClientOption($this->config);
		
		// Send request with retry support for timeout errors
		$response = ApiHelper::sendRequestWithRetries($this->logger, $this->client, $this->config, $request, $options);

		$statusCode = $response->getStatusCode();

		switch($statusCode) {
			case 200:
				return ApiHelper::handleResponseWithDataType(
					'\BhrSdk\Model\HolidayCatalogHolidayListResponseV1',
					$request,
					$response,
				);
			case 401:
				return ApiHelper::handleResponseWithDataType(
					'\BhrSdk\Model\ProblemDetailsResponse',
					$request,
					$response,
				);
			case 403:
				return ApiHelper::handleResponseWithDataType(
					'\BhrSdk\Model\ProblemDetailsResponse',
					$request,
					$response,
				);
			case 422:
				return ApiHelper::handleResponseWithDataType(
					'\BhrSdk\Model\ProblemDetailsResponse',
					$request,
					$response,
				);
		}

		if ($statusCode < 200 || $statusCode > 299) {
			throw new ApiException(
				sprintf(
					'[%d] Error connecting to the API (%s)',
					$statusCode,
					(string) $request->getUri()
				),
				$statusCode,
				$response->getHeaders(),
				(string) $response->getBody()
			);
		}

		return ApiHelper::handleResponseWithDataType(
			'\BhrSdk\Model\HolidayCatalogHolidayListResponseV1',
			$request,
			$response,
		);
	}

	/**
	 * Operation listCatalogHolidaysAsync
	 *
	 * List Catalog Holidays
	 *
	 * @param  string|null $country_code ISO 3166-1 alpha-2 country code. Filters the catalog to entries for the given country. (optional)
	 * @param  int|null $year Calendar year. Filters the catalog to entries whose startDate falls in the given year. (optional)
	 * @param  string|null $filter OData v4 filter expression. Supported fields: name, type, countryCode, startDate. Example: startDate ge &#39;2026-01-01&#39; and type eq &#39;PUBLIC&#39; (optional)
	 * @param  string|null $order_by Sort expression. Allowed fields: startDate, name, with optional asc/desc direction. (optional, default to 'startDate asc')
	 * @param  int|null $page Page number. (optional, default to 1)
	 * @param  int|null $page_size Page size. (optional, default to 20)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['listCatalogHolidays'] to see the possible values for this operation
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Promise\PromiseInterface
	 */
	public function listCatalogHolidaysAsync($country_code = null, $year = null, $filter = null, $order_by = 'startDate asc', $page = 1, $page_size = 20, string $contentType = self::CONTENT_TYPES['listCatalogHolidays'][0]) {
		return $this->listCatalogHolidaysAsyncWithHttpInfo($country_code, $year, $filter, $order_by, $page, $page_size, $contentType)
			->then(
				function ($response) {
					return $response[0];
				}
			);
	}

	/**
	 * Operation listCatalogHolidaysAsyncWithHttpInfo
	 *
	 * List Catalog Holidays
	 *
	 * @param  string|null $country_code ISO 3166-1 alpha-2 country code. Filters the catalog to entries for the given country. (optional)
	 * @param  int|null $year Calendar year. Filters the catalog to entries whose startDate falls in the given year. (optional)
	 * @param  string|null $filter OData v4 filter expression. Supported fields: name, type, countryCode, startDate. Example: startDate ge &#39;2026-01-01&#39; and type eq &#39;PUBLIC&#39; (optional)
	 * @param  string|null $order_by Sort expression. Allowed fields: startDate, name, with optional asc/desc direction. (optional, default to 'startDate asc')
	 * @param  int|null $page Page number. (optional, default to 1)
	 * @param  int|null $page_size Page size. (optional, default to 20)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['listCatalogHolidays'] to see the possible values for this operation
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Promise\PromiseInterface
	 */
	public function listCatalogHolidaysAsyncWithHttpInfo($country_code = null, $year = null, $filter = null, $order_by = 'startDate asc', $page = 1, $page_size = 20, string $contentType = self::CONTENT_TYPES['listCatalogHolidays'][0]) {
		$returnType = '\BhrSdk\Model\HolidayCatalogHolidayListResponseV1';
		$request = $this->listCatalogHolidaysRequest($country_code, $year, $filter, $order_by, $page, $page_size, $contentType);

		return ApiHelper::sendRequestWithRetriesAsync($this->logger, $this->client, $this->config, $request, ApiHelper::createHttpClientOption($this->config))
			->then(
				function ($response) use ($returnType) {
					$content = (string) $response->getBody();
					if ($returnType !== 'string') {
						$content = json_decode($content);
					}

					return [
						ObjectSerializer::deserialize($content, $returnType, []),
						$response->getStatusCode(),
						$response->getHeaders()
					];
				},
				function ($exception) {
					$response = $exception->getResponse();
					$statusCode = $response->getStatusCode();
					throw new ApiException(
						sprintf(
							'[%d] Error connecting to the API (%s)',
							$statusCode,
							$exception->getRequest()->getUri()
						),
						$statusCode,
						$response->getHeaders(),
						(string) $response->getBody()
					);
				}
			);
	}

	/**
	 * Create request for operation 'listCatalogHolidays'
	 *
	 * @param  string|null $country_code ISO 3166-1 alpha-2 country code. Filters the catalog to entries for the given country. (optional)
	 * @param  int|null $year Calendar year. Filters the catalog to entries whose startDate falls in the given year. (optional)
	 * @param  string|null $filter OData v4 filter expression. Supported fields: name, type, countryCode, startDate. Example: startDate ge &#39;2026-01-01&#39; and type eq &#39;PUBLIC&#39; (optional)
	 * @param  string|null $order_by Sort expression. Allowed fields: startDate, name, with optional asc/desc direction. (optional, default to 'startDate asc')
	 * @param  int|null $page Page number. (optional, default to 1)
	 * @param  int|null $page_size Page size. (optional, default to 20)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['listCatalogHolidays'] to see the possible values for this operation
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Psr7\Request
	 */
	public function listCatalogHolidaysRequest($country_code = null, $year = null, $filter = null, $order_by = 'startDate asc', $page = 1, $page_size = 20, string $contentType = self::CONTENT_TYPES['listCatalogHolidays'][0]) {

		if ($country_code !== null && !preg_match("/^[A-Za-z]{2}$/", $country_code)) {
			throw new \InvalidArgumentException("invalid value for \"country_code\" when calling HolidaysApi.listCatalogHolidays, must conform to the pattern /^[A-Za-z]{2}$/.");
		}
		
		if ($page !== null && $page < 1) {
			throw new \InvalidArgumentException('invalid value for "$page" when calling HolidaysApi.listCatalogHolidays, must be bigger than or equal to 1.');
		}
		
		if ($page_size !== null && $page_size > 100) {
			throw new \InvalidArgumentException('invalid value for "$page_size" when calling HolidaysApi.listCatalogHolidays, must be smaller than or equal to 100.');
		}
		if ($page_size !== null && $page_size < 1) {
			throw new \InvalidArgumentException('invalid value for "$page_size" when calling HolidaysApi.listCatalogHolidays, must be bigger than or equal to 1.');
		}
		
		$resourcePath = '/api/v1/holidays/catalog';
		$this->logger?->info('Request method: [GET], URL: ' . $resourcePath);
		
		$queryParams = [];
		$headerParams = [];
		$httpBody = '';
		$multipart = false;

		$parameters = [
			'countryCode' => ['value' => $country_code, 'type' => 'string', 'required' => false, 'style' => 'form', 'explode' => true],
			'year' => ['value' => $year, 'type' => 'integer', 'required' => false, 'style' => 'form', 'explode' => true],
			'filter' => ['value' => $filter, 'type' => 'string', 'required' => false, 'style' => 'form', 'explode' => true],
			'orderBy' => ['value' => $order_by, 'type' => 'string', 'required' => false, 'style' => 'form', 'explode' => true],
			'page' => ['value' => $page, 'type' => 'integer', 'required' => false, 'style' => 'form', 'explode' => true],
			'pageSize' => ['value' => $page_size, 'type' => 'integer', 'required' => false, 'style' => 'form', 'explode' => true],
		];

		// Process parameters and build query values directly
		$queryParams = [];

		foreach ($parameters as $paramName => $config) {
			$value = ObjectSerializer::toQueryValue($config['value'], $paramName, $config['type'], $config['style'], $config['explode'], $config['required']);
			
			if ($value !== null) {
				// Merge each parameter value directly into queryParams
				$queryParams = array_merge($queryParams, $value);
			}
		}

		$headers = $this->headerSelector->selectHeaders(
			['application/json', ],
			$contentType,
			$multipart
		);

		// Authentication methods
		
		// Basic authentication
		if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
			$this->logger?->info('Using Basic authentication');	
			$headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
		}
		
		// OAuth/Bearer authentication
		if (!empty($this->config->getAccessToken())) {
			$this->logger?->info('Using Bearer authentication');
			$headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
		}

		$defaultHeaders = [];
		if ($this->config->getUserAgent()) {
			$this->logger?->debug('Using User-Agent: ' . $this->config->getUserAgent());	
			$defaultHeaders['User-Agent'] = $this->config->getUserAgent();
		}

		$headers = array_merge(
			$defaultHeaders,
			$headerParams,
			$headers
		);
		
		// Special handling for accept_header_parameter to set the Accept header directly
		/** @phpstan-ignore-next-line */
		if (isset($accept_header_parameter) && $accept_header_parameter !== null) {
			$this->logger?->debug('Overriding Accept header: ' . $accept_header_parameter);
			/** @phpstan-ignore-next-line */
			$headers['Accept'] = ObjectSerializer::toHeaderValue($accept_header_parameter);
		}

		$operationHost = $this->config->getHost();
		$query = ObjectSerializer::buildQuery($queryParams);
		return new Request(
			'GET',
			$operationHost . $resourcePath . ($query ? "?{$query}" : ''),
			$headers,
			is_string($httpBody) ? $httpBody : (string)$httpBody
		);
	}

	/**
	 * Operation listCompanyHolidays
	 *
	 * List Company Holidays
	 *
	 * @param  string|null $filter OData filter expression applied to company holidays. Supported operators: &#x60;eq&#x60; (equals, use &#x60;eq null&#x60; to match NULL), &#x60;ne&#x60; (not equals, use &#x60;ne null&#x60; to match NOT NULL), &#x60;lt&#x60; (less than), &#x60;le&#x60; (less than or equal), &#x60;gt&#x60; (greater than), &#x60;ge&#x60; (greater than or equal), &#x60;in&#x60; (value in list), &#x60;and&#x60; (combine clauses). Not supported: &#x60;or&#x60;, &#x60;not&#x60;, parenthesized grouping. Filterable fields: &#x60;name&#x60;, &#x60;startDate&#x60;, &#x60;endDate&#x60;, &#x60;isPublic&#x60;, &#x60;globalHolidayUuid&#x60;. Examples: &#x60;startDate ge &#39;2026-01-01&#39;&#x60;, &#x60;isPublic eq true and endDate ne null&#x60;. (optional)
	 * @param  string|null $order_by Comma-separated list of sort terms, each a field optionally followed by &#x60;asc&#x60; or &#x60;desc&#x60;. Allowed sort fields: &#x60;name&#x60;, &#x60;startDate&#x60;, &#x60;endDate&#x60;, &#x60;createdAt&#x60;, &#x60;updatedAt&#x60;. (optional, default to 'startDate asc')
	 * @param  string|null $select Comma-separated list of properties to include in each returned holiday. Reduces payload size. Example: &#x60;id,name,startDate&#x60;. (optional)
	 * @param  int|null $page The page number to retrieve. (optional, default to 1)
	 * @param  int|null $page_size The number of items to return per page. (optional, default to 20)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['listCompanyHolidays'] to see the possible values for this operation
	 *
	 * @throws \BhrSdk\ApiException on non-2xx response or if the response body is not in the expected format
	 * @throws \InvalidArgumentException
	 * @return \BhrSdk\Model\HolidayCompanyHolidayListResponseV1|\BhrSdk\Model\ProblemDetailsResponse|\BhrSdk\Model\ProblemDetailsResponse|\BhrSdk\Model\ProblemDetailsResponse
	 */
	public function listCompanyHolidays($filter = null, $order_by = 'startDate asc', $select = null, $page = 1, $page_size = 20, string $contentType = self::CONTENT_TYPES['listCompanyHolidays'][0]) {
		list($response) = $this->listCompanyHolidaysWithHttpInfo($filter, $order_by, $select, $page, $page_size, $contentType);
		return $response;
	}

	/**
	 * Operation listCompanyHolidaysWithHttpInfo
	 *
	 * List Company Holidays
	 *
	 * @param  string|null $filter OData filter expression applied to company holidays. Supported operators: &#x60;eq&#x60; (equals, use &#x60;eq null&#x60; to match NULL), &#x60;ne&#x60; (not equals, use &#x60;ne null&#x60; to match NOT NULL), &#x60;lt&#x60; (less than), &#x60;le&#x60; (less than or equal), &#x60;gt&#x60; (greater than), &#x60;ge&#x60; (greater than or equal), &#x60;in&#x60; (value in list), &#x60;and&#x60; (combine clauses). Not supported: &#x60;or&#x60;, &#x60;not&#x60;, parenthesized grouping. Filterable fields: &#x60;name&#x60;, &#x60;startDate&#x60;, &#x60;endDate&#x60;, &#x60;isPublic&#x60;, &#x60;globalHolidayUuid&#x60;. Examples: &#x60;startDate ge &#39;2026-01-01&#39;&#x60;, &#x60;isPublic eq true and endDate ne null&#x60;. (optional)
	 * @param  string|null $order_by Comma-separated list of sort terms, each a field optionally followed by &#x60;asc&#x60; or &#x60;desc&#x60;. Allowed sort fields: &#x60;name&#x60;, &#x60;startDate&#x60;, &#x60;endDate&#x60;, &#x60;createdAt&#x60;, &#x60;updatedAt&#x60;. (optional, default to 'startDate asc')
	 * @param  string|null $select Comma-separated list of properties to include in each returned holiday. Reduces payload size. Example: &#x60;id,name,startDate&#x60;. (optional)
	 * @param  int|null $page The page number to retrieve. (optional, default to 1)
	 * @param  int|null $page_size The number of items to return per page. (optional, default to 20)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['listCompanyHolidays'] to see the possible values for this operation
	 *
	 * @throws \BhrSdk\ApiException on non-2xx response or if the response body is not in the expected format
	 * @throws \InvalidArgumentException
	 * @return array of \BhrSdk\Model\HolidayCompanyHolidayListResponseV1|\BhrSdk\Model\ProblemDetailsResponse|\BhrSdk\Model\ProblemDetailsResponse|\BhrSdk\Model\ProblemDetailsResponse, HTTP status code, HTTP response headers (array of strings)
	 */
	public function listCompanyHolidaysWithHttpInfo($filter = null, $order_by = 'startDate asc', $select = null, $page = 1, $page_size = 20, string $contentType = self::CONTENT_TYPES['listCompanyHolidays'][0]) {
		$request = $this->listCompanyHolidaysRequest($filter, $order_by, $select, $page, $page_size, $contentType);
		$options = ApiHelper::createHttpClientOption($this->config);
		
		// Send request with retry support for timeout errors
		$response = ApiHelper::sendRequestWithRetries($this->logger, $this->client, $this->config, $request, $options);

		$statusCode = $response->getStatusCode();

		switch($statusCode) {
			case 200:
				return ApiHelper::handleResponseWithDataType(
					'\BhrSdk\Model\HolidayCompanyHolidayListResponseV1',
					$request,
					$response,
				);
			case 401:
				return ApiHelper::handleResponseWithDataType(
					'\BhrSdk\Model\ProblemDetailsResponse',
					$request,
					$response,
				);
			case 403:
				return ApiHelper::handleResponseWithDataType(
					'\BhrSdk\Model\ProblemDetailsResponse',
					$request,
					$response,
				);
			case 422:
				return ApiHelper::handleResponseWithDataType(
					'\BhrSdk\Model\ProblemDetailsResponse',
					$request,
					$response,
				);
		}

		if ($statusCode < 200 || $statusCode > 299) {
			throw new ApiException(
				sprintf(
					'[%d] Error connecting to the API (%s)',
					$statusCode,
					(string) $request->getUri()
				),
				$statusCode,
				$response->getHeaders(),
				(string) $response->getBody()
			);
		}

		return ApiHelper::handleResponseWithDataType(
			'\BhrSdk\Model\HolidayCompanyHolidayListResponseV1',
			$request,
			$response,
		);
	}

	/**
	 * Operation listCompanyHolidaysAsync
	 *
	 * List Company Holidays
	 *
	 * @param  string|null $filter OData filter expression applied to company holidays. Supported operators: &#x60;eq&#x60; (equals, use &#x60;eq null&#x60; to match NULL), &#x60;ne&#x60; (not equals, use &#x60;ne null&#x60; to match NOT NULL), &#x60;lt&#x60; (less than), &#x60;le&#x60; (less than or equal), &#x60;gt&#x60; (greater than), &#x60;ge&#x60; (greater than or equal), &#x60;in&#x60; (value in list), &#x60;and&#x60; (combine clauses). Not supported: &#x60;or&#x60;, &#x60;not&#x60;, parenthesized grouping. Filterable fields: &#x60;name&#x60;, &#x60;startDate&#x60;, &#x60;endDate&#x60;, &#x60;isPublic&#x60;, &#x60;globalHolidayUuid&#x60;. Examples: &#x60;startDate ge &#39;2026-01-01&#39;&#x60;, &#x60;isPublic eq true and endDate ne null&#x60;. (optional)
	 * @param  string|null $order_by Comma-separated list of sort terms, each a field optionally followed by &#x60;asc&#x60; or &#x60;desc&#x60;. Allowed sort fields: &#x60;name&#x60;, &#x60;startDate&#x60;, &#x60;endDate&#x60;, &#x60;createdAt&#x60;, &#x60;updatedAt&#x60;. (optional, default to 'startDate asc')
	 * @param  string|null $select Comma-separated list of properties to include in each returned holiday. Reduces payload size. Example: &#x60;id,name,startDate&#x60;. (optional)
	 * @param  int|null $page The page number to retrieve. (optional, default to 1)
	 * @param  int|null $page_size The number of items to return per page. (optional, default to 20)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['listCompanyHolidays'] to see the possible values for this operation
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Promise\PromiseInterface
	 */
	public function listCompanyHolidaysAsync($filter = null, $order_by = 'startDate asc', $select = null, $page = 1, $page_size = 20, string $contentType = self::CONTENT_TYPES['listCompanyHolidays'][0]) {
		return $this->listCompanyHolidaysAsyncWithHttpInfo($filter, $order_by, $select, $page, $page_size, $contentType)
			->then(
				function ($response) {
					return $response[0];
				}
			);
	}

	/**
	 * Operation listCompanyHolidaysAsyncWithHttpInfo
	 *
	 * List Company Holidays
	 *
	 * @param  string|null $filter OData filter expression applied to company holidays. Supported operators: &#x60;eq&#x60; (equals, use &#x60;eq null&#x60; to match NULL), &#x60;ne&#x60; (not equals, use &#x60;ne null&#x60; to match NOT NULL), &#x60;lt&#x60; (less than), &#x60;le&#x60; (less than or equal), &#x60;gt&#x60; (greater than), &#x60;ge&#x60; (greater than or equal), &#x60;in&#x60; (value in list), &#x60;and&#x60; (combine clauses). Not supported: &#x60;or&#x60;, &#x60;not&#x60;, parenthesized grouping. Filterable fields: &#x60;name&#x60;, &#x60;startDate&#x60;, &#x60;endDate&#x60;, &#x60;isPublic&#x60;, &#x60;globalHolidayUuid&#x60;. Examples: &#x60;startDate ge &#39;2026-01-01&#39;&#x60;, &#x60;isPublic eq true and endDate ne null&#x60;. (optional)
	 * @param  string|null $order_by Comma-separated list of sort terms, each a field optionally followed by &#x60;asc&#x60; or &#x60;desc&#x60;. Allowed sort fields: &#x60;name&#x60;, &#x60;startDate&#x60;, &#x60;endDate&#x60;, &#x60;createdAt&#x60;, &#x60;updatedAt&#x60;. (optional, default to 'startDate asc')
	 * @param  string|null $select Comma-separated list of properties to include in each returned holiday. Reduces payload size. Example: &#x60;id,name,startDate&#x60;. (optional)
	 * @param  int|null $page The page number to retrieve. (optional, default to 1)
	 * @param  int|null $page_size The number of items to return per page. (optional, default to 20)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['listCompanyHolidays'] to see the possible values for this operation
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Promise\PromiseInterface
	 */
	public function listCompanyHolidaysAsyncWithHttpInfo($filter = null, $order_by = 'startDate asc', $select = null, $page = 1, $page_size = 20, string $contentType = self::CONTENT_TYPES['listCompanyHolidays'][0]) {
		$returnType = '\BhrSdk\Model\HolidayCompanyHolidayListResponseV1';
		$request = $this->listCompanyHolidaysRequest($filter, $order_by, $select, $page, $page_size, $contentType);

		return ApiHelper::sendRequestWithRetriesAsync($this->logger, $this->client, $this->config, $request, ApiHelper::createHttpClientOption($this->config))
			->then(
				function ($response) use ($returnType) {
					$content = (string) $response->getBody();
					if ($returnType !== 'string') {
						$content = json_decode($content);
					}

					return [
						ObjectSerializer::deserialize($content, $returnType, []),
						$response->getStatusCode(),
						$response->getHeaders()
					];
				},
				function ($exception) {
					$response = $exception->getResponse();
					$statusCode = $response->getStatusCode();
					throw new ApiException(
						sprintf(
							'[%d] Error connecting to the API (%s)',
							$statusCode,
							$exception->getRequest()->getUri()
						),
						$statusCode,
						$response->getHeaders(),
						(string) $response->getBody()
					);
				}
			);
	}

	/**
	 * Create request for operation 'listCompanyHolidays'
	 *
	 * @param  string|null $filter OData filter expression applied to company holidays. Supported operators: &#x60;eq&#x60; (equals, use &#x60;eq null&#x60; to match NULL), &#x60;ne&#x60; (not equals, use &#x60;ne null&#x60; to match NOT NULL), &#x60;lt&#x60; (less than), &#x60;le&#x60; (less than or equal), &#x60;gt&#x60; (greater than), &#x60;ge&#x60; (greater than or equal), &#x60;in&#x60; (value in list), &#x60;and&#x60; (combine clauses). Not supported: &#x60;or&#x60;, &#x60;not&#x60;, parenthesized grouping. Filterable fields: &#x60;name&#x60;, &#x60;startDate&#x60;, &#x60;endDate&#x60;, &#x60;isPublic&#x60;, &#x60;globalHolidayUuid&#x60;. Examples: &#x60;startDate ge &#39;2026-01-01&#39;&#x60;, &#x60;isPublic eq true and endDate ne null&#x60;. (optional)
	 * @param  string|null $order_by Comma-separated list of sort terms, each a field optionally followed by &#x60;asc&#x60; or &#x60;desc&#x60;. Allowed sort fields: &#x60;name&#x60;, &#x60;startDate&#x60;, &#x60;endDate&#x60;, &#x60;createdAt&#x60;, &#x60;updatedAt&#x60;. (optional, default to 'startDate asc')
	 * @param  string|null $select Comma-separated list of properties to include in each returned holiday. Reduces payload size. Example: &#x60;id,name,startDate&#x60;. (optional)
	 * @param  int|null $page The page number to retrieve. (optional, default to 1)
	 * @param  int|null $page_size The number of items to return per page. (optional, default to 20)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['listCompanyHolidays'] to see the possible values for this operation
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Psr7\Request
	 */
	public function listCompanyHolidaysRequest($filter = null, $order_by = 'startDate asc', $select = null, $page = 1, $page_size = 20, string $contentType = self::CONTENT_TYPES['listCompanyHolidays'][0]) {

		if ($page !== null && $page < 1) {
			throw new \InvalidArgumentException('invalid value for "$page" when calling HolidaysApi.listCompanyHolidays, must be bigger than or equal to 1.');
		}
		
		if ($page_size !== null && $page_size > 100) {
			throw new \InvalidArgumentException('invalid value for "$page_size" when calling HolidaysApi.listCompanyHolidays, must be smaller than or equal to 100.');
		}
		if ($page_size !== null && $page_size < 1) {
			throw new \InvalidArgumentException('invalid value for "$page_size" when calling HolidaysApi.listCompanyHolidays, must be bigger than or equal to 1.');
		}
		
		$resourcePath = '/api/v1/holidays';
		$this->logger?->info('Request method: [GET], URL: ' . $resourcePath);
		
		$queryParams = [];
		$headerParams = [];
		$httpBody = '';
		$multipart = false;

		$parameters = [
			'filter' => ['value' => $filter, 'type' => 'string', 'required' => false, 'style' => 'form', 'explode' => true],
			'orderBy' => ['value' => $order_by, 'type' => 'string', 'required' => false, 'style' => 'form', 'explode' => true],
			'select' => ['value' => $select, 'type' => 'string', 'required' => false, 'style' => 'form', 'explode' => true],
			'page' => ['value' => $page, 'type' => 'integer', 'required' => false, 'style' => 'form', 'explode' => true],
			'pageSize' => ['value' => $page_size, 'type' => 'integer', 'required' => false, 'style' => 'form', 'explode' => true],
		];

		// Process parameters and build query values directly
		$queryParams = [];

		foreach ($parameters as $paramName => $config) {
			$value = ObjectSerializer::toQueryValue($config['value'], $paramName, $config['type'], $config['style'], $config['explode'], $config['required']);
			
			if ($value !== null) {
				// Merge each parameter value directly into queryParams
				$queryParams = array_merge($queryParams, $value);
			}
		}

		$headers = $this->headerSelector->selectHeaders(
			['application/json', ],
			$contentType,
			$multipart
		);

		// Authentication methods
		
		// Basic authentication
		if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
			$this->logger?->info('Using Basic authentication');	
			$headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
		}
		
		// OAuth/Bearer authentication
		if (!empty($this->config->getAccessToken())) {
			$this->logger?->info('Using Bearer authentication');
			$headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
		}

		$defaultHeaders = [];
		if ($this->config->getUserAgent()) {
			$this->logger?->debug('Using User-Agent: ' . $this->config->getUserAgent());	
			$defaultHeaders['User-Agent'] = $this->config->getUserAgent();
		}

		$headers = array_merge(
			$defaultHeaders,
			$headerParams,
			$headers
		);
		
		// Special handling for accept_header_parameter to set the Accept header directly
		/** @phpstan-ignore-next-line */
		if (isset($accept_header_parameter) && $accept_header_parameter !== null) {
			$this->logger?->debug('Overriding Accept header: ' . $accept_header_parameter);
			/** @phpstan-ignore-next-line */
			$headers['Accept'] = ObjectSerializer::toHeaderValue($accept_header_parameter);
		}

		$operationHost = $this->config->getHost();
		$query = ObjectSerializer::buildQuery($queryParams);
		return new Request(
			'GET',
			$operationHost . $resourcePath . ($query ? "?{$query}" : ''),
			$headers,
			is_string($httpBody) ? $httpBody : (string)$httpBody
		);
	}

	/**
	 * Operation updateCompanyHoliday
	 *
	 * Update Company Holiday
	 *
	 * @param  int $id The company holiday ID. (required)
	 * @param  \BhrSdk\Model\HolidayUpdateCompanyHolidayRequestV1 $holiday_update_company_holiday_request_v1 holiday_update_company_holiday_request_v1 (required)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['updateCompanyHoliday'] to see the possible values for this operation
	 *
	 * @throws \BhrSdk\ApiException on non-2xx response or if the response body is not in the expected format
	 * @throws \InvalidArgumentException
	 * @return \BhrSdk\Model\HolidayCompanyHolidayV1|\BhrSdk\Model\ProblemDetailsResponse|\BhrSdk\Model\ProblemDetailsResponse|\BhrSdk\Model\ProblemDetailsResponse|\BhrSdk\Model\ProblemDetailsResponse|\BhrSdk\Model\ProblemDetailsResponse|\BhrSdk\Model\ProblemDetailsResponse
	 */
	public function updateCompanyHoliday($id, $holiday_update_company_holiday_request_v1, string $contentType = self::CONTENT_TYPES['updateCompanyHoliday'][0]) {
		list($response) = $this->updateCompanyHolidayWithHttpInfo($id, $holiday_update_company_holiday_request_v1, $contentType);
		return $response;
	}

	/**
	 * Operation updateCompanyHolidayWithHttpInfo
	 *
	 * Update Company Holiday
	 *
	 * @param  int $id The company holiday ID. (required)
	 * @param  \BhrSdk\Model\HolidayUpdateCompanyHolidayRequestV1 $holiday_update_company_holiday_request_v1 (required)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['updateCompanyHoliday'] to see the possible values for this operation
	 *
	 * @throws \BhrSdk\ApiException on non-2xx response or if the response body is not in the expected format
	 * @throws \InvalidArgumentException
	 * @return array of \BhrSdk\Model\HolidayCompanyHolidayV1|\BhrSdk\Model\ProblemDetailsResponse|\BhrSdk\Model\ProblemDetailsResponse|\BhrSdk\Model\ProblemDetailsResponse|\BhrSdk\Model\ProblemDetailsResponse|\BhrSdk\Model\ProblemDetailsResponse|\BhrSdk\Model\ProblemDetailsResponse, HTTP status code, HTTP response headers (array of strings)
	 */
	public function updateCompanyHolidayWithHttpInfo($id, $holiday_update_company_holiday_request_v1, string $contentType = self::CONTENT_TYPES['updateCompanyHoliday'][0]) {
		$request = $this->updateCompanyHolidayRequest($id, $holiday_update_company_holiday_request_v1, $contentType);
		$options = ApiHelper::createHttpClientOption($this->config);
		
		// Send request with retry support for timeout errors
		$response = ApiHelper::sendRequestWithRetries($this->logger, $this->client, $this->config, $request, $options);

		$statusCode = $response->getStatusCode();

		switch($statusCode) {
			case 200:
				return ApiHelper::handleResponseWithDataType(
					'\BhrSdk\Model\HolidayCompanyHolidayV1',
					$request,
					$response,
				);
			case 400:
				return ApiHelper::handleResponseWithDataType(
					'\BhrSdk\Model\ProblemDetailsResponse',
					$request,
					$response,
				);
			case 401:
				return ApiHelper::handleResponseWithDataType(
					'\BhrSdk\Model\ProblemDetailsResponse',
					$request,
					$response,
				);
			case 403:
				return ApiHelper::handleResponseWithDataType(
					'\BhrSdk\Model\ProblemDetailsResponse',
					$request,
					$response,
				);
			case 404:
				return ApiHelper::handleResponseWithDataType(
					'\BhrSdk\Model\ProblemDetailsResponse',
					$request,
					$response,
				);
			case 415:
				return ApiHelper::handleResponseWithDataType(
					'\BhrSdk\Model\ProblemDetailsResponse',
					$request,
					$response,
				);
			case 422:
				return ApiHelper::handleResponseWithDataType(
					'\BhrSdk\Model\ProblemDetailsResponse',
					$request,
					$response,
				);
		}

		if ($statusCode < 200 || $statusCode > 299) {
			throw new ApiException(
				sprintf(
					'[%d] Error connecting to the API (%s)',
					$statusCode,
					(string) $request->getUri()
				),
				$statusCode,
				$response->getHeaders(),
				(string) $response->getBody()
			);
		}

		return ApiHelper::handleResponseWithDataType(
			'\BhrSdk\Model\HolidayCompanyHolidayV1',
			$request,
			$response,
		);
	}

	/**
	 * Operation updateCompanyHolidayAsync
	 *
	 * Update Company Holiday
	 *
	 * @param  int $id The company holiday ID. (required)
	 * @param  \BhrSdk\Model\HolidayUpdateCompanyHolidayRequestV1 $holiday_update_company_holiday_request_v1 (required)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['updateCompanyHoliday'] to see the possible values for this operation
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Promise\PromiseInterface
	 */
	public function updateCompanyHolidayAsync($id, $holiday_update_company_holiday_request_v1, string $contentType = self::CONTENT_TYPES['updateCompanyHoliday'][0]) {
		return $this->updateCompanyHolidayAsyncWithHttpInfo($id, $holiday_update_company_holiday_request_v1, $contentType)
			->then(
				function ($response) {
					return $response[0];
				}
			);
	}

	/**
	 * Operation updateCompanyHolidayAsyncWithHttpInfo
	 *
	 * Update Company Holiday
	 *
	 * @param  int $id The company holiday ID. (required)
	 * @param  \BhrSdk\Model\HolidayUpdateCompanyHolidayRequestV1 $holiday_update_company_holiday_request_v1 (required)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['updateCompanyHoliday'] to see the possible values for this operation
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Promise\PromiseInterface
	 */
	public function updateCompanyHolidayAsyncWithHttpInfo($id, $holiday_update_company_holiday_request_v1, string $contentType = self::CONTENT_TYPES['updateCompanyHoliday'][0]) {
		$returnType = '\BhrSdk\Model\HolidayCompanyHolidayV1';
		$request = $this->updateCompanyHolidayRequest($id, $holiday_update_company_holiday_request_v1, $contentType);

		return ApiHelper::sendRequestWithRetriesAsync($this->logger, $this->client, $this->config, $request, ApiHelper::createHttpClientOption($this->config))
			->then(
				function ($response) use ($returnType) {
					$content = (string) $response->getBody();
					if ($returnType !== 'string') {
						$content = json_decode($content);
					}

					return [
						ObjectSerializer::deserialize($content, $returnType, []),
						$response->getStatusCode(),
						$response->getHeaders()
					];
				},
				function ($exception) {
					$response = $exception->getResponse();
					$statusCode = $response->getStatusCode();
					throw new ApiException(
						sprintf(
							'[%d] Error connecting to the API (%s)',
							$statusCode,
							$exception->getRequest()->getUri()
						),
						$statusCode,
						$response->getHeaders(),
						(string) $response->getBody()
					);
				}
			);
	}

	/**
	 * Create request for operation 'updateCompanyHoliday'
	 *
	 * @param  int $id The company holiday ID. (required)
	 * @param  \BhrSdk\Model\HolidayUpdateCompanyHolidayRequestV1 $holiday_update_company_holiday_request_v1 (required)
	 * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['updateCompanyHoliday'] to see the possible values for this operation
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Psr7\Request
	 */
	public function updateCompanyHolidayRequest($id, $holiday_update_company_holiday_request_v1, string $contentType = self::CONTENT_TYPES['updateCompanyHoliday'][0]) {
		// PHP 8.0+ only
		ApiHelper::validateRequiredParameters(
			params: [
				'id' => $id,
				'holiday_update_company_holiday_request_v1' => $holiday_update_company_holiday_request_v1,
			],
			methodName: 'updateCompanyHoliday'
		);

		$resourcePath = '/api/v1/holidays/{id}';
		$this->logger?->info('Request method: [PATCH], URL: ' . $resourcePath);
		
		$queryParams = [];
		$headerParams = [];
		$httpBody = '';
		$multipart = false;

		// path params
		if ($id !== null) {
			$resourcePath = str_replace(
				'{' . 'id' . '}',
				ObjectSerializer::toPathValue((string) $id),
				$resourcePath
			);
		}

		$headers = $this->headerSelector->selectHeaders(
			['application/json', ],
			$contentType,
			$multipart
		);

		// for model (json/xml)
		if (isset($holiday_update_company_holiday_request_v1)) {
			if (stripos($headers['Content-Type'], 'application/json') !== false) {
				# if Content-Type contains "application/json", json_encode the body
				$httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($holiday_update_company_holiday_request_v1));
			} else {
				$httpBody = is_array($holiday_update_company_holiday_request_v1) ? json_encode($holiday_update_company_holiday_request_v1) : $holiday_update_company_holiday_request_v1;
			}
		} 

		// Authentication methods
		
		// Basic authentication
		if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
			$this->logger?->info('Using Basic authentication');	
			$headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
		}
		
		// OAuth/Bearer authentication
		if (!empty($this->config->getAccessToken())) {
			$this->logger?->info('Using Bearer authentication');
			$headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
		}

		$defaultHeaders = [];
		if ($this->config->getUserAgent()) {
			$this->logger?->debug('Using User-Agent: ' . $this->config->getUserAgent());	
			$defaultHeaders['User-Agent'] = $this->config->getUserAgent();
		}

		$headers = array_merge(
			$defaultHeaders,
			$headerParams,
			$headers
		);
		
		// Special handling for accept_header_parameter to set the Accept header directly
		/** @phpstan-ignore-next-line */
		if (isset($accept_header_parameter) && $accept_header_parameter !== null) {
			$this->logger?->debug('Overriding Accept header: ' . $accept_header_parameter);
			/** @phpstan-ignore-next-line */
			$headers['Accept'] = ObjectSerializer::toHeaderValue($accept_header_parameter);
		}

		$operationHost = $this->config->getHost();
		$query = ObjectSerializer::buildQuery($queryParams);
		return new Request(
			'PATCH',
			$operationHost . $resourcePath . ($query ? "?{$query}" : ''),
			$headers,
			is_string($httpBody) ? $httpBody : (string)$httpBody
		);
	}

}
