<?php
/**
 * AccountStatusTransformerEmployees
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  MySdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BambooHR API
 *
 * BambooHR API documentation. https://www.bamboohr.com/api/documentation/
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MySdk\Model;

use \ArrayAccess;
use \MySdk\ObjectSerializer;

/**
 * AccountStatusTransformerEmployees Class Doc Comment
 *
 * @category Class
 * @description Employee status counts.
 * @package  MySdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AccountStatusTransformerEmployees implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AccountStatusTransformer_employees';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'active_employees' => 'mixed',
        'total_active_employees' => 'mixed',
        'employees_terminated_this_year' => 'mixed',
        'employees_terminated_last_december' => 'mixed',
        'total_terminated_employees' => 'mixed'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'active_employees' => null,
        'total_active_employees' => null,
        'employees_terminated_this_year' => null,
        'employees_terminated_last_december' => null,
        'total_terminated_employees' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'active_employees' => true,
        'total_active_employees' => true,
        'employees_terminated_this_year' => true,
        'employees_terminated_last_december' => true,
        'total_terminated_employees' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'active_employees' => 'activeEmployees',
        'total_active_employees' => 'totalActiveEmployees',
        'employees_terminated_this_year' => 'employeesTerminatedThisYear',
        'employees_terminated_last_december' => 'employeesTerminatedLastDecember',
        'total_terminated_employees' => 'totalTerminatedEmployees'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'active_employees' => 'setActiveEmployees',
        'total_active_employees' => 'setTotalActiveEmployees',
        'employees_terminated_this_year' => 'setEmployeesTerminatedThisYear',
        'employees_terminated_last_december' => 'setEmployeesTerminatedLastDecember',
        'total_terminated_employees' => 'setTotalTerminatedEmployees'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'active_employees' => 'getActiveEmployees',
        'total_active_employees' => 'getTotalActiveEmployees',
        'employees_terminated_this_year' => 'getEmployeesTerminatedThisYear',
        'employees_terminated_last_december' => 'getEmployeesTerminatedLastDecember',
        'total_terminated_employees' => 'getTotalTerminatedEmployees'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('active_employees', $data ?? [], null);
        $this->setIfExists('total_active_employees', $data ?? [], null);
        $this->setIfExists('employees_terminated_this_year', $data ?? [], null);
        $this->setIfExists('employees_terminated_last_december', $data ?? [], null);
        $this->setIfExists('total_terminated_employees', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets active_employees
     *
     * @return mixed|null
     */
    public function getActiveEmployees()
    {
        return $this->container['active_employees'];
    }

    /**
     * Sets active_employees
     *
     * @param mixed|null $active_employees Current number of active employees.
     *
     * @return self
     */
    public function setActiveEmployees($active_employees)
    {
        if (is_null($active_employees)) {
            array_push($this->openAPINullablesSetToNull, 'active_employees');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('active_employees', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['active_employees'] = $active_employees;

        return $this;
    }

    /**
     * Gets total_active_employees
     *
     * @return mixed|null
     */
    public function getTotalActiveEmployees()
    {
        return $this->container['total_active_employees'];
    }

    /**
     * Sets total_active_employees
     *
     * @param mixed|null $total_active_employees Expected total number of active employees.
     *
     * @return self
     */
    public function setTotalActiveEmployees($total_active_employees)
    {
        if (is_null($total_active_employees)) {
            array_push($this->openAPINullablesSetToNull, 'total_active_employees');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('total_active_employees', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['total_active_employees'] = $total_active_employees;

        return $this;
    }

    /**
     * Gets employees_terminated_this_year
     *
     * @return mixed|null
     */
    public function getEmployeesTerminatedThisYear()
    {
        return $this->container['employees_terminated_this_year'];
    }

    /**
     * Sets employees_terminated_this_year
     *
     * @param mixed|null $employees_terminated_this_year Number of employees terminated this year.
     *
     * @return self
     */
    public function setEmployeesTerminatedThisYear($employees_terminated_this_year)
    {
        if (is_null($employees_terminated_this_year)) {
            array_push($this->openAPINullablesSetToNull, 'employees_terminated_this_year');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('employees_terminated_this_year', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['employees_terminated_this_year'] = $employees_terminated_this_year;

        return $this;
    }

    /**
     * Gets employees_terminated_last_december
     *
     * @return mixed|null
     */
    public function getEmployeesTerminatedLastDecember()
    {
        return $this->container['employees_terminated_last_december'];
    }

    /**
     * Sets employees_terminated_last_december
     *
     * @param mixed|null $employees_terminated_last_december Number of employees terminated last December.
     *
     * @return self
     */
    public function setEmployeesTerminatedLastDecember($employees_terminated_last_december)
    {
        if (is_null($employees_terminated_last_december)) {
            array_push($this->openAPINullablesSetToNull, 'employees_terminated_last_december');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('employees_terminated_last_december', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['employees_terminated_last_december'] = $employees_terminated_last_december;

        return $this;
    }

    /**
     * Gets total_terminated_employees
     *
     * @return mixed|null
     */
    public function getTotalTerminatedEmployees()
    {
        return $this->container['total_terminated_employees'];
    }

    /**
     * Sets total_terminated_employees
     *
     * @param mixed|null $total_terminated_employees Expected total number of terminated employees.
     *
     * @return self
     */
    public function setTotalTerminatedEmployees($total_terminated_employees)
    {
        if (is_null($total_terminated_employees)) {
            array_push($this->openAPINullablesSetToNull, 'total_terminated_employees');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('total_terminated_employees', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['total_terminated_employees'] = $total_terminated_employees;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


