<?php
declare(strict_types=1);
/**
 * CreatedTimeOffRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  BhrSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BambooHR API
 *
 * BambooHR API documentation. https://www.bamboohr.com/api/documentation/
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace BhrSdk\Model;

use \ArrayAccess;
use \BhrSdk\ObjectSerializer;

/**
 * CreatedTimeOffRequest Class Doc Comment
 *
 * @category Class
 * @package  BhrSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CreatedTimeOffRequest implements ModelInterface, ArrayAccess, \JsonSerializable {
	public const DISCRIMINATOR = null;

	/**
	  * The original name of the model.
	  *
	  * @var string
	  */
	protected static $openApiModelName = 'CreatedTimeOffRequest';

	/**
	  * Array of property to type mappings. Used for (de)serialization
	  *
	  * @var string[]
	  */
	protected static $openApiTypes = [
		'id' => 'int',
		'employee_id' => 'int',
		'name' => 'string',
		'start' => '\DateTime',
		'end' => '\DateTime',
		'created' => '\DateTime',
		'status' => '\BhrSdk\Model\CreatedTimeOffRequestStatus',
		'type' => '\BhrSdk\Model\CreatedTimeOffRequestType',
		'amount' => '\BhrSdk\Model\CreatedTimeOffRequestAmount',
		'dates' => 'array<string,float>',
		'notes' => '\BhrSdk\Model\CreatedTimeOffRequestNotes',
		'comments' => 'object[]',
		'approvers' => 'array[]',
		'actions' => 'array<string,bool>',
		'overlapping_requests' => 'object[]',
		'policy_type' => 'string',
		'used_year_to_date' => 'float',
		'balance_on_date_of_request' => 'float'
	];

	/**
	  * Array of property to format mappings. Used for (de)serialization
	  *
	  * @var string[]
	  * @phpstan-var array<string, string|null>
	  * @psalm-var array<string, string|null>
	  */
	protected static $openApiFormats = [
		'id' => null,
		'employee_id' => null,
		'name' => null,
		'start' => 'date',
		'end' => 'date',
		'created' => 'date',
		'status' => null,
		'type' => null,
		'amount' => null,
		'dates' => null,
		'notes' => null,
		'comments' => null,
		'approvers' => null,
		'actions' => null,
		'overlapping_requests' => null,
		'policy_type' => null,
		'used_year_to_date' => null,
		'balance_on_date_of_request' => null
	];

	/**
	  * Array of nullable properties. Used for (de)serialization
	  *
	  * @var bool[]
	  * @phpstan-var array<string, bool>
	  */
	protected static array $openApiNullables = [
		'id' => false,
		'employee_id' => false,
		'name' => false,
		'start' => false,
		'end' => false,
		'created' => false,
		'status' => false,
		'type' => false,
		'amount' => false,
		'dates' => false,
		'notes' => false,
		'comments' => false,
		'approvers' => false,
		'actions' => false,
		'overlapping_requests' => false,
		'policy_type' => false,
		'used_year_to_date' => true,
		'balance_on_date_of_request' => true
	];

	/**
	  * If a nullable field gets set to null, insert it here
	  *
	  * @var bool[]
	  * @phpstan-var array<string, bool>
	  */
	protected array $openApiNullablesSetToNull = [];

	/**
	 * Array of property to type mappings. Used for (de)serialization
	 *
	 * @return array
	 */
	public static function openApiTypes() {
		return self::$openApiTypes;
	}

	/**
	 * Array of property to format mappings. Used for (de)serialization
	 *
	 * @return array
	 */
	public static function openApiFormats() {
		return self::$openApiFormats;
	}

	/**
	 * Array of nullable properties
	 *
	 * @return array
	 */
	protected static function openApiNullables(): array {
		return self::$openApiNullables;
	}

	/**
	 * Array of nullable field names deliberately set to null
	 *
	 * @return bool[]
	 * @phpstan-return array<string, bool>
	 */
	private function getOpenApiNullablesSetToNull(): array {
		return $this->openApiNullablesSetToNull;
	}

	/**
	 * Setter - Array of nullable field names deliberately set to null
	 *
	 * @param bool[] $openApiNullablesSetToNull
	 * @phpstan-param array<string, bool> $openApiNullablesSetToNull
	 */
	private function setOpenApiNullablesSetToNull(array $openApiNullablesSetToNull): void {
		$this->openApiNullablesSetToNull = $openApiNullablesSetToNull;
	}

	/**
	 * Checks if a property is nullable
	 *
	 * @param string $property
	 * @return bool
	 */
	public static function isNullable(string $property): bool {
		return self::openApiNullables()[$property] ?? false;
	}

	/**
	 * Checks if a nullable property is set to null.
	 *
	 * @param string $property
	 * @return bool
	 */
	public function isNullableSetToNull(string $property): bool {
		return isset($this->getOpenApiNullablesSetToNull()[$property]);
	}

	/**
	 * Array of attributes where the key is the local name,
	 * and the value is the original name
	 *
	 * @var string[]
	 */
	protected static $attributeMap = [
		'id' => 'id',
		'employee_id' => 'employeeId',
		'name' => 'name',
		'start' => 'start',
		'end' => 'end',
		'created' => 'created',
		'status' => 'status',
		'type' => 'type',
		'amount' => 'amount',
		'dates' => 'dates',
		'notes' => 'notes',
		'comments' => 'comments',
		'approvers' => 'approvers',
		'actions' => 'actions',
		'overlapping_requests' => 'overlappingRequests',
		'policy_type' => 'policyType',
		'used_year_to_date' => 'usedYearToDate',
		'balance_on_date_of_request' => 'balanceOnDateOfRequest'
	];

	/**
	 * Array of attributes to setter functions (for deserialization of responses)
	 *
	 * @var string[]
	 */
	protected static $setters = [
		'id' => 'setId',
		'employee_id' => 'setEmployeeId',
		'name' => 'setName',
		'start' => 'setStart',
		'end' => 'setEnd',
		'created' => 'setCreated',
		'status' => 'setStatus',
		'type' => 'setType',
		'amount' => 'setAmount',
		'dates' => 'setDates',
		'notes' => 'setNotes',
		'comments' => 'setComments',
		'approvers' => 'setApprovers',
		'actions' => 'setActions',
		'overlapping_requests' => 'setOverlappingRequests',
		'policy_type' => 'setPolicyType',
		'used_year_to_date' => 'setUsedYearToDate',
		'balance_on_date_of_request' => 'setBalanceOnDateOfRequest'
	];

	/**
	 * Array of attributes to getter functions (for serialization of requests)
	 *
	 * @var string[]
	 */
	protected static $getters = [
		'id' => 'getId',
		'employee_id' => 'getEmployeeId',
		'name' => 'getName',
		'start' => 'getStart',
		'end' => 'getEnd',
		'created' => 'getCreated',
		'status' => 'getStatus',
		'type' => 'getType',
		'amount' => 'getAmount',
		'dates' => 'getDates',
		'notes' => 'getNotes',
		'comments' => 'getComments',
		'approvers' => 'getApprovers',
		'actions' => 'getActions',
		'overlapping_requests' => 'getOverlappingRequests',
		'policy_type' => 'getPolicyType',
		'used_year_to_date' => 'getUsedYearToDate',
		'balance_on_date_of_request' => 'getBalanceOnDateOfRequest'
	];

	/**
	 * Array of attributes where the key is the local name,
	 * and the value is the original name
	 *
	 * @return array
	 */
	public static function attributeMap() {
		return self::$attributeMap;
	}

	/**
	 * Array of attributes to setter functions (for deserialization of responses)
	 *
	 * @return array
	 */
	public static function setters() {
		return self::$setters;
	}

	/**
	 * Array of attributes to getter functions (for serialization of requests)
	 *
	 * @return array
	 */
	public static function getters() {
		return self::$getters;
	}

	/**
	 * The original name of the model.
	 *
	 * @return string
	 */
	public function getModelName() {
		return self::$openApiModelName;
	}

	/**
	 * Associative array for storing property values
	 *
	 * @var mixed[]
	 */
	protected $container = [];

	/**
	 * Constructor
	 *
	 * @param mixed[]|null $data Associated array of property values
	 *                           initializing the model
	 */
	public function __construct(?array $data = null) {
		$this->setIfExists('id', $data ?? [], null);
		$this->setIfExists('employee_id', $data ?? [], null);
		$this->setIfExists('name', $data ?? [], null);
		$this->setIfExists('start', $data ?? [], null);
		$this->setIfExists('end', $data ?? [], null);
		$this->setIfExists('created', $data ?? [], null);
		$this->setIfExists('status', $data ?? [], null);
		$this->setIfExists('type', $data ?? [], null);
		$this->setIfExists('amount', $data ?? [], null);
		$this->setIfExists('dates', $data ?? [], null);
		$this->setIfExists('notes', $data ?? [], null);
		$this->setIfExists('comments', $data ?? [], null);
		$this->setIfExists('approvers', $data ?? [], null);
		$this->setIfExists('actions', $data ?? [], null);
		$this->setIfExists('overlapping_requests', $data ?? [], null);
		$this->setIfExists('policy_type', $data ?? [], null);
		$this->setIfExists('used_year_to_date', $data ?? [], null);
		$this->setIfExists('balance_on_date_of_request', $data ?? [], null);
	}

	/**
	* Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
	* is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
	* $this->openApiNullablesSetToNull array
	*
	* @param string $variableName
	* @param array  $fields
	* @param mixed  $defaultValue
	*/
	private function setIfExists(string $variableName, array $fields, $defaultValue): void {
		if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
			$this->openApiNullablesSetToNull[$variableName] = true;
		}

		$this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
	}

	/**
	 * Show all the invalid properties with reasons.
	 *
	 * @return array invalid properties with reasons
	 */
	public function listInvalidProperties() {
		$invalidProperties = [];

		return $invalidProperties;
	}

	/**
	 * Validate all the properties in the model
	 * return true if all passed
	 *
	 * @return bool True if all properties are valid
	 */
	public function valid() {
		return count($this->listInvalidProperties()) === 0;
	}

	/**
	 * Gets id
	 *
	 * @return int|null
	 */
	public function getId() {
		return $this->container['id'];
	}

	/**
	 * Sets id
	 *
	 * @param int|null $id The newly created time off request ID. Use this to chain follow-up operations such as approving, canceling, or superseding the request.
	 *
	 * @return self
	 */
	public function setId($id) {
		if (is_null($id)) {
			throw new \InvalidArgumentException('non-nullable id cannot be null');
		}
		$this->container['id'] = $id;

		return $this;
	}

	/**
	 * Gets employee_id
	 *
	 * @return int|null
	 */
	public function getEmployeeId() {
		return $this->container['employee_id'];
	}

	/**
	 * Sets employee_id
	 *
	 * @param int|null $employee_id The ID of the employee the request was created for.
	 *
	 * @return self
	 */
	public function setEmployeeId($employee_id) {
		if (is_null($employee_id)) {
			throw new \InvalidArgumentException('non-nullable employee_id cannot be null');
		}
		$this->container['employee_id'] = $employee_id;

		return $this;
	}

	/**
	 * Gets name
	 *
	 * @return string|null
	 */
	public function getName() {
		return $this->container['name'];
	}

	/**
	 * Sets name
	 *
	 * @param string|null $name The employee's full name. Only present when the employee record could be loaded.
	 *
	 * @return self
	 */
	public function setName($name) {
		if (is_null($name)) {
			throw new \InvalidArgumentException('non-nullable name cannot be null');
		}
		$this->container['name'] = $name;

		return $this;
	}

	/**
	 * Gets start
	 *
	 * @return \DateTime|null
	 */
	public function getStart() {
		return $this->container['start'];
	}

	/**
	 * Sets start
	 *
	 * @param \DateTime|null $start The start date of the request in YYYY-MM-DD format.
	 *
	 * @return self
	 */
	public function setStart($start) {
		if (is_null($start)) {
			throw new \InvalidArgumentException('non-nullable start cannot be null');
		}
		$this->container['start'] = $start;

		return $this;
	}

	/**
	 * Gets end
	 *
	 * @return \DateTime|null
	 */
	public function getEnd() {
		return $this->container['end'];
	}

	/**
	 * Sets end
	 *
	 * @param \DateTime|null $end The end date of the request in YYYY-MM-DD format.
	 *
	 * @return self
	 */
	public function setEnd($end) {
		if (is_null($end)) {
			throw new \InvalidArgumentException('non-nullable end cannot be null');
		}
		$this->container['end'] = $end;

		return $this;
	}

	/**
	 * Gets created
	 *
	 * @return \DateTime|null
	 */
	public function getCreated() {
		return $this->container['created'];
	}

	/**
	 * Sets created
	 *
	 * @param \DateTime|null $created The date the request was created in YYYY-MM-DD format (company timezone).
	 *
	 * @return self
	 */
	public function setCreated($created) {
		if (is_null($created)) {
			throw new \InvalidArgumentException('non-nullable created cannot be null');
		}
		$this->container['created'] = $created;

		return $this;
	}

	/**
	 * Gets status
	 *
	 * @return \BhrSdk\Model\CreatedTimeOffRequestStatus|null
	 */
	public function getStatus() {
		return $this->container['status'];
	}

	/**
	 * Sets status
	 *
	 * @param \BhrSdk\Model\CreatedTimeOffRequestStatus|null $status status
	 *
	 * @return self
	 */
	public function setStatus($status) {
		if (is_null($status)) {
			throw new \InvalidArgumentException('non-nullable status cannot be null');
		}
		$this->container['status'] = $status;

		return $this;
	}

	/**
	 * Gets type
	 *
	 * @return \BhrSdk\Model\CreatedTimeOffRequestType|null
	 */
	public function getType() {
		return $this->container['type'];
	}

	/**
	 * Sets type
	 *
	 * @param \BhrSdk\Model\CreatedTimeOffRequestType|null $type type
	 *
	 * @return self
	 */
	public function setType($type) {
		if (is_null($type)) {
			throw new \InvalidArgumentException('non-nullable type cannot be null');
		}
		$this->container['type'] = $type;

		return $this;
	}

	/**
	 * Gets amount
	 *
	 * @return \BhrSdk\Model\CreatedTimeOffRequestAmount|null
	 */
	public function getAmount() {
		return $this->container['amount'];
	}

	/**
	 * Sets amount
	 *
	 * @param \BhrSdk\Model\CreatedTimeOffRequestAmount|null $amount amount
	 *
	 * @return self
	 */
	public function setAmount($amount) {
		if (is_null($amount)) {
			throw new \InvalidArgumentException('non-nullable amount cannot be null');
		}
		$this->container['amount'] = $amount;

		return $this;
	}

	/**
	 * Gets dates
	 *
	 * @return array<string,float>|null
	 */
	public function getDates() {
		return $this->container['dates'];
	}

	/**
	 * Sets dates
	 *
	 * @param array<string,float>|null $dates A map of dates (YYYY-MM-DD) to daily amounts. Only present when daily details were attached to the request.
	 *
	 * @return self
	 */
	public function setDates($dates) {
		if (is_null($dates)) {
			throw new \InvalidArgumentException('non-nullable dates cannot be null');
		}
		$this->container['dates'] = $dates;

		return $this;
	}

	/**
	 * Gets notes
	 *
	 * @return \BhrSdk\Model\CreatedTimeOffRequestNotes|null
	 */
	public function getNotes() {
		return $this->container['notes'];
	}

	/**
	 * Sets notes
	 *
	 * @param \BhrSdk\Model\CreatedTimeOffRequestNotes|null $notes notes
	 *
	 * @return self
	 */
	public function setNotes($notes) {
		if (is_null($notes)) {
			throw new \InvalidArgumentException('non-nullable notes cannot be null');
		}
		$this->container['notes'] = $notes;

		return $this;
	}

	/**
	 * Gets comments
	 *
	 * @return object[]|null
	 */
	public function getComments() {
		return $this->container['comments'];
	}

	/**
	 * Sets comments
	 *
	 * @param object[]|null $comments Comments attached to the request. Always present; empty array when no comments exist.
	 *
	 * @return self
	 */
	public function setComments($comments) {
		if (is_null($comments)) {
			throw new \InvalidArgumentException('non-nullable comments cannot be null');
		}
		$this->container['comments'] = $comments;

		return $this;
	}

	/**
	 * Gets approvers
	 *
	 * @return array[]|null
	 */
	public function getApprovers() {
		return $this->container['approvers'];
	}

	/**
	 * Sets approvers
	 *
	 * @param array[]|null $approvers The approval chain for this request. Only present when the request has approvers.
	 *
	 * @return self
	 */
	public function setApprovers($approvers) {
		if (is_null($approvers)) {
			throw new \InvalidArgumentException('non-nullable approvers cannot be null');
		}
		$this->container['approvers'] = $approvers;

		return $this;
	}

	/**
	 * Gets actions
	 *
	 * @return array<string,bool>|null
	 */
	public function getActions() {
		return $this->container['actions'];
	}

	/**
	 * Sets actions
	 *
	 * @param array<string,bool>|null $actions Actions the current user can perform on this request. Only present when PTO action permissions are available. Keys are restricted to `view`, `edit`, `cancel`, `approve`, `deny`, `bypass`; values are booleans.
	 *
	 * @return self
	 */
	public function setActions($actions) {
		if (is_null($actions)) {
			throw new \InvalidArgumentException('non-nullable actions cannot be null');
		}
		$this->container['actions'] = $actions;

		return $this;
	}

	/**
	 * Gets overlapping_requests
	 *
	 * @return object[]|null
	 */
	public function getOverlappingRequests() {
		return $this->container['overlapping_requests'];
	}

	/**
	 * Sets overlapping_requests
	 *
	 * @param object[]|null $overlapping_requests Other existing time off requests whose date ranges overlap this request. Only present when overlap data was loaded with the request.
	 *
	 * @return self
	 */
	public function setOverlappingRequests($overlapping_requests) {
		if (is_null($overlapping_requests)) {
			throw new \InvalidArgumentException('non-nullable overlapping_requests cannot be null');
		}
		$this->container['overlapping_requests'] = $overlapping_requests;

		return $this;
	}

	/**
	 * Gets policy_type
	 *
	 * @return string|null
	 */
	public function getPolicyType() {
		return $this->container['policy_type'];
	}

	/**
	 * Sets policy_type
	 *
	 * @param string|null $policy_type The policy type backing this request (e.g. accruing, manual, unlimited).
	 *
	 * @return self
	 */
	public function setPolicyType($policy_type) {
		if (is_null($policy_type)) {
			throw new \InvalidArgumentException('non-nullable policy_type cannot be null');
		}
		$this->container['policy_type'] = $policy_type;

		return $this;
	}

	/**
	 * Gets used_year_to_date
	 *
	 * @return float|null
	 */
	public function getUsedYearToDate() {
		return $this->container['used_year_to_date'];
	}

	/**
	 * Sets used_year_to_date
	 *
	 * @param float|null $used_year_to_date used_year_to_date
	 *
	 * @return self
	 */
	public function setUsedYearToDate($used_year_to_date) {
		if (is_null($used_year_to_date)) {
			$this->openApiNullablesSetToNull['used_year_to_date'] = true;
		} else {
			$nullablesSetToNull = $this->getOpenApiNullablesSetToNull();
			if (isset($nullablesSetToNull['used_year_to_date'])) {
				unset($nullablesSetToNull['used_year_to_date']);
				$this->setOpenApiNullablesSetToNull($nullablesSetToNull);
			}
		}
		$this->container['used_year_to_date'] = $used_year_to_date;

		return $this;
	}

	/**
	 * Gets balance_on_date_of_request
	 *
	 * @return float|null
	 */
	public function getBalanceOnDateOfRequest() {
		return $this->container['balance_on_date_of_request'];
	}

	/**
	 * Sets balance_on_date_of_request
	 *
	 * @param float|null $balance_on_date_of_request balance_on_date_of_request
	 *
	 * @return self
	 */
	public function setBalanceOnDateOfRequest($balance_on_date_of_request) {
		if (is_null($balance_on_date_of_request)) {
			$this->openApiNullablesSetToNull['balance_on_date_of_request'] = true;
		} else {
			$nullablesSetToNull = $this->getOpenApiNullablesSetToNull();
			if (isset($nullablesSetToNull['balance_on_date_of_request'])) {
				unset($nullablesSetToNull['balance_on_date_of_request']);
				$this->setOpenApiNullablesSetToNull($nullablesSetToNull);
			}
		}
		$this->container['balance_on_date_of_request'] = $balance_on_date_of_request;

		return $this;
	}
	/**
	 * Returns true if offset exists. False otherwise.
	 *
	 * @param string $offset Offset
	 *
	 * @return boolean
	 */
	public function offsetExists($offset): bool {
		return isset($this->container[$offset]);
	}

	/**
	 * Gets offset.
	 *
	 * @param string $offset Offset
	 *
	 * @return mixed|null
	 */
	#[\ReturnTypeWillChange]
	public function offsetGet($offset) {
		return $this->container[$offset] ?? null;
	}

	/**
	 * Sets value based on offset.
	 *
	 * @param string|null $offset Offset
	 * @param mixed    $value  Value to be set
	 *
	 * @return void
	 */
	public function offsetSet($offset, $value): void {
		if (is_null($offset)) {
			$this->container[] = $value;
		} else {
			$this->container[$offset] = $value;
		}
	}

	/**
	 * Unsets offset.
	 *
	 * @param string $offset Offset
	 *
	 * @return void
	 */
	public function offsetUnset($offset): void {
		unset($this->container[$offset]);
	}

	/**
	 * Serializes the object to a value that can be serialized natively by json_encode().
	 * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
	 *
	 * @return mixed Returns data which can be serialized by json_encode(), which is a value
	 * of any type other than a resource.
	 */
	#[\ReturnTypeWillChange]
	public function jsonSerialize() {
	   return ObjectSerializer::sanitizeForSerialization($this);
	}

	/**
	 * Gets the string presentation of the object
	 *
	 * @return string
	 */
	public function __toString(): string {
		$jsonEncoded = json_encode(
			ObjectSerializer::sanitizeForSerialization($this),
			JSON_PRETTY_PRINT
		);
		return $jsonEncoded === false ? '{}' : $jsonEncoded;
	}

	/**
	 * Gets a header-safe presentation of the object
	 *
	 * @return string
	 */
	public function toHeaderValue(): string {
		$jsonEncoded = json_encode(ObjectSerializer::sanitizeForSerialization($this));
		return $jsonEncoded === false ? '{}' : $jsonEncoded;
	}
}

