<?php
declare(strict_types=1);
/**
 * EmployeeVerificationPublicApiRecord
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  BhrSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BambooHR API
 *
 * BambooHR API documentation. https://www.bamboohr.com/api/documentation/
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace BhrSdk\Model;

use \ArrayAccess;
use \BhrSdk\ObjectSerializer;

/**
 * EmployeeVerificationPublicApiRecord Class Doc Comment
 *
 * @category Class
 * @description A single employee verification row as returned by the public list API.
 * @package  BhrSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class EmployeeVerificationPublicApiRecord implements ModelInterface, ArrayAccess, \JsonSerializable {
	public const DISCRIMINATOR = null;

	/**
	  * The original name of the model.
	  *
	  * @var string
	  */
	protected static $openApiModelName = 'EmployeeVerificationPublicApiRecord';

	/**
	  * Array of property to type mappings. Used for (de)serialization
	  *
	  * @var string[]
	  */
	protected static $openApiTypes = [
		'id' => 'int',
		'employee_id' => 'int',
		'integration_type' => 'string',
		'verification_type' => 'string',
		'verification_status' => 'string',
		'verification_status_notes' => 'string',
		'remote_access_url' => 'string',
		'e_verify_status' => 'string',
		'archived' => 'bool',
		'billing_processed' => 'bool',
		'created_by_user_id' => 'int',
		'created_ymdt' => 'string',
		'last_modified_ymdt' => 'string',
		'start_date_ymdt' => 'string'
	];

	/**
	  * Array of property to format mappings. Used for (de)serialization
	  *
	  * @var string[]
	  * @phpstan-var array<string, string|null>
	  * @psalm-var array<string, string|null>
	  */
	protected static $openApiFormats = [
		'id' => 'int64',
		'employee_id' => 'int64',
		'integration_type' => null,
		'verification_type' => null,
		'verification_status' => null,
		'verification_status_notes' => null,
		'remote_access_url' => null,
		'e_verify_status' => null,
		'archived' => null,
		'billing_processed' => null,
		'created_by_user_id' => 'int64',
		'created_ymdt' => null,
		'last_modified_ymdt' => null,
		'start_date_ymdt' => null
	];

	/**
	  * Array of nullable properties. Used for (de)serialization
	  *
	  * @var bool[]
	  * @phpstan-var array<string, bool>
	  */
	protected static array $openApiNullables = [
		'id' => false,
		'employee_id' => true,
		'integration_type' => false,
		'verification_type' => false,
		'verification_status' => true,
		'verification_status_notes' => true,
		'remote_access_url' => true,
		'e_verify_status' => true,
		'archived' => false,
		'billing_processed' => false,
		'created_by_user_id' => false,
		'created_ymdt' => false,
		'last_modified_ymdt' => false,
		'start_date_ymdt' => false
	];

	/**
	  * If a nullable field gets set to null, insert it here
	  *
	  * @var bool[]
	  * @phpstan-var array<string, bool>
	  */
	protected array $openApiNullablesSetToNull = [];

	/**
	 * Array of property to type mappings. Used for (de)serialization
	 *
	 * @return array
	 */
	public static function openApiTypes() {
		return self::$openApiTypes;
	}

	/**
	 * Array of property to format mappings. Used for (de)serialization
	 *
	 * @return array
	 */
	public static function openApiFormats() {
		return self::$openApiFormats;
	}

	/**
	 * Array of nullable properties
	 *
	 * @return array
	 */
	protected static function openApiNullables(): array {
		return self::$openApiNullables;
	}

	/**
	 * Array of nullable field names deliberately set to null
	 *
	 * @return bool[]
	 * @phpstan-return array<string, bool>
	 */
	private function getOpenApiNullablesSetToNull(): array {
		return $this->openApiNullablesSetToNull;
	}

	/**
	 * Setter - Array of nullable field names deliberately set to null
	 *
	 * @param bool[] $openApiNullablesSetToNull
	 * @phpstan-param array<string, bool> $openApiNullablesSetToNull
	 */
	private function setOpenApiNullablesSetToNull(array $openApiNullablesSetToNull): void {
		$this->openApiNullablesSetToNull = $openApiNullablesSetToNull;
	}

	/**
	 * Checks if a property is nullable
	 *
	 * @param string $property
	 * @return bool
	 */
	public static function isNullable(string $property): bool {
		return self::openApiNullables()[$property] ?? false;
	}

	/**
	 * Checks if a nullable property is set to null.
	 *
	 * @param string $property
	 * @return bool
	 */
	public function isNullableSetToNull(string $property): bool {
		return isset($this->getOpenApiNullablesSetToNull()[$property]);
	}

	/**
	 * Array of attributes where the key is the local name,
	 * and the value is the original name
	 *
	 * @var string[]
	 */
	protected static $attributeMap = [
		'id' => 'id',
		'employee_id' => 'employeeId',
		'integration_type' => 'integrationType',
		'verification_type' => 'verificationType',
		'verification_status' => 'verificationStatus',
		'verification_status_notes' => 'verificationStatusNotes',
		'remote_access_url' => 'remoteAccessUrl',
		'e_verify_status' => 'eVerifyStatus',
		'archived' => 'archived',
		'billing_processed' => 'billingProcessed',
		'created_by_user_id' => 'createdByUserId',
		'created_ymdt' => 'createdYmdt',
		'last_modified_ymdt' => 'lastModifiedYmdt',
		'start_date_ymdt' => 'startDateYmdt'
	];

	/**
	 * Array of attributes to setter functions (for deserialization of responses)
	 *
	 * @var string[]
	 */
	protected static $setters = [
		'id' => 'setId',
		'employee_id' => 'setEmployeeId',
		'integration_type' => 'setIntegrationType',
		'verification_type' => 'setVerificationType',
		'verification_status' => 'setVerificationStatus',
		'verification_status_notes' => 'setVerificationStatusNotes',
		'remote_access_url' => 'setRemoteAccessUrl',
		'e_verify_status' => 'setEVerifyStatus',
		'archived' => 'setArchived',
		'billing_processed' => 'setBillingProcessed',
		'created_by_user_id' => 'setCreatedByUserId',
		'created_ymdt' => 'setCreatedYmdt',
		'last_modified_ymdt' => 'setLastModifiedYmdt',
		'start_date_ymdt' => 'setStartDateYmdt'
	];

	/**
	 * Array of attributes to getter functions (for serialization of requests)
	 *
	 * @var string[]
	 */
	protected static $getters = [
		'id' => 'getId',
		'employee_id' => 'getEmployeeId',
		'integration_type' => 'getIntegrationType',
		'verification_type' => 'getVerificationType',
		'verification_status' => 'getVerificationStatus',
		'verification_status_notes' => 'getVerificationStatusNotes',
		'remote_access_url' => 'getRemoteAccessUrl',
		'e_verify_status' => 'getEVerifyStatus',
		'archived' => 'getArchived',
		'billing_processed' => 'getBillingProcessed',
		'created_by_user_id' => 'getCreatedByUserId',
		'created_ymdt' => 'getCreatedYmdt',
		'last_modified_ymdt' => 'getLastModifiedYmdt',
		'start_date_ymdt' => 'getStartDateYmdt'
	];

	/**
	 * Array of attributes where the key is the local name,
	 * and the value is the original name
	 *
	 * @return array
	 */
	public static function attributeMap() {
		return self::$attributeMap;
	}

	/**
	 * Array of attributes to setter functions (for deserialization of responses)
	 *
	 * @return array
	 */
	public static function setters() {
		return self::$setters;
	}

	/**
	 * Array of attributes to getter functions (for serialization of requests)
	 *
	 * @return array
	 */
	public static function getters() {
		return self::$getters;
	}

	/**
	 * The original name of the model.
	 *
	 * @return string
	 */
	public function getModelName() {
		return self::$openApiModelName;
	}

	/**
	 * Associative array for storing property values
	 *
	 * @var mixed[]
	 */
	protected $container = [];

	/**
	 * Constructor
	 *
	 * @param mixed[]|null $data Associated array of property values
	 *                           initializing the model
	 */
	public function __construct(?array $data = null) {
		$this->setIfExists('id', $data ?? [], null);
		$this->setIfExists('employee_id', $data ?? [], null);
		$this->setIfExists('integration_type', $data ?? [], null);
		$this->setIfExists('verification_type', $data ?? [], null);
		$this->setIfExists('verification_status', $data ?? [], null);
		$this->setIfExists('verification_status_notes', $data ?? [], null);
		$this->setIfExists('remote_access_url', $data ?? [], null);
		$this->setIfExists('e_verify_status', $data ?? [], null);
		$this->setIfExists('archived', $data ?? [], null);
		$this->setIfExists('billing_processed', $data ?? [], null);
		$this->setIfExists('created_by_user_id', $data ?? [], null);
		$this->setIfExists('created_ymdt', $data ?? [], null);
		$this->setIfExists('last_modified_ymdt', $data ?? [], null);
		$this->setIfExists('start_date_ymdt', $data ?? [], null);
	}

	/**
	* Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
	* is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
	* $this->openApiNullablesSetToNull array
	*
	* @param string $variableName
	* @param array  $fields
	* @param mixed  $defaultValue
	*/
	private function setIfExists(string $variableName, array $fields, $defaultValue): void {
		if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
			$this->openApiNullablesSetToNull[$variableName] = true;
		}

		$this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
	}

	/**
	 * Show all the invalid properties with reasons.
	 *
	 * @return array invalid properties with reasons
	 */
	public function listInvalidProperties() {
		$invalidProperties = [];

		return $invalidProperties;
	}

	/**
	 * Validate all the properties in the model
	 * return true if all passed
	 *
	 * @return bool True if all properties are valid
	 */
	public function valid() {
		return count($this->listInvalidProperties()) === 0;
	}

	/**
	 * Gets id
	 *
	 * @return int|null
	 */
	public function getId() {
		return $this->container['id'];
	}

	/**
	 * Sets id
	 *
	 * @param int|null $id id
	 *
	 * @return self
	 */
	public function setId($id) {
		if (is_null($id)) {
			throw new \InvalidArgumentException('non-nullable id cannot be null');
		}
		$this->container['id'] = $id;

		return $this;
	}

	/**
	 * Gets employee_id
	 *
	 * @return int|null
	 */
	public function getEmployeeId() {
		return $this->container['employee_id'];
	}

	/**
	 * Sets employee_id
	 *
	 * @param int|null $employee_id employee_id
	 *
	 * @return self
	 */
	public function setEmployeeId($employee_id) {
		if (is_null($employee_id)) {
			$this->openApiNullablesSetToNull['employee_id'] = true;
		} else {
			$nullablesSetToNull = $this->getOpenApiNullablesSetToNull();
			if (isset($nullablesSetToNull['employee_id'])) {
				unset($nullablesSetToNull['employee_id']);
				$this->setOpenApiNullablesSetToNull($nullablesSetToNull);
			}
		}
		$this->container['employee_id'] = $employee_id;

		return $this;
	}

	/**
	 * Gets integration_type
	 *
	 * @return string|null
	 */
	public function getIntegrationType() {
		return $this->container['integration_type'];
	}

	/**
	 * Sets integration_type
	 *
	 * @param string|null $integration_type integration_type
	 *
	 * @return self
	 */
	public function setIntegrationType($integration_type) {
		if (is_null($integration_type)) {
			throw new \InvalidArgumentException('non-nullable integration_type cannot be null');
		}
		$this->container['integration_type'] = $integration_type;

		return $this;
	}

	/**
	 * Gets verification_type
	 *
	 * @return string|null
	 */
	public function getVerificationType() {
		return $this->container['verification_type'];
	}

	/**
	 * Sets verification_type
	 *
	 * @param string|null $verification_type verification_type
	 *
	 * @return self
	 */
	public function setVerificationType($verification_type) {
		if (is_null($verification_type)) {
			throw new \InvalidArgumentException('non-nullable verification_type cannot be null');
		}
		$this->container['verification_type'] = $verification_type;

		return $this;
	}

	/**
	 * Gets verification_status
	 *
	 * @return string|null
	 */
	public function getVerificationStatus() {
		return $this->container['verification_status'];
	}

	/**
	 * Sets verification_status
	 *
	 * @param string|null $verification_status verification_status
	 *
	 * @return self
	 */
	public function setVerificationStatus($verification_status) {
		if (is_null($verification_status)) {
			$this->openApiNullablesSetToNull['verification_status'] = true;
		} else {
			$nullablesSetToNull = $this->getOpenApiNullablesSetToNull();
			if (isset($nullablesSetToNull['verification_status'])) {
				unset($nullablesSetToNull['verification_status']);
				$this->setOpenApiNullablesSetToNull($nullablesSetToNull);
			}
		}
		$this->container['verification_status'] = $verification_status;

		return $this;
	}

	/**
	 * Gets verification_status_notes
	 *
	 * @return string|null
	 */
	public function getVerificationStatusNotes() {
		return $this->container['verification_status_notes'];
	}

	/**
	 * Sets verification_status_notes
	 *
	 * @param string|null $verification_status_notes verification_status_notes
	 *
	 * @return self
	 */
	public function setVerificationStatusNotes($verification_status_notes) {
		if (is_null($verification_status_notes)) {
			$this->openApiNullablesSetToNull['verification_status_notes'] = true;
		} else {
			$nullablesSetToNull = $this->getOpenApiNullablesSetToNull();
			if (isset($nullablesSetToNull['verification_status_notes'])) {
				unset($nullablesSetToNull['verification_status_notes']);
				$this->setOpenApiNullablesSetToNull($nullablesSetToNull);
			}
		}
		$this->container['verification_status_notes'] = $verification_status_notes;

		return $this;
	}

	/**
	 * Gets remote_access_url
	 *
	 * @return string|null
	 */
	public function getRemoteAccessUrl() {
		return $this->container['remote_access_url'];
	}

	/**
	 * Sets remote_access_url
	 *
	 * @param string|null $remote_access_url remote_access_url
	 *
	 * @return self
	 */
	public function setRemoteAccessUrl($remote_access_url) {
		if (is_null($remote_access_url)) {
			$this->openApiNullablesSetToNull['remote_access_url'] = true;
		} else {
			$nullablesSetToNull = $this->getOpenApiNullablesSetToNull();
			if (isset($nullablesSetToNull['remote_access_url'])) {
				unset($nullablesSetToNull['remote_access_url']);
				$this->setOpenApiNullablesSetToNull($nullablesSetToNull);
			}
		}
		$this->container['remote_access_url'] = $remote_access_url;

		return $this;
	}

	/**
	 * Gets e_verify_status
	 *
	 * @return string|null
	 */
	public function getEVerifyStatus() {
		return $this->container['e_verify_status'];
	}

	/**
	 * Sets e_verify_status
	 *
	 * @param string|null $e_verify_status e_verify_status
	 *
	 * @return self
	 */
	public function setEVerifyStatus($e_verify_status) {
		if (is_null($e_verify_status)) {
			$this->openApiNullablesSetToNull['e_verify_status'] = true;
		} else {
			$nullablesSetToNull = $this->getOpenApiNullablesSetToNull();
			if (isset($nullablesSetToNull['e_verify_status'])) {
				unset($nullablesSetToNull['e_verify_status']);
				$this->setOpenApiNullablesSetToNull($nullablesSetToNull);
			}
		}
		$this->container['e_verify_status'] = $e_verify_status;

		return $this;
	}

	/**
	 * Gets archived
	 *
	 * @return bool|null
	 */
	public function getArchived() {
		return $this->container['archived'];
	}

	/**
	 * Sets archived
	 *
	 * @param bool|null $archived archived
	 *
	 * @return self
	 */
	public function setArchived($archived) {
		if (is_null($archived)) {
			throw new \InvalidArgumentException('non-nullable archived cannot be null');
		}
		$this->container['archived'] = $archived;

		return $this;
	}

	/**
	 * Gets billing_processed
	 *
	 * @return bool|null
	 */
	public function getBillingProcessed() {
		return $this->container['billing_processed'];
	}

	/**
	 * Sets billing_processed
	 *
	 * @param bool|null $billing_processed billing_processed
	 *
	 * @return self
	 */
	public function setBillingProcessed($billing_processed) {
		if (is_null($billing_processed)) {
			throw new \InvalidArgumentException('non-nullable billing_processed cannot be null');
		}
		$this->container['billing_processed'] = $billing_processed;

		return $this;
	}

	/**
	 * Gets created_by_user_id
	 *
	 * @return int|null
	 */
	public function getCreatedByUserId() {
		return $this->container['created_by_user_id'];
	}

	/**
	 * Sets created_by_user_id
	 *
	 * @param int|null $created_by_user_id created_by_user_id
	 *
	 * @return self
	 */
	public function setCreatedByUserId($created_by_user_id) {
		if (is_null($created_by_user_id)) {
			throw new \InvalidArgumentException('non-nullable created_by_user_id cannot be null');
		}
		$this->container['created_by_user_id'] = $created_by_user_id;

		return $this;
	}

	/**
	 * Gets created_ymdt
	 *
	 * @return string|null
	 */
	public function getCreatedYmdt() {
		return $this->container['created_ymdt'];
	}

	/**
	 * Sets created_ymdt
	 *
	 * @param string|null $created_ymdt Creation timestamp (company DB format).
	 *
	 * @return self
	 */
	public function setCreatedYmdt($created_ymdt) {
		if (is_null($created_ymdt)) {
			throw new \InvalidArgumentException('non-nullable created_ymdt cannot be null');
		}
		$this->container['created_ymdt'] = $created_ymdt;

		return $this;
	}

	/**
	 * Gets last_modified_ymdt
	 *
	 * @return string|null
	 */
	public function getLastModifiedYmdt() {
		return $this->container['last_modified_ymdt'];
	}

	/**
	 * Sets last_modified_ymdt
	 *
	 * @param string|null $last_modified_ymdt Last modified timestamp (company DB format).
	 *
	 * @return self
	 */
	public function setLastModifiedYmdt($last_modified_ymdt) {
		if (is_null($last_modified_ymdt)) {
			throw new \InvalidArgumentException('non-nullable last_modified_ymdt cannot be null');
		}
		$this->container['last_modified_ymdt'] = $last_modified_ymdt;

		return $this;
	}

	/**
	 * Gets start_date_ymdt
	 *
	 * @return string|null
	 */
	public function getStartDateYmdt() {
		return $this->container['start_date_ymdt'];
	}

	/**
	 * Sets start_date_ymdt
	 *
	 * @param string|null $start_date_ymdt start_date_ymdt
	 *
	 * @return self
	 */
	public function setStartDateYmdt($start_date_ymdt) {
		if (is_null($start_date_ymdt)) {
			throw new \InvalidArgumentException('non-nullable start_date_ymdt cannot be null');
		}
		$this->container['start_date_ymdt'] = $start_date_ymdt;

		return $this;
	}
	/**
	 * Returns true if offset exists. False otherwise.
	 *
	 * @param string $offset Offset
	 *
	 * @return boolean
	 */
	public function offsetExists($offset): bool {
		return isset($this->container[$offset]);
	}

	/**
	 * Gets offset.
	 *
	 * @param string $offset Offset
	 *
	 * @return mixed|null
	 */
	#[\ReturnTypeWillChange]
	public function offsetGet($offset) {
		return $this->container[$offset] ?? null;
	}

	/**
	 * Sets value based on offset.
	 *
	 * @param string|null $offset Offset
	 * @param mixed    $value  Value to be set
	 *
	 * @return void
	 */
	public function offsetSet($offset, $value): void {
		if (is_null($offset)) {
			$this->container[] = $value;
		} else {
			$this->container[$offset] = $value;
		}
	}

	/**
	 * Unsets offset.
	 *
	 * @param string $offset Offset
	 *
	 * @return void
	 */
	public function offsetUnset($offset): void {
		unset($this->container[$offset]);
	}

	/**
	 * Serializes the object to a value that can be serialized natively by json_encode().
	 * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
	 *
	 * @return mixed Returns data which can be serialized by json_encode(), which is a value
	 * of any type other than a resource.
	 */
	#[\ReturnTypeWillChange]
	public function jsonSerialize() {
	   return ObjectSerializer::sanitizeForSerialization($this);
	}

	/**
	 * Gets the string presentation of the object
	 *
	 * @return string
	 */
	public function __toString(): string {
		$jsonEncoded = json_encode(
			ObjectSerializer::sanitizeForSerialization($this),
			JSON_PRETTY_PRINT
		);
		return $jsonEncoded === false ? '{}' : $jsonEncoded;
	}

	/**
	 * Gets a header-safe presentation of the object
	 *
	 * @return string
	 */
	public function toHeaderValue(): string {
		$jsonEncoded = json_encode(ObjectSerializer::sanitizeForSerialization($this));
		return $jsonEncoded === false ? '{}' : $jsonEncoded;
	}
}

