<?php
/**
 * TimeOffPolicySettingsTransformerAccrualOptions
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  MySdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BambooHR API
 *
 * BambooHR API documentation. https://www.bamboohr.com/api/documentation/
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MySdk\Model;

use \ArrayAccess;
use \MySdk\ObjectSerializer;

/**
 * TimeOffPolicySettingsTransformerAccrualOptions Class Doc Comment
 *
 * @category Class
 * @package  MySdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TimeOffPolicySettingsTransformerAccrualOptions implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'TimeOffPolicySettingsTransformer_accrualOptions';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'carry_over_select_option' => 'string',
        'carry_over_month' => 'string',
        'carry_over_day' => 'string',
        'carry_over_expiration' => 'string',
        'preaccrue' => 'string',
        'reset_negative_balances' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'carry_over_select_option' => null,
        'carry_over_month' => null,
        'carry_over_day' => null,
        'carry_over_expiration' => null,
        'preaccrue' => null,
        'reset_negative_balances' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'carry_over_select_option' => false,
        'carry_over_month' => false,
        'carry_over_day' => false,
        'carry_over_expiration' => false,
        'preaccrue' => false,
        'reset_negative_balances' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'carry_over_select_option' => 'carryOverSelectOption',
        'carry_over_month' => 'carryOverMonth',
        'carry_over_day' => 'carryOverDay',
        'carry_over_expiration' => 'carryOverExpiration',
        'preaccrue' => 'preaccrue',
        'reset_negative_balances' => 'resetNegativeBalances'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'carry_over_select_option' => 'setCarryOverSelectOption',
        'carry_over_month' => 'setCarryOverMonth',
        'carry_over_day' => 'setCarryOverDay',
        'carry_over_expiration' => 'setCarryOverExpiration',
        'preaccrue' => 'setPreaccrue',
        'reset_negative_balances' => 'setResetNegativeBalances'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'carry_over_select_option' => 'getCarryOverSelectOption',
        'carry_over_month' => 'getCarryOverMonth',
        'carry_over_day' => 'getCarryOverDay',
        'carry_over_expiration' => 'getCarryOverExpiration',
        'preaccrue' => 'getPreaccrue',
        'reset_negative_balances' => 'getResetNegativeBalances'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('carry_over_select_option', $data ?? [], null);
        $this->setIfExists('carry_over_month', $data ?? [], null);
        $this->setIfExists('carry_over_day', $data ?? [], null);
        $this->setIfExists('carry_over_expiration', $data ?? [], null);
        $this->setIfExists('preaccrue', $data ?? [], null);
        $this->setIfExists('reset_negative_balances', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets carry_over_select_option
     *
     * @return string|null
     */
    public function getCarryOverSelectOption()
    {
        return $this->container['carry_over_select_option'];
    }

    /**
     * Sets carry_over_select_option
     *
     * @param string|null $carry_over_select_option carry_over_select_option
     *
     * @return self
     */
    public function setCarryOverSelectOption($carry_over_select_option)
    {
        if (is_null($carry_over_select_option)) {
            throw new \InvalidArgumentException('non-nullable carry_over_select_option cannot be null');
        }
        $this->container['carry_over_select_option'] = $carry_over_select_option;

        return $this;
    }

    /**
     * Gets carry_over_month
     *
     * @return string|null
     */
    public function getCarryOverMonth()
    {
        return $this->container['carry_over_month'];
    }

    /**
     * Sets carry_over_month
     *
     * @param string|null $carry_over_month carry_over_month
     *
     * @return self
     */
    public function setCarryOverMonth($carry_over_month)
    {
        if (is_null($carry_over_month)) {
            throw new \InvalidArgumentException('non-nullable carry_over_month cannot be null');
        }
        $this->container['carry_over_month'] = $carry_over_month;

        return $this;
    }

    /**
     * Gets carry_over_day
     *
     * @return string|null
     */
    public function getCarryOverDay()
    {
        return $this->container['carry_over_day'];
    }

    /**
     * Sets carry_over_day
     *
     * @param string|null $carry_over_day carry_over_day
     *
     * @return self
     */
    public function setCarryOverDay($carry_over_day)
    {
        if (is_null($carry_over_day)) {
            throw new \InvalidArgumentException('non-nullable carry_over_day cannot be null');
        }
        $this->container['carry_over_day'] = $carry_over_day;

        return $this;
    }

    /**
     * Gets carry_over_expiration
     *
     * @return string|null
     */
    public function getCarryOverExpiration()
    {
        return $this->container['carry_over_expiration'];
    }

    /**
     * Sets carry_over_expiration
     *
     * @param string|null $carry_over_expiration carry_over_expiration
     *
     * @return self
     */
    public function setCarryOverExpiration($carry_over_expiration)
    {
        if (is_null($carry_over_expiration)) {
            throw new \InvalidArgumentException('non-nullable carry_over_expiration cannot be null');
        }
        $this->container['carry_over_expiration'] = $carry_over_expiration;

        return $this;
    }

    /**
     * Gets preaccrue
     *
     * @return string|null
     */
    public function getPreaccrue()
    {
        return $this->container['preaccrue'];
    }

    /**
     * Sets preaccrue
     *
     * @param string|null $preaccrue preaccrue
     *
     * @return self
     */
    public function setPreaccrue($preaccrue)
    {
        if (is_null($preaccrue)) {
            throw new \InvalidArgumentException('non-nullable preaccrue cannot be null');
        }
        $this->container['preaccrue'] = $preaccrue;

        return $this;
    }

    /**
     * Gets reset_negative_balances
     *
     * @return string|null
     */
    public function getResetNegativeBalances()
    {
        return $this->container['reset_negative_balances'];
    }

    /**
     * Sets reset_negative_balances
     *
     * @param string|null $reset_negative_balances reset_negative_balances
     *
     * @return self
     */
    public function setResetNegativeBalances($reset_negative_balances)
    {
        if (is_null($reset_negative_balances)) {
            throw new \InvalidArgumentException('non-nullable reset_negative_balances cannot be null');
        }
        $this->container['reset_negative_balances'] = $reset_negative_balances;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


