<?php
/**
 * TimeTrackingProjectDataObject
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  MySdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BambooHR API
 *
 * BambooHR API documentation. https://www.bamboohr.com/api/documentation/
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MySdk\Model;

use \ArrayAccess;
use \MySdk\ObjectSerializer;

/**
 * TimeTrackingProjectDataObject Class Doc Comment
 *
 * @category Class
 * @package  MySdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TimeTrackingProjectDataObject implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'TimeTrackingProjectDataObject';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'int',
        'name' => 'string',
        'allow_all_employees' => 'bool',
        'has_tasks' => 'bool',
        'archived' => 'bool',
        'billable' => 'bool',
        'include_in_payroll' => 'bool',
        'created_ymdt' => 'string',
        'deleted_ymdt' => 'string',
        'deleted_by_user_id' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'name' => null,
        'allow_all_employees' => null,
        'has_tasks' => null,
        'archived' => null,
        'billable' => null,
        'include_in_payroll' => null,
        'created_ymdt' => null,
        'deleted_ymdt' => null,
        'deleted_by_user_id' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'name' => false,
        'allow_all_employees' => false,
        'has_tasks' => false,
        'archived' => false,
        'billable' => false,
        'include_in_payroll' => false,
        'created_ymdt' => false,
        'deleted_ymdt' => false,
        'deleted_by_user_id' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'name' => 'name',
        'allow_all_employees' => 'allowAllEmployees',
        'has_tasks' => 'hasTasks',
        'archived' => 'archived',
        'billable' => 'billable',
        'include_in_payroll' => 'includeInPayroll',
        'created_ymdt' => 'createdYmdt',
        'deleted_ymdt' => 'deletedYmdt',
        'deleted_by_user_id' => 'deletedByUserId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'name' => 'setName',
        'allow_all_employees' => 'setAllowAllEmployees',
        'has_tasks' => 'setHasTasks',
        'archived' => 'setArchived',
        'billable' => 'setBillable',
        'include_in_payroll' => 'setIncludeInPayroll',
        'created_ymdt' => 'setCreatedYmdt',
        'deleted_ymdt' => 'setDeletedYmdt',
        'deleted_by_user_id' => 'setDeletedByUserId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'name' => 'getName',
        'allow_all_employees' => 'getAllowAllEmployees',
        'has_tasks' => 'getHasTasks',
        'archived' => 'getArchived',
        'billable' => 'getBillable',
        'include_in_payroll' => 'getIncludeInPayroll',
        'created_ymdt' => 'getCreatedYmdt',
        'deleted_ymdt' => 'getDeletedYmdt',
        'deleted_by_user_id' => 'getDeletedByUserId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('allow_all_employees', $data ?? [], null);
        $this->setIfExists('has_tasks', $data ?? [], null);
        $this->setIfExists('archived', $data ?? [], null);
        $this->setIfExists('billable', $data ?? [], null);
        $this->setIfExists('include_in_payroll', $data ?? [], null);
        $this->setIfExists('created_ymdt', $data ?? [], null);
        $this->setIfExists('deleted_ymdt', $data ?? [], null);
        $this->setIfExists('deleted_by_user_id', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int|null $id Class TimeTrackingProject
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets allow_all_employees
     *
     * @return bool|null
     */
    public function getAllowAllEmployees()
    {
        return $this->container['allow_all_employees'];
    }

    /**
     * Sets allow_all_employees
     *
     * @param bool|null $allow_all_employees allow_all_employees
     *
     * @return self
     */
    public function setAllowAllEmployees($allow_all_employees)
    {
        if (is_null($allow_all_employees)) {
            throw new \InvalidArgumentException('non-nullable allow_all_employees cannot be null');
        }
        $this->container['allow_all_employees'] = $allow_all_employees;

        return $this;
    }

    /**
     * Gets has_tasks
     *
     * @return bool|null
     */
    public function getHasTasks()
    {
        return $this->container['has_tasks'];
    }

    /**
     * Sets has_tasks
     *
     * @param bool|null $has_tasks has_tasks
     *
     * @return self
     */
    public function setHasTasks($has_tasks)
    {
        if (is_null($has_tasks)) {
            throw new \InvalidArgumentException('non-nullable has_tasks cannot be null');
        }
        $this->container['has_tasks'] = $has_tasks;

        return $this;
    }

    /**
     * Gets archived
     *
     * @return bool|null
     */
    public function getArchived()
    {
        return $this->container['archived'];
    }

    /**
     * Sets archived
     *
     * @param bool|null $archived archived
     *
     * @return self
     */
    public function setArchived($archived)
    {
        if (is_null($archived)) {
            throw new \InvalidArgumentException('non-nullable archived cannot be null');
        }
        $this->container['archived'] = $archived;

        return $this;
    }

    /**
     * Gets billable
     *
     * @return bool|null
     */
    public function getBillable()
    {
        return $this->container['billable'];
    }

    /**
     * Sets billable
     *
     * @param bool|null $billable billable
     *
     * @return self
     */
    public function setBillable($billable)
    {
        if (is_null($billable)) {
            throw new \InvalidArgumentException('non-nullable billable cannot be null');
        }
        $this->container['billable'] = $billable;

        return $this;
    }

    /**
     * Gets include_in_payroll
     *
     * @return bool|null
     */
    public function getIncludeInPayroll()
    {
        return $this->container['include_in_payroll'];
    }

    /**
     * Sets include_in_payroll
     *
     * @param bool|null $include_in_payroll include_in_payroll
     *
     * @return self
     */
    public function setIncludeInPayroll($include_in_payroll)
    {
        if (is_null($include_in_payroll)) {
            throw new \InvalidArgumentException('non-nullable include_in_payroll cannot be null');
        }
        $this->container['include_in_payroll'] = $include_in_payroll;

        return $this;
    }

    /**
     * Gets created_ymdt
     *
     * @return string|null
     */
    public function getCreatedYmdt()
    {
        return $this->container['created_ymdt'];
    }

    /**
     * Sets created_ymdt
     *
     * @param string|null $created_ymdt created_ymdt
     *
     * @return self
     */
    public function setCreatedYmdt($created_ymdt)
    {
        if (is_null($created_ymdt)) {
            throw new \InvalidArgumentException('non-nullable created_ymdt cannot be null');
        }
        $this->container['created_ymdt'] = $created_ymdt;

        return $this;
    }

    /**
     * Gets deleted_ymdt
     *
     * @return string|null
     */
    public function getDeletedYmdt()
    {
        return $this->container['deleted_ymdt'];
    }

    /**
     * Sets deleted_ymdt
     *
     * @param string|null $deleted_ymdt deleted_ymdt
     *
     * @return self
     */
    public function setDeletedYmdt($deleted_ymdt)
    {
        if (is_null($deleted_ymdt)) {
            throw new \InvalidArgumentException('non-nullable deleted_ymdt cannot be null');
        }
        $this->container['deleted_ymdt'] = $deleted_ymdt;

        return $this;
    }

    /**
     * Gets deleted_by_user_id
     *
     * @return int|null
     */
    public function getDeletedByUserId()
    {
        return $this->container['deleted_by_user_id'];
    }

    /**
     * Sets deleted_by_user_id
     *
     * @param int|null $deleted_by_user_id deleted_by_user_id
     *
     * @return self
     */
    public function setDeletedByUserId($deleted_by_user_id)
    {
        if (is_null($deleted_by_user_id)) {
            throw new \InvalidArgumentException('non-nullable deleted_by_user_id cannot be null');
        }
        $this->container['deleted_by_user_id'] = $deleted_by_user_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


