<?php
declare(strict_types=1);
/**
 * TotalRewardsEquityGrowthChartItem
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  BhrSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BambooHR API
 *
 * BambooHR API documentation. https://www.bamboohr.com/api/documentation/
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace BhrSdk\Model;

use \ArrayAccess;
use \BhrSdk\ObjectSerializer;

/**
 * TotalRewardsEquityGrowthChartItem Class Doc Comment
 *
 * @category Class
 * @description Schema for total rewards equity growth chart item
 * @package  BhrSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TotalRewardsEquityGrowthChartItem implements ModelInterface, ArrayAccess, \JsonSerializable {
	public const DISCRIMINATOR = null;

	/**
	  * The original name of the model.
	  *
	  * @var string
	  */
	protected static $openApiModelName = 'TotalRewards-EquityGrowthChartItem';

	/**
	  * Array of property to type mappings. Used for (de)serialization
	  *
	  * @var string[]
	  */
	protected static $openApiTypes = [
		'label' => 'string',
		'estimated_net_value' => 'string',
		'subvalue' => 'string',
		'vested' => 'float',
		'current' => 'float',
		'unvested' => 'float'
	];

	/**
	  * Array of property to format mappings. Used for (de)serialization
	  *
	  * @var string[]
	  * @phpstan-var array<string, string|null>
	  * @psalm-var array<string, string|null>
	  */
	protected static $openApiFormats = [
		'label' => null,
		'estimated_net_value' => null,
		'subvalue' => null,
		'vested' => 'float',
		'current' => 'float',
		'unvested' => 'float'
	];

	/**
	  * Array of nullable properties. Used for (de)serialization
	  *
	  * @var bool[]
	  * @phpstan-var array<string, bool>
	  */
	protected static array $openApiNullables = [
		'label' => false,
		'estimated_net_value' => false,
		'subvalue' => true,
		'vested' => true,
		'current' => true,
		'unvested' => true
	];

	/**
	  * If a nullable field gets set to null, insert it here
	  *
	  * @var bool[]
	  * @phpstan-var array<string, bool>
	  */
	protected array $openApiNullablesSetToNull = [];

	/**
	 * Array of property to type mappings. Used for (de)serialization
	 *
	 * @return array
	 */
	public static function openApiTypes() {
		return self::$openApiTypes;
	}

	/**
	 * Array of property to format mappings. Used for (de)serialization
	 *
	 * @return array
	 */
	public static function openApiFormats() {
		return self::$openApiFormats;
	}

	/**
	 * Array of nullable properties
	 *
	 * @return array
	 */
	protected static function openApiNullables(): array {
		return self::$openApiNullables;
	}

	/**
	 * Array of nullable field names deliberately set to null
	 *
	 * @return bool[]
	 * @phpstan-return array<string, bool>
	 */
	private function getOpenApiNullablesSetToNull(): array {
		return $this->openApiNullablesSetToNull;
	}

	/**
	 * Setter - Array of nullable field names deliberately set to null
	 *
	 * @param bool[] $openApiNullablesSetToNull
	 * @phpstan-param array<string, bool> $openApiNullablesSetToNull
	 */
	private function setOpenApiNullablesSetToNull(array $openApiNullablesSetToNull): void {
		$this->openApiNullablesSetToNull = $openApiNullablesSetToNull;
	}

	/**
	 * Checks if a property is nullable
	 *
	 * @param string $property
	 * @return bool
	 */
	public static function isNullable(string $property): bool {
		return self::openApiNullables()[$property] ?? false;
	}

	/**
	 * Checks if a nullable property is set to null.
	 *
	 * @param string $property
	 * @return bool
	 */
	public function isNullableSetToNull(string $property): bool {
		return isset($this->getOpenApiNullablesSetToNull()[$property]);
	}

	/**
	 * Array of attributes where the key is the local name,
	 * and the value is the original name
	 *
	 * @var string[]
	 */
	protected static $attributeMap = [
		'label' => 'label',
		'estimated_net_value' => 'estimatedNetValue',
		'subvalue' => 'subvalue',
		'vested' => 'vested',
		'current' => 'current',
		'unvested' => 'unvested'
	];

	/**
	 * Array of attributes to setter functions (for deserialization of responses)
	 *
	 * @var string[]
	 */
	protected static $setters = [
		'label' => 'setLabel',
		'estimated_net_value' => 'setEstimatedNetValue',
		'subvalue' => 'setSubvalue',
		'vested' => 'setVested',
		'current' => 'setCurrent',
		'unvested' => 'setUnvested'
	];

	/**
	 * Array of attributes to getter functions (for serialization of requests)
	 *
	 * @var string[]
	 */
	protected static $getters = [
		'label' => 'getLabel',
		'estimated_net_value' => 'getEstimatedNetValue',
		'subvalue' => 'getSubvalue',
		'vested' => 'getVested',
		'current' => 'getCurrent',
		'unvested' => 'getUnvested'
	];

	/**
	 * Array of attributes where the key is the local name,
	 * and the value is the original name
	 *
	 * @return array
	 */
	public static function attributeMap() {
		return self::$attributeMap;
	}

	/**
	 * Array of attributes to setter functions (for deserialization of responses)
	 *
	 * @return array
	 */
	public static function setters() {
		return self::$setters;
	}

	/**
	 * Array of attributes to getter functions (for serialization of requests)
	 *
	 * @return array
	 */
	public static function getters() {
		return self::$getters;
	}

	/**
	 * The original name of the model.
	 *
	 * @return string
	 */
	public function getModelName() {
		return self::$openApiModelName;
	}

	/**
	 * Associative array for storing property values
	 *
	 * @var mixed[]
	 */
	protected $container = [];

	/**
	 * Constructor
	 *
	 * @param mixed[]|null $data Associated array of property values
	 *                           initializing the model
	 */
	public function __construct(?array $data = null) {
		$this->setIfExists('label', $data ?? [], null);
		$this->setIfExists('estimated_net_value', $data ?? [], null);
		$this->setIfExists('subvalue', $data ?? [], null);
		$this->setIfExists('vested', $data ?? [], null);
		$this->setIfExists('current', $data ?? [], null);
		$this->setIfExists('unvested', $data ?? [], null);
	}

	/**
	* Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
	* is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
	* $this->openApiNullablesSetToNull array
	*
	* @param string $variableName
	* @param array  $fields
	* @param mixed  $defaultValue
	*/
	private function setIfExists(string $variableName, array $fields, $defaultValue): void {
		if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
			$this->openApiNullablesSetToNull[$variableName] = true;
		}

		$this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
	}

	/**
	 * Show all the invalid properties with reasons.
	 *
	 * @return array invalid properties with reasons
	 */
	public function listInvalidProperties() {
		$invalidProperties = [];

		return $invalidProperties;
	}

	/**
	 * Validate all the properties in the model
	 * return true if all passed
	 *
	 * @return bool True if all properties are valid
	 */
	public function valid() {
		return count($this->listInvalidProperties()) === 0;
	}

	/**
	 * Gets label
	 *
	 * @return string|null
	 */
	public function getLabel() {
		return $this->container['label'];
	}

	/**
	 * Sets label
	 *
	 * @param string|null $label Label
	 *
	 * @return self
	 */
	public function setLabel($label) {
		if (is_null($label)) {
			throw new \InvalidArgumentException('non-nullable label cannot be null');
		}
		$this->container['label'] = $label;

		return $this;
	}

	/**
	 * Gets estimated_net_value
	 *
	 * @return string|null
	 */
	public function getEstimatedNetValue() {
		return $this->container['estimated_net_value'];
	}

	/**
	 * Sets estimated_net_value
	 *
	 * @param string|null $estimated_net_value Estimated value
	 *
	 * @return self
	 */
	public function setEstimatedNetValue($estimated_net_value) {
		if (is_null($estimated_net_value)) {
			throw new \InvalidArgumentException('non-nullable estimated_net_value cannot be null');
		}
		$this->container['estimated_net_value'] = $estimated_net_value;

		return $this;
	}

	/**
	 * Gets subvalue
	 *
	 * @return string|null
	 */
	public function getSubvalue() {
		return $this->container['subvalue'];
	}

	/**
	 * Sets subvalue
	 *
	 * @param string|null $subvalue subvalue
	 *
	 * @return self
	 */
	public function setSubvalue($subvalue) {
		if (is_null($subvalue)) {
			$this->openApiNullablesSetToNull['subvalue'] = true;
		} else {
			$nullablesSetToNull = $this->getOpenApiNullablesSetToNull();
			if (isset($nullablesSetToNull['subvalue'])) {
				unset($nullablesSetToNull['subvalue']);
				$this->setOpenApiNullablesSetToNull($nullablesSetToNull);
			}
		}
		$this->container['subvalue'] = $subvalue;

		return $this;
	}

	/**
	 * Gets vested
	 *
	 * @return float|null
	 */
	public function getVested() {
		return $this->container['vested'];
	}

	/**
	 * Sets vested
	 *
	 * @param float|null $vested vested
	 *
	 * @return self
	 */
	public function setVested($vested) {
		if (is_null($vested)) {
			$this->openApiNullablesSetToNull['vested'] = true;
		} else {
			$nullablesSetToNull = $this->getOpenApiNullablesSetToNull();
			if (isset($nullablesSetToNull['vested'])) {
				unset($nullablesSetToNull['vested']);
				$this->setOpenApiNullablesSetToNull($nullablesSetToNull);
			}
		}
		$this->container['vested'] = $vested;

		return $this;
	}

	/**
	 * Gets current
	 *
	 * @return float|null
	 */
	public function getCurrent() {
		return $this->container['current'];
	}

	/**
	 * Sets current
	 *
	 * @param float|null $current current
	 *
	 * @return self
	 */
	public function setCurrent($current) {
		if (is_null($current)) {
			$this->openApiNullablesSetToNull['current'] = true;
		} else {
			$nullablesSetToNull = $this->getOpenApiNullablesSetToNull();
			if (isset($nullablesSetToNull['current'])) {
				unset($nullablesSetToNull['current']);
				$this->setOpenApiNullablesSetToNull($nullablesSetToNull);
			}
		}
		$this->container['current'] = $current;

		return $this;
	}

	/**
	 * Gets unvested
	 *
	 * @return float|null
	 */
	public function getUnvested() {
		return $this->container['unvested'];
	}

	/**
	 * Sets unvested
	 *
	 * @param float|null $unvested unvested
	 *
	 * @return self
	 */
	public function setUnvested($unvested) {
		if (is_null($unvested)) {
			$this->openApiNullablesSetToNull['unvested'] = true;
		} else {
			$nullablesSetToNull = $this->getOpenApiNullablesSetToNull();
			if (isset($nullablesSetToNull['unvested'])) {
				unset($nullablesSetToNull['unvested']);
				$this->setOpenApiNullablesSetToNull($nullablesSetToNull);
			}
		}
		$this->container['unvested'] = $unvested;

		return $this;
	}
	/**
	 * Returns true if offset exists. False otherwise.
	 *
	 * @param string $offset Offset
	 *
	 * @return boolean
	 */
	public function offsetExists($offset): bool {
		return isset($this->container[$offset]);
	}

	/**
	 * Gets offset.
	 *
	 * @param string $offset Offset
	 *
	 * @return mixed|null
	 */
	#[\ReturnTypeWillChange]
	public function offsetGet($offset) {
		return $this->container[$offset] ?? null;
	}

	/**
	 * Sets value based on offset.
	 *
	 * @param string|null $offset Offset
	 * @param mixed    $value  Value to be set
	 *
	 * @return void
	 */
	public function offsetSet($offset, $value): void {
		if (is_null($offset)) {
			$this->container[] = $value;
		} else {
			$this->container[$offset] = $value;
		}
	}

	/**
	 * Unsets offset.
	 *
	 * @param string $offset Offset
	 *
	 * @return void
	 */
	public function offsetUnset($offset): void {
		unset($this->container[$offset]);
	}

	/**
	 * Serializes the object to a value that can be serialized natively by json_encode().
	 * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
	 *
	 * @return mixed Returns data which can be serialized by json_encode(), which is a value
	 * of any type other than a resource.
	 */
	#[\ReturnTypeWillChange]
	public function jsonSerialize() {
	   return ObjectSerializer::sanitizeForSerialization($this);
	}

	/**
	 * Gets the string presentation of the object
	 *
	 * @return string
	 */
	public function __toString(): string {
		$jsonEncoded = json_encode(
			ObjectSerializer::sanitizeForSerialization($this),
			JSON_PRETTY_PRINT
		);
		return $jsonEncoded === false ? '{}' : $jsonEncoded;
	}

	/**
	 * Gets a header-safe presentation of the object
	 *
	 * @return string
	 */
	public function toHeaderValue(): string {
		$jsonEncoded = json_encode(ObjectSerializer::sanitizeForSerialization($this));
		return $jsonEncoded === false ? '{}' : $jsonEncoded;
	}
}

