<?php
/**
 * ApprovalGroupDataObjectTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BambooHR API
 *
 * BambooHR API documentation. https://www.bamboohr.com/api/documentation/
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ApprovalGroupDataObjectTest Class Doc Comment
 *
 * @category    Class
 * @description Data object representing a group of employees with their approval flow
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ApprovalGroupDataObjectTest extends TestCase {

	/**
	 * Setup before running any test case
	 */
	public static function setUpBeforeClass(): void {
	}

	/**
	 * Setup before running each test case
	 */
	public function setUp(): void {
	}

	/**
	 * Clean up after running each test case
	 */
	public function tearDown(): void {
	}

	/**
	 * Clean up after running all test cases
	 */
	public static function tearDownAfterClass(): void {
	}

	/**
	 * Test "ApprovalGroupDataObject"
	 */
	public function testApprovalGroupDataObject() {
		// TODO: implement
		self::markTestIncomplete('Not implemented');
	}

	/**
	 * Test attribute "employee_ids"
	 */
	public function testPropertyEmployeeIds() {
		// TODO: implement
		self::markTestIncomplete('Not implemented');
	}

	/**
	 * Test attribute "template_id"
	 */
	public function testPropertyTemplateId() {
		// TODO: implement
		self::markTestIncomplete('Not implemented');
	}

	/**
	 * Test attribute "flow_data"
	 */
	public function testPropertyFlowData() {
		// TODO: implement
		self::markTestIncomplete('Not implemented');
	}

	/**
	 * Test attribute "group_id"
	 */
	public function testPropertyGroupId() {
		// TODO: implement
		self::markTestIncomplete('Not implemented');
	}
}
