<?php
declare(strict_types=1);
/**
 * ClockEntriesSchemaTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  BhrSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BambooHR API
 *
 * BambooHR API documentation. https://www.bamboohr.com/api/documentation/
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace BhrSdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ClockEntriesSchemaTest Class Doc Comment
 *
 * @category    Class
 * @description Request body schema for operations involving multiple clock entries
 * @package     BhrSdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ClockEntriesSchemaTest extends TestCase {

	/**
	 * Setup before running any test case
	 */
	public static function setUpBeforeClass(): void {
	}

	/**
	 * Setup before running each test case
	 */
	public function setUp(): void {
	}

	/**
	 * Clean up after running each test case
	 */
	public function tearDown(): void {
	}

	/**
	 * Clean up after running all test cases
	 */
	public static function tearDownAfterClass(): void {
	}

	/**
	 * Test "ClockEntriesSchema"
	 */
	public function testClockEntriesSchema(): void {
		// TODO: implement
		self::markTestIncomplete('Not implemented');
	}

	/**
	 * Test attribute "entries"
	 */
	public function testPropertyEntries(): void {
		// TODO: implement
		self::markTestIncomplete('Not implemented');
	}
}
