<?php
/**
 * ProjectedPrepaymentResponseTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BambooHR API
 *
 * BambooHR API documentation. https://www.bamboohr.com/api/documentation/
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ProjectedPrepaymentResponseTest Class Doc Comment
 *
 * @category    Class
 * @description Schema for projected prepayment details.
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ProjectedPrepaymentResponseTest extends TestCase {

	/**
	 * Setup before running any test case
	 */
	public static function setUpBeforeClass(): void {
	}

	/**
	 * Setup before running each test case
	 */
	public function setUp(): void {
	}

	/**
	 * Clean up after running each test case
	 */
	public function tearDown(): void {
	}

	/**
	 * Clean up after running all test cases
	 */
	public static function tearDownAfterClass(): void {
	}

	/**
	 * Test "ProjectedPrepaymentResponse"
	 */
	public function testProjectedPrepaymentResponse() {
		// TODO: implement
		self::markTestIncomplete('Not implemented');
	}

	/**
	 * Test attribute "invoice_items"
	 */
	public function testPropertyInvoiceItems() {
		// TODO: implement
		self::markTestIncomplete('Not implemented');
	}

	/**
	 * Test attribute "subtotal"
	 */
	public function testPropertySubtotal() {
		// TODO: implement
		self::markTestIncomplete('Not implemented');
	}

	/**
	 * Test attribute "tax"
	 */
	public function testPropertyTax() {
		// TODO: implement
		self::markTestIncomplete('Not implemented');
	}

	/**
	 * Test attribute "total"
	 */
	public function testPropertyTotal() {
		// TODO: implement
		self::markTestIncomplete('Not implemented');
	}

	/**
	 * Test attribute "account_balance"
	 */
	public function testPropertyAccountBalance() {
		// TODO: implement
		self::markTestIncomplete('Not implemented');
	}

	/**
	 * Test attribute "discounts"
	 */
	public function testPropertyDiscounts() {
		// TODO: implement
		self::markTestIncomplete('Not implemented');
	}

	/**
	 * Test attribute "customer_details"
	 */
	public function testPropertyCustomerDetails() {
		// TODO: implement
		self::markTestIncomplete('Not implemented');
	}

	/**
	 * Test attribute "payment_information"
	 */
	public function testPropertyPaymentInformation() {
		// TODO: implement
		self::markTestIncomplete('Not implemented');
	}
}
