<?php
declare(strict_types=1);
/**
 * UpdateTrainingTypeRequestCategoryTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  BhrSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BambooHR API
 *
 * BambooHR API documentation. https://www.bamboohr.com/api/documentation/
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace BhrSdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * UpdateTrainingTypeRequestCategoryTest Class Doc Comment
 *
 * @category    Class
 * @description Category is optional and passing an empty value will remove the category from the training type. Passing a name will assign the training type to the new training category.
 * @package     BhrSdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class UpdateTrainingTypeRequestCategoryTest extends TestCase {

	/**
	 * Setup before running any test case
	 */
	public static function setUpBeforeClass(): void {
	}

	/**
	 * Setup before running each test case
	 */
	public function setUp(): void {
	}

	/**
	 * Clean up after running each test case
	 */
	public function tearDown(): void {
	}

	/**
	 * Clean up after running all test cases
	 */
	public static function tearDownAfterClass(): void {
	}

	/**
	 * Test "UpdateTrainingTypeRequestCategory"
	 */
	public function testUpdateTrainingTypeRequestCategory(): void {
		// TODO: implement
		self::markTestIncomplete('Not implemented');
	}

	/**
	 * Test attribute "id"
	 */
	public function testPropertyId(): void {
		// TODO: implement
		self::markTestIncomplete('Not implemented');
	}

	/**
	 * Test attribute "name"
	 */
	public function testPropertyName(): void {
		// TODO: implement
		self::markTestIncomplete('Not implemented');
	}

	/**
	 * Test attribute "accuracy"
	 */
	public function testPropertyAccuracy(): void {
		// TODO: implement
		self::markTestIncomplete('Not implemented');
	}

	/**
	 * Test attribute "address"
	 */
	public function testPropertyAddress(): void {
		// TODO: implement
		self::markTestIncomplete('Not implemented');
	}
}
