<?php
declare(strict_types=1);
/**
 * EmployeeFilesApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  BhrSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BambooHR API
 *
 * BambooHR API documentation. https://www.bamboohr.com/api/documentation/
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BhrSdk\Test\Api;

use \BhrSdk\Configuration;
use \BhrSdk\ApiException;
use \BhrSdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * EmployeeFilesApiTest Class Doc Comment
 *
 * @category Class
 * @package  BhrSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EmployeeFilesApiTest extends TestCase {

	/**
	 * Setup before running any test cases
	 */
	public static function setUpBeforeClass(): void {
	}

	/**
	 * Setup before running each test case
	 */
	public function setUp(): void {
	}

	/**
	 * Clean up after running each test case
	 */
	public function tearDown(): void {
	}

	/**
	 * Clean up after running all test cases
	 */
	public static function tearDownAfterClass(): void {
	}

	/**
	 * Test case for addEmployeeFileCategory
	 *
	 * Add Employee File Category.
	 *
	 */
	public function testAddEmployeeFileCategory(): void {
		// TODO: implement
		self::markTestIncomplete('Not implemented');
	}

	/**
	 * Test case for deleteEmployeeFile
	 *
	 * Delete Employee File.
	 *
	 */
	public function testDeleteEmployeeFile(): void {
		// TODO: implement
		self::markTestIncomplete('Not implemented');
	}

	/**
	 * Test case for getEmployeeFile
	 *
	 * Get an Employee File.
	 *
	 */
	public function testGetEmployeeFile(): void {
		// TODO: implement
		self::markTestIncomplete('Not implemented');
	}

	/**
	 * Test case for listEmployeeFiles
	 *
	 * List employee files and categories.
	 *
	 */
	public function testListEmployeeFiles(): void {
		// TODO: implement
		self::markTestIncomplete('Not implemented');
	}

	/**
	 * Test case for updateEmployeeFile
	 *
	 * Update Employee File.
	 *
	 */
	public function testUpdateEmployeeFile(): void {
		// TODO: implement
		self::markTestIncomplete('Not implemented');
	}

	/**
	 * Test case for uploadEmployeeFile
	 *
	 * Upload Employee File.
	 *
	 */
	public function testUploadEmployeeFile(): void {
		// TODO: implement
		self::markTestIncomplete('Not implemented');
	}
}
