<?php
declare(strict_types=1);
/**
 * HolidaysApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  BhrSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BambooHR API
 *
 * BambooHR API documentation. https://documentation.bamboohr.com/
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BhrSdk\Test\Api;

use \BhrSdk\Configuration;
use \BhrSdk\ApiException;
use \BhrSdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * HolidaysApiTest Class Doc Comment
 *
 * @category Class
 * @package  BhrSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class HolidaysApiTest extends TestCase {

	/**
	 * Setup before running any test cases
	 */
	public static function setUpBeforeClass(): void {
	}

	/**
	 * Setup before running each test case
	 */
	public function setUp(): void {
	}

	/**
	 * Clean up after running each test case
	 */
	public function tearDown(): void {
	}

	/**
	 * Clean up after running all test cases
	 */
	public static function tearDownAfterClass(): void {
	}

	/**
	 * Test case for bulkInsertCompanyHolidays
	 *
	 * Bulk Create Company Holidays.
	 *
	 */
	public function testBulkInsertCompanyHolidays(): void {
		// TODO: implement
		self::markTestIncomplete('Not implemented');
	}

	/**
	 * Test case for createCompanyHoliday
	 *
	 * Create Company Holiday.
	 *
	 */
	public function testCreateCompanyHoliday(): void {
		// TODO: implement
		self::markTestIncomplete('Not implemented');
	}

	/**
	 * Test case for deleteCompanyHoliday
	 *
	 * Delete Company Holiday.
	 *
	 */
	public function testDeleteCompanyHoliday(): void {
		// TODO: implement
		self::markTestIncomplete('Not implemented');
	}

	/**
	 * Test case for getCatalogHoliday
	 *
	 * Get Catalog Holiday.
	 *
	 */
	public function testGetCatalogHoliday(): void {
		// TODO: implement
		self::markTestIncomplete('Not implemented');
	}

	/**
	 * Test case for getCompanyHoliday
	 *
	 * Get Company Holiday.
	 *
	 */
	public function testGetCompanyHoliday(): void {
		// TODO: implement
		self::markTestIncomplete('Not implemented');
	}

	/**
	 * Test case for listCatalogHolidays
	 *
	 * List Catalog Holidays.
	 *
	 */
	public function testListCatalogHolidays(): void {
		// TODO: implement
		self::markTestIncomplete('Not implemented');
	}

	/**
	 * Test case for listCompanyHolidays
	 *
	 * List Company Holidays.
	 *
	 */
	public function testListCompanyHolidays(): void {
		// TODO: implement
		self::markTestIncomplete('Not implemented');
	}

	/**
	 * Test case for updateCompanyHoliday
	 *
	 * Update Company Holiday.
	 *
	 */
	public function testUpdateCompanyHoliday(): void {
		// TODO: implement
		self::markTestIncomplete('Not implemented');
	}
}
