<?php
/**
 * HoursApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  MySdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BambooHR API
 *
 * BambooHR API documentation. https://www.bamboohr.com/api/documentation/
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace MySdk\Test\Api;

use \MySdk\Configuration;
use \MySdk\ApiException;
use \MySdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * HoursApiTest Class Doc Comment
 *
 * @category Class
 * @package  MySdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class HoursApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for call0f428442e53dc46d1e2c8ff5b7a483a8
     *
     * addTimeTrackingBulk.
     *
     */
    public function testCall0f428442e53dc46d1e2c8ff5b7a483a8()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for call14e73aef978eb81d51fdbd74e0e83823
     *
     * adjustTimeTracking.
     *
     */
    public function testCall14e73aef978eb81d51fdbd74e0e83823()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for call5e1c5b4ef12e61d1bc975e8b4e00c38d
     *
     * getTimeTrackingByTimeTrackingId.
     *
     */
    public function testCall5e1c5b4ef12e61d1bc975e8b4e00c38d()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for call69c777478f5d52dee1b4f0937dca154f
     *
     * addTimeTracking.
     *
     */
    public function testCall69c777478f5d52dee1b4f0937dca154f()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for f97efc203b25647724accb9da7dda7db
     *
     * deleteTimeTrackingByTimeTrackingId.
     *
     */
    public function testF97efc203b25647724accb9da7dda7db()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
